# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/mmi_glink_charger
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/mmi_glink_charger/device_glink
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/mmi_glink_charger/qti_glink_charger_v2
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
    EXTRA_CFLAGS += -DMMI_GKI_API_ALLOWANCE
endif


obj-m += mmi_glink_charger.o

mmi_glink_charger-objs := mmi_glink_core.o device_class.o battery_host.o trusted_shash_lib.o
mmi_glink_charger-objs += device_glink/battery_glink.o
mmi_glink_charger-objs += device_glink/wireless_charge_glink.o
mmi_glink_charger-objs += device_glink/charge_pump_glink.o
mmi_glink_charger-objs += device_glink/balance_charge_glink.o
mmi_glink_charger-objs += device_glink/switch_buck_glink.o
mmi_glink_charger-objs += device_glink/usb_glink.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../mmi_relay/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../bm_adsp_ulog/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/qti_glink_charger_v2/$(GKI_OBJ_MODULE_DIR)/Module.symvers
