# add -Wall to try to catch everything we can.

ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel_platform/common
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/moto_sched

ifneq ($(filter m y,$(CONFIG_MTK_SCHED_VIP_TASK)),)
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-6.1
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1
endif

mm_iosched-objs := iosched.o iosched_sysctl.o iosched_cgroup.o iosched_util.o
obj-m +=  mm_iosched.o
