# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/input/touchscreen/ilitek_mtk_mmi \
		-I$(TOP)/motorola/kernel/modules/drivers/input/touchscreen/ilitek_mtk_mmi/firmware

obj-m += ilitek_mtk_mmi.o


ifneq ($(filter m y,$(CONFIG_INPUT_ILI_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DILI_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_ILI_PANEL_NOTIFICATIONS)),)
EXTRA_CFLAGS += -DILI_CONFIG_PANEL_NOTIFICATIONS
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_RESUME_BY_DDI)),)
EXTRA_CFLAGS += -DILI_CONFIG_RESUME_BY_DDI
endif
ifneq ($(filter m y,$(CONFIG_INPUT_ILI_DECTECT_LCM_NAME)),)
EXTRA_CFLAGS += -DILI_DECTECT_LCM_NAME
endif

ilitek_mtk_mmi-objs += ilitek_v3.o
ilitek_mtk_mmi-objs += ilitek_v3_spi.o
ilitek_mtk_mmi-objs += ilitek_v3_mtk.o
ilitek_mtk_mmi-objs += ilitek_v3_ic.o
ilitek_mtk_mmi-objs += ilitek_v3_touch.o
ilitek_mtk_mmi-objs += ilitek_v3_mp.o
ilitek_mtk_mmi-objs += ilitek_v3_hostdl.o
ilitek_mtk_mmi-objs += ilitek_v3_node.o
