DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

ifneq ($(BOARD_USES_DOUBLE_TAP),)
	KERNEL_CFLAGS += CONFIG_INPUT_ILI_ENABLE_DOUBLE_TAP=y
endif

ifeq ($(BOARD_USES_DOUBLE_TAP_CTRL),true)
	KERNEL_CFLAGS += CONFIG_BOARD_USES_DOUBLE_TAP_CTRL=y
endif

ifneq ($(CONFIG_INPUT_SET_TOUCH_STATE),)
	KERNEL_CFLAGS += CONFIG_INPUT_ILI_SET_TOUCH_STATE=y
endif

ifneq ($(BOARD_USES_PANEL_NOTIFICATIONS),)
	KERNEL_CFLAGS += CONFIG_INPUT_ILI_PANEL_NOTIFICATIONS=y
endif

ifneq ($(BOARD_USES_MTK_CHECK_PANEL),)
	KERNEL_CFLAGS += CONFIG_ILITEK_MTK_CHECK_PANEL=y
endif

ifeq ($(ILITEK_MULTI_TP_MODULE),true)
	KERNEL_CFLAGS += CONFIG_ILITEK_MULTI_TP_MODULE=y
endif

ifeq ($(ILITEK_FW_MULTI_CHIP),true)
	KERNEL_CFLAGS += CONFIG_ILITEK_FW_MULTI_CHIP=y
endif

ifneq ($(ILITEK_RESUME_BY_DDI),)
	KERNEL_CFLAGS += CONFIG_ILITEK_RESUME_BY_DDI=y
endif

ifeq ($(CONFIG_INPUT_CHARGER_DETECTION),true)
	KERNEL_CFLAGS += CONFIG_ILITEK_CHARGER=y
endif

ifeq ($(ILITEK_ESD),true)
	KERNEL_CFLAGS += CONFIG_ILITEK_ESD=y
endif

ifeq ($(ILITEK_GESTURE),true)
	KERNEL_CFLAGS += CONFIG_ILITEK_GESTURE=y
endif

ifeq ($(TOUCHSCREEN_LAST_TIME),true)
	KERNEL_CFLAGS += CONFIG_ILI_TOUCH_LAST_TIME=y
endif

ifeq ($(ILITEK_PASSIVE_PEN),true)
	KERNEL_CFLAGS += CONFIG_ILITEK_PASSIVE_PEN=y
endif

ifneq ($(BOARD_USES_PEN_NOTIFIER),)
	KERNEL_CFLAGS += CONFIG_INPUT_ILITEK_MMI_PEN_NOTIFIER=y
endif

ifeq ($(GTP_ENABLE_DDA_STYLUS),true)
	KBUILD_OPTIONS += CONFIG_GTP_DDA_STYLUS=y
endif

include $(CLEAR_VARS)

ifneq ($(BOARD_USES_DOUBLE_TAP),)
LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/sensors_class.ko
LOCAL_REQUIRED_MODULES := sensors_class.ko
endif

ifneq ($(BOARD_USES_PEN_NOTIFIER),)
LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/bu520xx_pen.ko
LOCAL_REQUIRED_MODULES += bu520xx_pen.ko
endif

LOCAL_MODULE := ili9882_mmi_v1.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
include $(DLKM_DIR)/AndroidKernelModule.mk
