# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/gpu/drm/mediatek/mediatek_v2/
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/ili9882_mmi_v1 \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/ili9882_mmi_v1/firmware

ifeq ($(filter m y, $(CONFIG_TOUCHSCREEN_ILITEK_CHIPSET)),)
	obj-m += ili9882_mmi_v1.o
endif

ifneq ($(filter m y,$(CONFIG_INPUT_ILI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DILI_SENSOR_EN
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DILI_DOUBLE_TAP_CTRL
	EXTRA_CFLAGS += -DILI_PRIMARY_NODE
endif

ifneq ($(filter m y,$(CONFIG_INPUT_ILI_SET_TOUCH_STATE)),)
	EXTRA_CFLAGS += -DILI_SET_TOUCH_STATE
endif

ifneq ($(filter m y,$(CONFIG_INPUT_ILI_PANEL_NOTIFICATIONS)),)
EXTRA_CFLAGS += -DILI_CONFIG_PANEL_NOTIFICATIONS
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_RESUME_BY_DDI)),)
EXTRA_CFLAGS += -DILI_CONFIG_RESUME_BY_DDI
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_CHARGER)),)
EXTRA_CFLAGS += -DILI_CONFIG_MTK_CHARGER
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_ESD)),)
EXTRA_CFLAGS += -DILI_CONFIG_ESD
endif

ifneq ($(filter m y,$(CONFIG_ILITEK_MTK_CHECK_PANEL)),)
	EXTRA_CFLAGS += -DILI_MTK_CHECK_PANEL
endif

ifneq ($(filter m y,$(CONFIG_ILITEK_MULTI_TP_MODULE)),)
	EXTRA_CFLAGS += -DILI_TP_MODULE_EN
endif

ifneq ($(filter m y,$(CONFIG_ILITEK_FW_MULTI_CHIP)),)
	EXTRA_CFLAGS += -DILI_FW_MULTI_CHIP_EN
endif

ifneq ($(filter m y,$(CONFIG_ILI_TOUCH_LAST_TIME)),)
	EXTRA_CFLAGS += -DILI_TOUCH_LAST_TIME
endif

ifneq ($(filter m y,$(CONFIG_ILITEK_PASSIVE_PEN)),)
	EXTRA_CFLAGS += -DILI_PASSIVE_PEN
endif

ifneq ($(filter m y,$(CONFIG_INPUT_ILITEK_MMI_PEN_NOTIFIER)),)
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../misc/pen/$(GKI_OBJ_MODULE_DIR)/Module.symvers
	EXTRA_CFLAGS += -DILITEK_PEN_NOTIFIER
endif

ifneq ($(filter m y,$(CONFIG_GTP_DDA_STYLUS)),)
    EXTRA_CFLAGS += -DCONFIG_MOTO_DDA_PASSIVESTYLUS
endif

ili9882_mmi_v1-objs += ili9882_v1.o
ili9882_mmi_v1-objs += ili9882_v1_spi.o
ili9882_mmi_v1-objs += ili9882_v1_qcom.o
ili9882_mmi_v1-objs += ili9882_v1_ic.o
ili9882_mmi_v1-objs += ili9882_v1_touch.o
ili9882_mmi_v1-objs += ili9882_v1_mp.o
ili9882_mmi_v1-objs += ili9882_v1_hostdl.o
ili9882_mmi_v1-objs += ili9882_v1_node.o
ifneq ($(filter m y,$(CONFIG_GTP_DDA_STYLUS)),)
ili9882_mmi_v1-objs += moto_ts_dda.o
endif
