# add -Wall to try to catch everything we can.
ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

ifeq ($(DEVICE_MODULES_PATH),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += \
		-I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/

$(warning "wengjun2 DEVICE_MODULES_PATH = $(DEVICE_MODULES_PATH)")
$(warning "wengjun2 CONFIG_MTK_MET = $(CONFIG_MTK_MET)")
$(warning "wengjun2 TARGET_BUILD_VARIANT = $(TARGET_BUILD_VARIANT)")

ifneq ($(filter m y, $(CONFIG_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_PANEL_NOTIFICATIONS
endif
ifneq ($(filter m y, $(CONFIG_DRM_DYNAMIC_REFRESH_RATE)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_DYNAMIC_REFRESH_RATE
endif
ifneq ($(filter m y, $(CONFIG_TOUCHCLASS_MMI_DEBUG_INFO)),)
	EXTRA_CFLAGS += -DCONFIG_TOUCHCLASS_MMI_DEBUG_INFO
endif
ifneq ($(filter m y, $(CONFIG_TOUCHCLASS_MMI_GESTURE_POISON_EVENT)),)
	EXTRA_CFLAGS += -DTS_MMI_TOUCH_GESTURE_POISON_EVENT
endif
ifneq ($(filter m y, $(CONFIG_TOUCHCLASS_MMI_MULTIWAY_UPDATE_FW)),)
	EXTRA_CFLAGS += -DTS_MMI_TOUCH_MULTIWAY_UPDATE_FW
endif
ifneq ($(filter m y, $(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif
ifneq ($(filter m y, $(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif
ifneq ($(filter m y, $(CONFIG_TOUCH_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_PANEL_NOTIFICATIONS
endif
ifneq ($(filter m y, $(CONFIG_MTK_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_MTK_PANEL_NOTIFICATIONS
endif
ifneq ($(filter m y, $(CONFIG_TS_KERNEL_USE_GKI)),)
	EXTRA_CFLAGS += -DCONFIG_TS_KERNEL_USE_GKI
endif
ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

ifneq ($(filter m y, $(CONFIG_TOUCHCLASS_MMI_MTK_CHARGER)),)
	EXTRA_CFLAGS += -DCONFIG_TOUCHCLASS_MMI_MTK_CHARGER
endif

obj-m := touchscreen_u_mmi.o
touchscreen_u_mmi-objs := touchscreen_mmi_class.o touchscreen_mmi_panel.o touchscreen_mmi_notif.o touchscreen_mmi_gesture.o

KBUILD_EXTRA_SYMBOLS += $(KBUILD_EXTMOD)/../../sensors_class.ko_intermediates/LINKED/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(KBUILD_EXTMOD)/../../mmi_relay.ko_intermediates/LINKED/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/../../kernel/msm-$(MODULE_KERNEL_VERSION)/Module.symvers
