load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

define_mgk_ko(
    name = "cps4038_mmi",
    srcs = glob([
        "*.c",
        "*.h",
        "Kbuild",
        "Makefile",
        "Makefile.include",
    ]) + [
        "//kernel_device_modules-6.1:mtk_public_headers",
    ],

    outs = ["cps4038_mmi.ko"],
)
