DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

ifneq ($(FOCALTECH_TOUCH_IC_NAME),)
	KERNEL_CFLAGS += CONFIG_INPUT_FTS_MTK_V2_MMI_IC_NAME=$(FOCALTECH_TOUCH_IC_NAME)
else
	KERNEL_CFLAGS += CONFIG_INPUT_FTS_MTK_V2_MMI_IC_NAME=ft3519
endif

ifneq ($(FOCALTECH_TOUCH_TEST_SUPPORT),)
	KERNEL_CFLAGS += CONFIG_INPUT_FTS_TEST_SUPPORT=y
endif

include $(CLEAR_VARS)
LOCAL_MODULE := focaltech_mtk_v2_mmi.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
include $(DLKM_DIR)/AndroidKernelModule.mk
