DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

ifneq ($(FOCALTECH_TOUCH_IC_NAME),)
	KERNEL_CFLAGS += CONFIG_INPUT_FTS_MTK_V2_MMI_IC_NAME=$(FOCALTECH_TOUCH_IC_NAME)
else
	KERNEL_CFLAGS += CONFIG_INPUT_FTS_MTK_V2_MMI_IC_NAME=ft3519
endif

ifneq ($(BOARD_USES_DOUBLE_TAP),)
	KERNEL_CFLAGS += CONFIG_INPUT_FOCALTECH_MMI_ENABLE_DOUBLE_TAP=y
endif

ifeq ($(CONFIG_INPUT_FB_PANEL), true)
	KERNEL_CFLAGS += FOCALTECH_FB_PANEL=y
endif

ifneq ($(TOUCH_IC_POWER_RECOVER_EN),)
	KERNEL_CFLAGS += CONFIG_INPUT_FOCALTECH_POWER_RECOVER_EN=y
endif

ifneq ($(FOCALTECH_TOUCH_TEST_SUPPORT),)
	KERNEL_CFLAGS += CONFIG_INPUT_FTS_TEST_SUPPORT=y
endif

include $(CLEAR_VARS)
LOCAL_MODULE := focaltech_mtk_v2_mmi.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
include $(DLKM_DIR)/AndroidKernelModule.mk
