# SPDX-License-Identifier: GPL-2.0-or-later

# Google Wonder WiFi Virtual Device driver.

load("//build/kernel/kleaf:kernel.bzl", "checkpatch", "ddk_headers", "ddk_module")

checkpatch(
    name = "checkpatch",
    checkpatch_pl = "//common:scripts/checkpatch.pl",
)

filegroup(
    name = "wonder.kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/wlan:__subpackages__",
    ],
)

ddk_module(
    name = "wonder",
    srcs = glob([
        "**/*.h",
    ]) + [
        "band_config.c",
        "mac80211.c",
        "mac80211_txs.c",
        "main.c",
        "nl80211_ven_cmd.c",
        "ssr.c",
        "wondertap.c",
    ],
    out = "wonder.ko",
    conditional_srcs = {
        "CONFIG_DEBUG_FS": {
            True: [
                "debugfs.c",
            ],
        },
    },
    defconfig = "defconfig",
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel",
    visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/wlan:__subpackages__",
    ],
    deps = [
        "//common:all_headers_aarch64",
    ],
)

ddk_headers(
    name = "wonder_headers",
    hdrs = glob([
        "include/**/*.h",
    ]) + [
        "Makefile.include",
    ],
    includes = [
        "include",
    ],
    visibility = [
        # keep sorted
        "//private/devices/google:__subpackages__",
        "//private/google-modules/wlan:__subpackages__",
    ],
)
