# SPDX-License-Identifier: GPL-2.0
#
# This file should be included by external modules that need to link to this
# project.

KCFLAGS += -I$(ROOT_DIR)/motorola/kernel/modules/drivers/wonder/include

EXTRA_SYMBOLS += $(COMMON_OUT_DIR)/motorola/kernel/modules/drivers/wonder/wonder_Module.symvers
