# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ifneq ($(filter ctwo% arcfox% eiger%, $(TARGET_PRODUCT)),)
        EXTRA_CFLAGS += -DQCOM_NFC_CLK_REQ_WAKE_SET
endif

obj-m += st21nfc.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../mmi_info/Module.symvers
