# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \

#ifneq ($(filter m y,$(CONFIG_MMI_RELAY)),)
#	EXTRA_CFLAGS += -DMMI_RELAY_MODULE
#endif
#goodix_mtk_tee-y += gf_spi_tee.o gf_spi_factory.o

goodix_fps_tee-y += gf_spi_tee.o

obj-m += goodix_fps_tee.o

#KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_relay/$(GKI_OBJ_MODULE_DIR)/Module.symvers
