# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/gpu/drm/mediatek/mediatek_v2/
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/ilitek_v3_mmi \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/ilitek_v3_mmi/firmware

ifeq ($(filter m y, $(CONFIG_TOUCHSCREEN_ILITEK_CHIPSET)),)
	obj-m += ilitek_v3_mmi.o
endif

ifneq ($(filter m y,$(CONFIG_INPUT_ILI_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DILI_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_ILI_PANEL_NOTIFICATIONS)),)
EXTRA_CFLAGS += -DILI_CONFIG_PANEL_NOTIFICATIONS
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_RESUME_BY_DDI)),)
EXTRA_CFLAGS += -DILI_CONFIG_RESUME_BY_DDI
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_CHARGER)),)
EXTRA_CFLAGS += -DILI_CONFIG_MTK_CHARGER
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_ESD)),)
EXTRA_CFLAGS += -DILI_CONFIG_ESD
endif
ifneq ($(filter m y,$(CONFIG_ILITEK_GESTURE)),)
EXTRA_CFLAGS += -DILI_CONFIG_GESTURE
endif

ifneq ($(filter m y,$(CONFIG_ILITEK_MTK_CHECK_PANEL)),)
	EXTRA_CFLAGS += -DILI_MTK_CHECK_PANEL
endif

ilitek_v3_mmi-objs += ilitek_v3.o
ilitek_v3_mmi-objs += ilitek_v3_spi.o
ilitek_v3_mmi-objs += ilitek_v3_qcom.o
ilitek_v3_mmi-objs += ilitek_v3_ic.o
ilitek_v3_mmi-objs += ilitek_v3_touch.o
ilitek_v3_mmi-objs += ilitek_v3_mp.o
ilitek_v3_mmi-objs += ilitek_v3_hostdl.o
ilitek_v3_mmi-objs += ilitek_v3_node.o

