# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
                -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/usb/typec/aw35615

EXTRA_CFLAGS += \
                -DAW_HAVE_SNK \
		-DAW_HAVE_SRC \
		-DAW_HAVE_DRP \
		-DAW_HAVE_ACCMODE \
		-DAW_HAVE_EXT_MSG \
		-DAW_HAVE_VDM \
		-DAW_HAVE_DP

aw35615_objs  += aw35615_driver.o \
		aw35615_global.o \
		platform_helpers.o \
		dfs.o \
		core.o \
		PDPolicy.o \
		timer.o \
		PDProtocol.o \
		TypeC.o \
		Port.o \
		vendor_info.o \
		modules/dpm.o \
		modules/observer.o \
		vdm/bitfield_translators.o \
		vdm/vdm.o \
		vdm/vdm_callbacks.o \
		vdm/DisplayPort/dp.o

obj-m :=aw35615.o
aw35615-y := $(aw35615_objs)
