# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
    EXTRA_CFLAGS += -DCONFIG_FPSENSOR_LOG_ENABLE
endif

fpsensor_spi-y += fpsensor_spi_tee.o

obj-m += fpsensor_spi.o
