load("//build/kernel/kleaf:kernel.bzl", "ddk_headers", "ddk_uapi_headers")

package(
    default_visibility = [
        "//visibility:public",
    ],
)


filegroup(
    name = "moto_modules_headers",
    srcs = glob([
        "include/**/*.h",
    ]),
)

ddk_headers(
    name = "moto_modules_ddk_headers",
    hdrs = [
        # do not sort
        ":moto_modules_headers",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
)
