load("//build/kernel/kleaf:kernel.bzl", "ddk_headers", "ddk_uapi_headers")

package(
    default_visibility = [
        "//visibility:public",
    ],
)


filegroup(
    name = "moto_modules_headers",
    srcs = glob([
        "include/**/*.h",
    ]),
)

filegroup(
    name = "moto_kconfigs_group",
    srcs = [
         "//motorola/kernel/modules/drivers/input/touchscreen/goodix_thp:Kconfig",
         "//motorola/kernel/modules/drivers/input/touchscreen/synaptics_tcm2_mmi_v2:Kconfig",
         "//motorola/kernel/modules/drivers/input/touchscreen/goodix_berlin_mmi:Kconfig",
         "//motorola/kernel/modules/drivers/misc/sarsensor/awinic/aw963xx:Kconfig",
         "//motorola/kernel/modules/drivers/misc/sarsensor/semtech/sx937x:Kconfig",
         "//motorola/kernel/modules/drivers/moto_swap:Kconfig",
         "//motorola/kernel/modules/drivers/power/mmi_glink_charger:Kconfig",
         "//motorola/kernel/modules:Kconfig.moto",
         "//motorola/kernel/modules/drivers/moto_sched:Kconfig",
         "//motorola/kernel/modules/drivers/moto_reboot_reason:Kconfig",
         "//motorola/kernel/modules/drivers/wonder:Kconfig",
    ],
)

ddk_headers(
    name = "moto_modules_ddk_headers",
    hdrs = [
        # do not sort
        ":moto_modules_headers",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
)
