# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/power/bq2597x_mmi

obj-m += bq2597x_mmi.o
ifeq ($(findstring corfu, $(TARGET_PRODUCT)), corfu)
$(warning jianl: build bq2597x_charger.o)
bq2597x_mmi-objs += bq2597x_chg_mmi.o
else
bq2597x_mmi-objs += bq2597x_mmi.o
endif
