# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/kernel-5.10/include
EXTRA_CFLAGS += -I$(TOP)/kernel-5.10/include/uapi/

aw882xx_dlkm-objs = aw882xx.o aw_bin_parse.o aw_calib.o aw_device.o aw_dsp.o aw_init.o aw_monitor.o aw_spin.o
obj-m += aw882xx_dlkm.o

