ifeq (,$(KERNEL_DIR_PATH))
    KERNEL_DIR_PATH = $(shell find $(ANDROID_BUILD_TOP)/kernel/ -name "msm-*" -type d | head -1 | grep -i "kernel/msm-*")

    ifeq (,$(KERNEL_DIR_PATH))
        KERNEL_DIR_1_Level := true
        KERNEL_DIR_PATH = $(shell find $(ANDROID_BUILD_TOP)/kernel* -type d -name  "kernel-*" | head -1)
    endif
else
    KERNEL_DIR_1_Level := true
endif

KERNEL_VERSION_NAME = $(shell basename $(KERNEL_DIR_PATH))

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_SX937X_POWER_SUPPLY_ONLINE)),)
	EXTRA_CFLAGS += -DCONFIG_USE_POWER_SUPPLY_ONLINE
endif

ifneq ($(filter m y,$(CONFIG_SX937X_USB_CAL)),)
	EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq ($(filter m y,$(CONFIG_SX937X_FLIP_CAL)),)
	EXTRA_CFLAGS += -DCONFIG_CAPSENSE_FLIP_CAL
endif

ifneq ($(filter m y,$(CONFIG_SX937X_POWER_CONTROL_SUPPORT)),)
	EXTRA_CFLAGS += -DCONFIG_CAPSENSE_POWER_CONTROL_SUPPORT
endif

ifneq ($(filter m y,$(CONFIG_SX937X_MTK_KERNEL419_CHARGER_TYPE)),)
	EXTRA_CFLAGS += -DCONFIG_SX937X_MTK_KERNEL419_CHARGER_TYPE
endif

ifneq (,$(KERNEL_DIR_PATH))
        EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel/$(KERNEL_VERSION_NAME)/drivers/base

        ifeq ($(KERNEL_DIR_1_Level), true)
                EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/$(KERNEL_VERSION_NAME)/drivers/base
        endif
else
        EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel/drivers/base
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers

#sx937x_sar-y := sx937x_sar.o

obj-m += sx937x_sar.o

