DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

ifneq ($(FOCALTECH_TOUCH_IC_NAME),)
	KERNEL_CFLAGS += CONFIG_INPUT_FOCALTECH_V3_MMI_IC_NAME=$(FOCALTECH_TOUCH_IC_NAME)
else
	KERNEL_CFLAGS += CONFIG_INPUT_FOCALTECH_V3_MMI_IC_NAME=ft3681
endif

ifeq ($(BOARD_USES_DOUBLE_TAP),true)
	KERNEL_CFLAGS += CONFIG_INPUT_FOCALTECH_V3_MMI_ENABLE_DOUBLE_TAP=y
ifeq ($(FTS_DOUBLE_TAP_CONTROL),true)
	KERNEL_CFLAGS += CONFIG_FTS_DOUBLE_TAP_CONTROL=y
endif
endif

ifneq ($(BOARD_USES_TOUCH_PALM),)
	KERNEL_CFLAGS += CONFIG_INPUT_FOCALTECH_V3_MMI_ENABLE_PALM=y
endif

ifneq ($(BOARD_USES_PEN_NOTIFIER),)
	KERNEL_CFLAGS += CONFIG_INPUT_FOCALTECH_V3_MMI_PEN_NOTIFIER=y
endif

ifneq ($(findstring touchscreen_mmi.ko,$(PRODUCT_PACKAGES)),)
    KERNEL_CFLAGS += CONFIG_INPUT_TOUCHSCREEN_MMI=y
endif

ifeq ($(DRM_PANEL_EVENT_NOTIFICATIONS),true)
	KERNEL_CFLAGS += CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS=y
endif

ifeq ($(FTS_NOISE_TEST_P2P),true)
	KERNEL_CFLAGS += CONFIG_FTS_NOISE_TEST_P2P=y
endif

ifeq ($(FTS_COMPATIBLE_WITH_GKI),true)
	KERNEL_CFLAGS += CONFIG_FTS_COMPATIBLE_WITH_GKI=y
endif

ifeq ($(FTS_SUPPORT_HIGH_RESOLUTION),true)
	KERNEL_CFLAGS += CONFIG_FTS_SUPPORT_HIGH_RESOLUTION=y
endif

ifeq ($(MTK_PANEL_NOTIFICATIONS),true)
	 KERNEL_CFLAGS += CONFIG_MTK_PANEL_NOTIFICATIONS=y
endif

include $(CLEAR_VARS)
LOCAL_MODULE := focaltech_v3.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/mmi_info.ko
LOCAL_REQUIRED_MODULES := mmi_info.ko
ifneq ($(findstring touchscreen_mmi.ko,$(PRODUCT_PACKAGES)),)
	LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/touchscreen_mmi.ko
	LOCAL_REQUIRED_MODULES += touchscreen_mmi.ko
endif

KERNEL_CFLAGS_GKI += GKI_OBJ_MODULE_DIR=gki
KERNEL_CFLAGS_GKI += MODULE_KERNEL_VERSION=$(TARGET_KERNEL_VERSION)
include $(DLKM_DIR)/AndroidKernelModule.mk
