#MTK have kernel-4.14 and kernel-4.19 in the same dir,so we can't use below method
#KERNEL_DIR_PATH = $(shell find $(TOP)/kernel* -type d -name  "kernel-*" | head -1)
KERNEL_VERSION_NAME = $(shell basename $(KERNEL_DIR_PATH))

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/$(KERNEL_VERSION_NAME)/include
EXTRA_CFLAGS += -I$(TOP)/$(KERNEL_VERSION_NAME)/include/uapi/

aw883xx_dlkm-objs = aw883xx.o aw_monitor.o aw_bin_parse.o aw_device.o aw_init.o aw_calib.o
obj-m += aw883xx_dlkm.o

