# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include/uapi/
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/cps4035

obj-m += cps_wls_charger.o

