ifeq ($(ANDROID_BUILD_TOP),)
	ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/backlight/ktd3136_w_mmi \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1/include \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1/drivers/gpu/drm/panel \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.12/include \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.12/drivers/gpu/drm/panel \

obj-m += ktd3136_bl.o
