# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

ifneq ($(filter m y, $(ADAPTIVE_TOLERANCE_OPTIMIZATION)),)
	EXTRA_CFLAGS += -DADAPTIVE_TOLERANCE_OPTIMIZATION
endif

obj-m += qpnp_adaptive_charge.o
