# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/input/touchscreen/himax_mtk_mmi
EXTRA_CFLAGS += -DCONFIG_TOUCHSCREEN_HIMAX_DEBUG \
		-DCONFIG_TOUCHSCREEN_HIMAX_INSPECT

EXTRA_CFLAGS += -DCONFIG_TOUCHSCREEN_HIMAX_INCELL
EXTRA_CFLAGS += -DCONFIG_HMX_DB
EXTRA_CFLAGS += -D__HIMAX_MOD__

ifneq ($(filter y, $(HIMAX_CONFIG_KALLSYMS_ALL)),)
	EXTRA_CFLAGS += -D__KERNEL_KALLSYMS_ALL_ENABLED__
endif

obj-m := himax_mtk_mmi.o

himax_mtk_mmi-objs += himax_platform.o
himax_mtk_mmi-objs += himax_common.o
himax_mtk_mmi-objs += himax_debug.o
himax_mtk_mmi-objs += himax_ic_incell_core.o
himax_mtk_mmi-objs += himax_inspection.o

ifneq ($(filter hx83112,$(CONFIG_INPUT_HIMAX_MTK_MMI_IC_NAME)),)
	EXTRA_CFLAGS += -D__HIMAX_HX83112_MOD__
	EXTRA_CFLAGS += -DCONFIG_TOUCHSCREEN_HIMAX_IC_HX83112
	himax_mtk_mmi-objs += himax_ic_HX83112.o
endif
