# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/gpu/drm/mediatek/mediatek_v2/ \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/gpu/drm/
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/sensors \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_0flash_mmi_v2 \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_0flash_mmi_v2/include

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

obj-m := focaltech_0flash_mmi_v2.o
focaltech_0flash_mmi_v2-objs += focaltech_core.o
focaltech_0flash_mmi_v2-objs += focaltech_esdcheck.o
focaltech_0flash_mmi_v2-objs += focaltech_ex_fun.o
focaltech_0flash_mmi_v2-objs += focaltech_ex_mode.o
focaltech_0flash_mmi_v2-objs += focaltech_flash.o
focaltech_0flash_mmi_v2-objs += focaltech_gesture.o
focaltech_0flash_mmi_v2-objs += focaltech_point_report_check.o
focaltech_0flash_mmi_v2-objs += focaltech_spi.o

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DFOCALTECH_SENSOR_EN
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_ESD_EN)),)
EXTRA_CFLAGS += -DFOCALTECH_ESD_EN
endif

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DFOCALTECH_CONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_DEBUG_EN)),)
	EXTRA_CFLAGS += -DFOCALTECH_DEBUG_EN
endif

ifneq ($(filter m y,$(CONFIG_FT_FHD_MMI_GET_PANEL)),)
	EXTRA_CFLAGS += -DFT_FHD_MMI_GET_PANEL
endif

ifneq ($(filter m y, $(CONFIG_MTK_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_MTK_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_GTP_LAST_TIME)),)
	EXTRA_CFLAGS += -DCONFIG_GTP_LAST_TIME
endif
