ifeq (,$(KERNEL_DIR_PATH))
    KERNEL_DIR_PATH = $(shell find $(ANDROID_BUILD_TOP)/kernel/ -name "msm-*" -type d | head -1 | grep -i "kernel/msm-*")

    ifeq (,$(KERNEL_DIR_PATH))
        KERNEL_DIR_1_Level := true
        KERNEL_DIR_PATH = $(shell find $(ANDROID_BUILD_TOP)/kernel* -type d -name  "kernel-*" | head -1)
    endif
else
    KERNEL_DIR_1_Level := true
endif

KERNEL_VERSION_NAME = $(shell basename $(KERNEL_DIR_PATH))

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_SX933X_MTK_CHARGER)),)
        EXTRA_CFLAGS += -DCONFIG_SX933X_MTK_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_SX933X_MTK_KERNEL419_CHARGER_TYPE)),)
	EXTRA_CFLAGS += -DCONFIG_SX933X_MTK_KERNEL419_CHARGER_TYPE
endif

ifneq ($(filter m y,$(CONFIG_SX933X_USB_CAL)),)
	EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq ($(filter m y,$(CONFIG_SX933X_FLIP_CAL)),)
	EXTRA_CFLAGS += -DCONFIG_CAPSENSE_FLIP_CAL
endif

ifneq (,$(filter river%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter doha%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter sofia%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter odin%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL \
		-DCONFIG_CAPSENSE_ATTACH_CAL
endif

ifneq (,$(filter olson%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL \
		-DCONFIG_CAPSENSE_FLIP_CAL
endif

ifneq (,$(filter rav%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter burton%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter smith% nairo%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(filter racer%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_HEADSET_STATE
endif

ifneq (,$(filter kiev%,$(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq (,$(KERNEL_DIR_PATH))
        EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel/$(KERNEL_VERSION_NAME)/drivers/base

        ifeq ($(KERNEL_DIR_1_Level), true)
                EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/$(KERNEL_VERSION_NAME)/drivers/base
        endif
else
        EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel/drivers/base
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../sensors/Module.symvers

sx932x_sar-y := sx933x_sar.o

obj-m += sx933x_sar.o
