#obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += chipone-tddi.o
obj-m += chipone_tddi.o

chipone_tddi-objs := cts_driver.o
chipone_tddi-objs += cts_core.o
chipone_tddi-objs += cts_sfctrlv2.o
chipone_tddi-objs += cts_spi_flash.o
chipone_tddi-objs += cts_firmware.o
chipone_tddi-objs += cts_test.o
chipone_tddi-objs += cts_charger_detect.o
chipone_tddi-objs += cts_earjack_detect.o
chipone_tddi-objs += cts_tcs.o
chipone_tddi-objs += cts_platform.o
chipone_tddi-objs += cts_tool.o
chipone_tddi-objs += cts_sysfs.o
chipone_tddi-objs += cts_strerror.o
chipone_tddi-objs += cts_oem.o

