# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_touch_v3_4 \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_touch_v3_4/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_touch_v3_4/focaltech_test

obj-m := focaltech_v3_4.o
focaltech_v3_4-objs += focaltech_core.o
focaltech_v3_4-objs += focaltech_ex_fun.o
focaltech_v3_4-objs += focaltech_ex_mode.o
focaltech_v3_4-objs += focaltech_gesture.o
focaltech_v3_4-objs += focaltech_esdcheck.o
focaltech_v3_4-objs += focaltech_point_report_check.o
focaltech_v3_4-objs += focaltech_flash.o
focaltech_v3_4-objs += focaltech_spi.o
focaltech_v3_4-objs += focaltech_test/focaltech_test.o
focaltech_v3_4-objs += focaltech_test/focaltech_test_ini.o
focaltech_v3_4-objs += focaltech_ts_config.o
focaltech_v3_4-objs += focaltech_debug.o

ifneq ($(filter ft3681,$(CONFIG_INPUT_FOCAL_IC_NAME)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_IC_FT3681
	focaltech_v3_4-objs += focaltech_flash/focaltech_upgrade_ft3681.o
	focaltech_v3_4-objs += focaltech_test/supported_ic/focaltech_test_ft3681.o
endif

ifneq ($(filter ft3683g,$(CONFIG_INPUT_FOCAL_IC_NAME)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_IC_FT3683G
	EXTRA_CFLAGS += -DCONFIG_FTS_NOISE_TEST_P2P
	focaltech_v3_4-objs += focaltech_flash/focaltech_upgrade_ft3683g.o
	focaltech_v3_4-objs += focaltech_test/supported_ic/focaltech_test_ft3683g.o
endif

ifneq ($(filter m y,$(CONFIG_FTS_INPUT_PROTOCOL_V0)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_INPUT_PROTOCOL_V0
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
       KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
       EXTRA_CFLAGS += -DCONFIG_INPUT_TOUCHSCREEN_MMI
       focaltech_v3_4-objs += focaltech_ts_mmi.o
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_V3_MMI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DFOCALTECH_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_V3_MMI_ENABLE_PALM)),)
	EXTRA_CFLAGS += -DFOCALTECH_PALM_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_V3_MMI_PEN_NOTIFIER)),)
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../misc/pen/Module.symvers
	EXTRA_CFLAGS += -DFOCALTECH_PEN_NOTIFIER
endif

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif

ifneq ($(filter m y, $(CONFIG_FTS_NOISE_TEST_P2P)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_NOISE_TEST_P2P
endif

ifneq ($(filter m y, $(CONFIG_FTS_COMPATIBLE_WITH_GKI)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_COMPATIBLE_WITH_GKI
endif

ifneq ($(filter m y, $(CONFIG_FTS_DOUBLE_TAP_CONTROL)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_DOUBLE_TAP_CONTROL
endif

ifneq ($(CONFIG_SUPPORT_FTS_HIRES_X),)
	EXTRA_CFLAGS += -DCONFIG_FTS_HIRES_EN
	EXTRA_CFLAGS += -DCONFIG_FTS_HIRES_X=$(CONFIG_SUPPORT_FTS_HIRES_X)
endif

ifneq ($(filter m y, $(CONFIG_FTS_SUPPORT_HIGH_RESOLUTION)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_SUPPORT_HIGH_RESOLUTION
endif

ifneq ($(filter m y, $(CONFIG_FTS_VDD_GPIO_CONTROL)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_VDD_GPIO_CONTROL
endif

ifneq ($(filter m y,$(CONFIG_FTS_LAST_TIME)),)
    EXTRA_CFLAGS += -DCONFIG_FTS_LAST_TIME
endif

ifneq ($(filter m y,$(CONFIG_FTS_INPUT_ID)),)
    EXTRA_CFLAGS += -DCONFIG_FTS_INPUT_ID
endif

ifneq ($(filter m y,$(CONFIG_FOCALTECH_REPORT_PRESSURE_DISABLE)),)
    EXTRA_CFLAGS += -DCONFIG_FOCALTECH_REPORT_PRESSURE_DISABLE
endif

ifneq ($(findstring _factory,$(TARGET_PRODUCT)),)
USE_TARGET_PRODUCT := $(strip $(subst _factory,, $(TARGET_PRODUCT)))
else
USE_TARGET_PRODUCT := $(TARGET_PRODUCT)
endif

ifneq ($(filter bangkk%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_BANGKK
else ifneq ($(filter avatrn%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_AVATRN
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/../../kernel/msm-$(MODULE_KERNEL_VERSION)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
