DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)


ifeq ($(DRM_PANEL_EVENT_NOTIFICATIONS),true)
    KBUILD_OPTIONS += CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS=y
endif

ifeq ($(ENABLE_GTP_PALM_CANCEL),true)
    KBUILD_OPTIONS += CONFIG_ENABLE_FTS_PALM_CANCEL=y
endif

ifeq ($(ENABLE_FTS_MANUAL_CS),true)
    KBUILD_OPTIONS += CONFIG_ENABLE_FTS_MANUAL_CS=y
endif

ifeq ($(TOUCHCLASS_MMI_FORCE_ENTER_STANDBY),true)
    KBUILD_OPTIONS += CONFIG_TOUCHCLASS_MMI_FORCE_ENTER_STANDBY=y
endif

ifeq ($(TOUCH_HARDWARE_STATUS),true)
       KBUILD_OPTIONS += CONFIG_TOUCH_HARDWARE_STATUS=y
endif

include $(CLEAR_VARS)
LOCAL_MODULE := focaltech_v3_5.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/mmi_info.ko
ifneq ($(findstring touchscreen_mmi.ko,$(BOARD_VENDOR_KERNEL_MODULES)),)
    KBUILD_OPTIONS += CONFIG_INPUT_TOUCHSCREEN_MMI=y
    LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/touchscreen_mmi.ko
endif

KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
include $(DLKM_DIR)/AndroidKernelModule.mk
