# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_touch_v3_5 \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_touch_v3_5/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_touch_v3_5/focaltech_test

obj-m := focaltech_v3_5.o
focaltech_v3_5-objs += focaltech_core.o
focaltech_v3_5-objs += focaltech_ex_fun.o
focaltech_v3_5-objs += focaltech_ex_mode.o
focaltech_v3_5-objs += focaltech_gesture.o
focaltech_v3_5-objs += focaltech_esdcheck.o
focaltech_v3_5-objs += focaltech_point_report_check.o
focaltech_v3_5-objs += focaltech_flash.o
focaltech_v3_5-objs += focaltech_spi_v2.o
focaltech_v3_5-objs += focaltech_debug.o
focaltech_v3_5-objs += focaltech_hp.o
focaltech_v3_5-objs += focaltech_proximity.o

focaltech_v3_5-objs += focaltech_flash/focaltech_upgrade_ft3383.o
focaltech_v3_5-objs += focaltech_test/focaltech_test.o
focaltech_v3_5-objs += focaltech_test/focaltech_test_ini.o
focaltech_v3_5-objs += focaltech_test/supported_ic/focaltech_test_ft3383.o

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
       KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
       EXTRA_CFLAGS += -DCONFIG_INPUT_TOUCHSCREEN_MMI
       focaltech_v3_5-objs += focaltech_ts_mmi.o
endif

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_ENABLE_FTS_PALM_CANCEL)),)
    EXTRA_CFLAGS += -DCONFIG_ENABLE_FTS_PALM_CANCEL
endif

ifneq ($(filter m y,$(CONFIG_ENABLE_FTS_MANUAL_CS)),)
    EXTRA_CFLAGS += -DCONFIG_FTS_MANUAL_CS
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
