# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

obj-m += moto_mm.o

moto_mm-y := mm_main.o mm_sysfs.o mm_info.o mm_lru_shrinker.o

