ifeq ($(ANDROID_BUILD_TOP),)
	ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/sgm415xx_mmi \
		-I$(ANDROID_BUILD_TOP)/kernel-5.15/include \
		-I$(ANDROID_BUILD_TOP)/kernel-5.15/drivers/power/supply

obj-m += sgm415xx_mmi.o
