# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/input/misc/ets_bix_mmi
ets_bix_mmi-y += etxxx_fp.o

obj-m += ets_bix_mmi.o
