DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

MOTO_MUTEX_INHERIT := true
MOTO_RWSEM_INHERIT := true
# MOTO_FUTEX_INHERIT := true

ifeq ($(MOTO_MUTEX_INHERIT), true)
	KBUILD_OPTIONS += CONFIG_MOTO_MUTEX_INHERIT=y
	KERNEL_CFLAGS += CONFIG_MOTO_MUTEX_INHERIT=y
endif

ifeq ($(MOTO_RWSEM_INHERIT), true)
	KBUILD_OPTIONS += CONFIG_MOTO_RWSEM_INHERIT=y
	KERNEL_CFLAGS += CONFIG_MOTO_RWSEM_INHERIT=y
endif

ifeq ($(MOTO_FUTEX_INHERIT), true)
	KBUILD_OPTIONS += CONFIG_MOTO_FUTEX_INHERIT=y
	KERNEL_CFLAGS += CONFIG_MOTO_FUTEX_INHERIT=y
endif

ifeq ($(BOARD_CHIPSET_VENDOR),mtk)
ifneq ($strip($(LINUX_KERNEL_VERSION)),)
	KBUILD_OPTIONS += LINUX_KERNEL_VERSION=$(LINUX_KERNEL_VERSION)
	KERNEL_CFLAGS += LINUX_KERNEL_VERSION=$(LINUX_KERNEL_VERSION)
endif
endif

LOCAL_MODULE := moto_sched.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki

include $(DLKM_DIR)/AndroidKernelModule.mk
