# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel_platform/common
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/moto_sched
obj-m += moto_sched.o

moto_sched-y := msched_main.o msched_sysfs.o msched_common.o

moto_sched-y += locking/locking_main.o
moto_sched-y += locking/mutex.o
moto_sched-$(CONFIG_MOTO_RWSEM_INHERIT) += locking/rwsem.o
moto_sched-$(CONFIG_MOTO_FUTEX_INHERIT) += locking/futex.o