DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := qti_glink_charger.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
LOCAL_ADDITIONAL_DEPENDENCIES := $(KERNEL_MODULES_OUT)/mmi_charger.ko
LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/bm_adsp_ulog.ko

ifeq ($(WIRELESS_CPS4035B),true)
	KERNEL_CFLAGS += CONFIG_WIRELESS_CPS4035B=y
	KBUILD_OPTIONS += CONFIG_WIRELESS_CPS4035B=y
endif

ifeq ($(WIRELESS_CPS4019),true)
	KERNEL_CFLAGS += CONFIG_WIRELESS_CPS4019=y
	KBUILD_OPTIONS += CONFIG_WIRELESS_CPS4019=y
endif

ifeq ($(MSB_DEV),true)
	KERNEL_CFLAGS += CONFIG_MSB_DEV=y
	KBUILD_OPTIONS += CONFIG_MSB_DEV=y
endif

ifeq ($(SWITCHEDCAP_DUMP),true)
	KERNEL_CFLAGS += CONFIG_SWITCHEDCAP_DUMP=y
	KBUILD_OPTIONS += CONFIG_SWITCHEDCAP_DUMP=y
endif

ifeq ($(SKIP_QTI_CHARGER_CONFIRMAION),true)
	KERNEL_CFLAGS += CONFIG_SKIP_QTI_CHARGER_CONFIRMAION=y
	KBUILD_OPTIONS += CONFIG_SKIP_QTI_CHARGER_CONFIRMAION=y
endif

KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
include $(DLKM_DIR)/AndroidKernelModule.mk
