DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_ZRAM=y
#KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_ZRAM_WRITEBACK=y
#KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_ASYNC_COMPRESS=y
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP=y
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_SWAPD=y
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_CORE=y

include $(CLEAR_VARS)
LOCAL_MODULE := moto_swap.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
include $(DLKM_DIR)/AndroidKernelModule.mk

