ifeq ($(shell expr $(KERNELVERSION) \>= 6.6), 1)
ZRAM_SRC = zram-6.6
else ifeq ($(shell expr $(KERNELVERSION) \>= 6.1), 1)
ZRAM_SRC = zram-6.1
else ifeq ($(shell expr $(KERNELVERSION) \>= 5.15), 1)
ZRAM_SRC = zram-5.15
else ifeq ($(shell expr $(KERNELVERSION) \>= 5.10), 1)
ZRAM_SRC = zram-5.10
else ifeq ($(shell expr $(KERNELVERSION) \>= 5.4), 1)
ZRAM_SRC = zram-5.4
endif

ifeq ($(shell expr $(KERNELVERSION) \>= 6.1), 1)
EXTRA_CFLAGS += -Wframe-larger-than=4096
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ZRAM)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_ZRAM
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ZRAM_WRITEBACK)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_ZRAM_WRITEBACK
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_SWAPD)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_SWAPD
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_CORE)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_CORE
endif

moto_swap-objs += $(ZRAM_SRC)/zram_drv.o
moto_swap-objs += hybridswap/hybridswap_main.o
moto_swap-objs += hybridswap/hybridswap_eswap.o

moto_swap-objs += hybridswap/hybridswap_swapd.o
moto_swap-objs += $(ZRAM_SRC)/zcomp.o

obj-m += moto_swap.o
