/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef AW965XX_H_
#define AW965XX_H_
#include "comm/aw_sar_type.h"
#include "linux/sensors.h"
#include "linux/platform_device.h"

#define USE_SENSORS_CLASS

#define AW965XX_CHANNEL_NUM_MAX				(8)
#define AW965XX_VALID_TH				(2)
#define AW965XX_DATA_PROCESS_FACTOR			(1024)
#define AW9620X_SAR_VCC_MIN_UV				(1700000)
#define AW9620X_SAR_VCC_MAX_UV				(3600000)
#define AW965XX_SRAM_UPDATE_ONE_PACK_SIZE		(256)
#define AW965XX_SRAM_UPDATE_ONE_UINT_SIZE		(4)
#define AW965XX_SRAM_START_ADDR				(0x2000)
#define AW965XX_SRAM_END_ADDR				(0x4ff4 + 4)
#define AW965XX_SRAM_SIZE				(AW965XX_SRAM_END_ADDR - AW965XX_SRAM_START_ADDR)
#define AW965XX_SRAM_DEFAULT_VAL			(0xffffffff)

#define AW965XX_TRIGGER_FAR				(0)
#define REG_SA_RSTNALL									(0xFF0C)
#define AW965XX_SOFT_RST_EN								(0)
#define AW965XX_CHIP_INIT_MAX_TIME_MS					(30)
#define AW965XX_STEP_LEN_UNSIGNED_CAP_ROUGH_ADJ			(1300)
#define AW965XX_STEP_LEN_UNSIGNED_CAP_FINE_ADJ			(25)
#define AW965XX_STEP_LEN_UNSIGNED_CAP_ENLARGE			(1000)

#define AW965XX_CPU_OSC_CTRL_MASK			(1)

#define AW965XX_ABNORMAL_IRQ_HANDLE_DELAY_MS		(30000)

#define HALF_WORD					(0xf)
#define ONE_WORD					(0xff)
#define AW_BIT8						(8)
#define AW_BIT16					(16)
#define AW96503						("AW96503")
#define AW96505						("AW96505")
#define AW96506						("AW96506")
#define AW96508						("AW96508")
#define AW96510						("AW96510")

enum aw965xx_cap_mode {
	AW965XX_UNSIGNED_CAP = 0,
	AW965XX_SIGNED_CAP = 4,
	AW965XX_MUTUAL_CAP = 5,
};

enum aw965xx_approach_state {
	AW965XX_FAR_AWAY = 0,
	AW965XX_APPROACH = 1,
};

enum aw965xx_cs_2_irq {
	AW965XX_CS3_IRQ = 3,
	AW965XX_CS4_IRQ = 4,
};

enum aw965xx_operation_mode {
	AW965XX_ACTIVE_MODE = 0x01,
	AW965XX_SLEEP_MODE = 0x02,
	AW965XX_DEEPSLEEP_MODE = 0x03,
};

enum aw965xx_chip_id {
	AW96503_CHIP_ID = 0xA9630340,
	AW96505_CHIP_ID = 0xA9630520,
	AW96508_CHIP_ID = 0xA9630810,
	AW96510_CHIP_ID = 0xA9631010,
};

enum aw965xx_boot_mode {
	AW965XX_ROM_MODE = 0,
	AW965XX_RAM_MODE = 1,
};

struct aw965xx {
	uint32_t irq_mux;
	uint32_t start_mode;
	uint32_t ref_ch_en[AW965XX_CHANNEL_NUM_MAX];
	void *p_aw_sar;
	struct class capsense_class;
	struct device *capsense_dev;
	bool sar_cali_flag;
	uint32_t enabled_channels;

	uint32_t last_blfilta[AW965XX_CHANNEL_NUM_MAX];
	uint32_t last_irq_en;

#ifdef USE_SENSORS_CLASS
	struct sensors_classdev sensors_capsensor_chs[AW965XX_CHANNEL_NUM_MAX];
	struct platform_device *capsense_pdev[AW965XX_CHANNEL_NUM_MAX];
#endif
};


#define AFE_BASE_ADDR					(0x0000)
#define DSP_BASE_ADDR					(0x0000)
#define STAT_BASE_ADDR					(0x0000)
#define DATA_BASE_ADDR					(0x0000)
#define DSPEX_BASE_ADDR					(0x0000)
#define SFR_BASE_ADDR					(0x0000)
/* registers list */
//A2431A_AW96508QNR_0707_AFE MAP
#define REG_SCANCTRL0					((0x0000) + AFE_BASE_ADDR)
#define REG_SCANCTRL1					((0x0004) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG0_CH0			((0x0008) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG1_CH0			((0x000C) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG2_CH0			((0x0010) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG0_CH1			((0x0014) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG1_CH1			((0x0018) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG2_CH1			((0x001C) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG0_CH2			((0x0020) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG1_CH2			((0x0024) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG2_CH2			((0x0028) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG0_CH3			((0x002C) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG1_CH3			((0x0030) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG2_CH3			((0x0034) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG0_CH4			((0x0038) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG1_CH4			((0x003C) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG2_CH4			((0x0040) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG0_CH5			((0x0044) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG1_CH5			((0x0048) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG2_CH5			((0x004C) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG0_CH6			((0x0050) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG1_CH6			((0x0054) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG2_CH6			((0x0058) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG0_CH7			((0x005C) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG1_CH7			((0x0060) + AFE_BASE_ADDR)
#define REG_AFE_SOFT_CFG2_CH7			((0x0064) + AFE_BASE_ADDR)

/* registers list */
//A2431A_AW96508QNR_0707_DSP MAP
#define REG_FILT_CTRL0_CH0				((0x0068) + DSP_BASE_ADDR)
#define REG_FILT_CTRL1_CH0				((0x006C) + DSP_BASE_ADDR)
#define REG_FILT_CTRL2_CH0				((0x0070) + DSP_BASE_ADDR)
#define REG_FILT_CTRL3_CH0				((0x0074) + DSP_BASE_ADDR)
#define REG_BL_FILT0_CH0				((0x0078) + DSP_BASE_ADDR)
#define REG_BL_FILT1_CH0				((0x007C) + DSP_BASE_ADDR)
#define REG_BL_FILT2_CH0				((0x0080) + DSP_BASE_ADDR)
#define REG_BL_FILT3_CH0				((0x0084) + DSP_BASE_ADDR)
#define REG_BL_FILT4_CH0				((0x0088) + DSP_BASE_ADDR)
#define REG_BL_FILT5_CH0				((0x008C) + DSP_BASE_ADDR)
#define REG_BL_FILT6_CH0				((0x0090) + DSP_BASE_ADDR)
#define REG_PROX_CTRL0_CH0				((0x0094) + DSP_BASE_ADDR)
#define REG_PROX_CTRL1_CH0				((0x0098) + DSP_BASE_ADDR)
#define REG_PROX_CTRL2_CH0				((0x009C) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL0_CH0		((0x00A0) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL1_CH0		((0x00A4) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL2_CH0		((0x00A8) + DSP_BASE_ADDR)
#define REG_RAW_CTRL0_CH0				((0x00AC) + DSP_BASE_ADDR)
#define REG_RAW_CTRL1_CH0				((0x00B0) + DSP_BASE_ADDR)
#define REG_FILT_CTRL0_CH1				((0x00B4) + DSP_BASE_ADDR)
#define REG_FILT_CTRL1_CH1				((0x00B8) + DSP_BASE_ADDR)
#define REG_FILT_CTRL2_CH1				((0x00BC) + DSP_BASE_ADDR)
#define REG_FILT_CTRL3_CH1				((0x00C0) + DSP_BASE_ADDR)
#define REG_BL_FILT0_CH1				((0x00C4) + DSP_BASE_ADDR)
#define REG_BL_FILT1_CH1				((0x00C8) + DSP_BASE_ADDR)
#define REG_BL_FILT2_CH1				((0x00CC) + DSP_BASE_ADDR)
#define REG_BL_FILT3_CH1				((0x00D0) + DSP_BASE_ADDR)
#define REG_BL_FILT4_CH1				((0x00D4) + DSP_BASE_ADDR)
#define REG_BL_FILT5_CH1				((0x00D8) + DSP_BASE_ADDR)
#define REG_BL_FILT6_CH1				((0x00DC) + DSP_BASE_ADDR)
#define REG_PROX_CTRL0_CH1				((0x00E0) + DSP_BASE_ADDR)
#define REG_PROX_CTRL1_CH1				((0x00E4) + DSP_BASE_ADDR)
#define REG_PROX_CTRL2_CH1				((0x00E8) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL0_CH1		((0x00EC) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL1_CH1		((0x00F0) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL2_CH1		((0x00F4) + DSP_BASE_ADDR)
#define REG_RAW_CTRL0_CH1				((0x00F8) + DSP_BASE_ADDR)
#define REG_RAW_CTRL1_CH1				((0x00FC) + DSP_BASE_ADDR)
#define REG_FILT_CTRL0_CH2				((0x0100) + DSP_BASE_ADDR)
#define REG_FILT_CTRL1_CH2				((0x0104) + DSP_BASE_ADDR)
#define REG_FILT_CTRL2_CH2				((0x0108) + DSP_BASE_ADDR)
#define REG_FILT_CTRL3_CH2				((0x010C) + DSP_BASE_ADDR)
#define REG_BL_FILT0_CH2				((0x0110) + DSP_BASE_ADDR)
#define REG_BL_FILT1_CH2				((0x0114) + DSP_BASE_ADDR)
#define REG_BL_FILT2_CH2				((0x0118) + DSP_BASE_ADDR)
#define REG_BL_FILT3_CH2				((0x011C) + DSP_BASE_ADDR)
#define REG_BL_FILT4_CH2				((0x0120) + DSP_BASE_ADDR)
#define REG_BL_FILT5_CH2				((0x0124) + DSP_BASE_ADDR)
#define REG_BL_FILT6_CH2				((0x0128) + DSP_BASE_ADDR)
#define REG_PROX_CTRL0_CH2				((0x012C) + DSP_BASE_ADDR)
#define REG_PROX_CTRL1_CH2				((0x0130) + DSP_BASE_ADDR)
#define REG_PROX_CTRL2_CH2				((0x0134) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL0_CH2		((0x0138) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL1_CH2		((0x013C) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL2_CH2		((0x0140) + DSP_BASE_ADDR)
#define REG_RAW_CTRL0_CH2				((0x0144) + DSP_BASE_ADDR)
#define REG_RAW_CTRL1_CH2				((0x0148) + DSP_BASE_ADDR)
#define REG_FILT_CTRL0_CH3				((0x014C) + DSP_BASE_ADDR)
#define REG_FILT_CTRL1_CH3				((0x0150) + DSP_BASE_ADDR)
#define REG_FILT_CTRL2_CH3				((0x0154) + DSP_BASE_ADDR)
#define REG_FILT_CTRL3_CH3				((0x0158) + DSP_BASE_ADDR)
#define REG_BL_FILT0_CH3				((0x015C) + DSP_BASE_ADDR)
#define REG_BL_FILT1_CH3				((0x0160) + DSP_BASE_ADDR)
#define REG_BL_FILT2_CH3				((0x0164) + DSP_BASE_ADDR)
#define REG_BL_FILT3_CH3				((0x0168) + DSP_BASE_ADDR)
#define REG_BL_FILT4_CH3				((0x016C) + DSP_BASE_ADDR)
#define REG_BL_FILT5_CH3				((0x0170) + DSP_BASE_ADDR)
#define REG_BL_FILT6_CH3				((0x0174) + DSP_BASE_ADDR)
#define REG_PROX_CTRL0_CH3				((0x0178) + DSP_BASE_ADDR)
#define REG_PROX_CTRL1_CH3				((0x017C) + DSP_BASE_ADDR)
#define REG_PROX_CTRL2_CH3				((0x0180) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL0_CH3		((0x0184) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL1_CH3		((0x0188) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL2_CH3		((0x018C) + DSP_BASE_ADDR)
#define REG_RAW_CTRL0_CH3				((0x0190) + DSP_BASE_ADDR)
#define REG_RAW_CTRL1_CH3				((0x0194) + DSP_BASE_ADDR)
#define REG_FILT_CTRL0_CH4				((0x0198) + DSP_BASE_ADDR)
#define REG_FILT_CTRL1_CH4				((0x019C) + DSP_BASE_ADDR)
#define REG_FILT_CTRL2_CH4				((0x01A0) + DSP_BASE_ADDR)
#define REG_FILT_CTRL3_CH4				((0x01A4) + DSP_BASE_ADDR)
#define REG_BL_FILT0_CH4				((0x01A8) + DSP_BASE_ADDR)
#define REG_BL_FILT1_CH4				((0x01AC) + DSP_BASE_ADDR)
#define REG_BL_FILT2_CH4				((0x01B0) + DSP_BASE_ADDR)
#define REG_BL_FILT3_CH4				((0x01B4) + DSP_BASE_ADDR)
#define REG_BL_FILT4_CH4				((0x01B8) + DSP_BASE_ADDR)
#define REG_BL_FILT5_CH4				((0x01BC) + DSP_BASE_ADDR)
#define REG_BL_FILT6_CH4				((0x01C0) + DSP_BASE_ADDR)
#define REG_PROX_CTRL0_CH4				((0x01C4) + DSP_BASE_ADDR)
#define REG_PROX_CTRL1_CH4				((0x01C8) + DSP_BASE_ADDR)
#define REG_PROX_CTRL2_CH4				((0x01CC) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL0_CH4		((0x01D0) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL1_CH4		((0x01D4) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL2_CH4		((0x01D8) + DSP_BASE_ADDR)
#define REG_RAW_CTRL0_CH4				((0x01DC) + DSP_BASE_ADDR)
#define REG_RAW_CTRL1_CH4				((0x01E0) + DSP_BASE_ADDR)
#define REG_FILT_CTRL0_CH5				((0x01E4) + DSP_BASE_ADDR)
#define REG_FILT_CTRL1_CH5				((0x01E8) + DSP_BASE_ADDR)
#define REG_FILT_CTRL2_CH5				((0x01EC) + DSP_BASE_ADDR)
#define REG_FILT_CTRL3_CH5				((0x01F0) + DSP_BASE_ADDR)
#define REG_BL_FILT0_CH5				((0x01F4) + DSP_BASE_ADDR)
#define REG_BL_FILT1_CH5				((0x01F8) + DSP_BASE_ADDR)
#define REG_BL_FILT2_CH5				((0x01FC) + DSP_BASE_ADDR)
#define REG_BL_FILT3_CH5				((0x0200) + DSP_BASE_ADDR)
#define REG_BL_FILT4_CH5				((0x0204) + DSP_BASE_ADDR)
#define REG_BL_FILT5_CH5				((0x0208) + DSP_BASE_ADDR)
#define REG_BL_FILT6_CH5				((0x020C) + DSP_BASE_ADDR)
#define REG_PROX_CTRL0_CH5				((0x0210) + DSP_BASE_ADDR)
#define REG_PROX_CTRL1_CH5				((0x0214) + DSP_BASE_ADDR)
#define REG_PROX_CTRL2_CH5				((0x0218) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL0_CH5		((0x021C) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL1_CH5		((0x0220) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL2_CH5		((0x0224) + DSP_BASE_ADDR)
#define REG_RAW_CTRL0_CH5				((0x0228) + DSP_BASE_ADDR)
#define REG_RAW_CTRL1_CH5				((0x022C) + DSP_BASE_ADDR)
#define REG_FILT_CTRL0_CH6				((0x0230) + DSP_BASE_ADDR)
#define REG_FILT_CTRL1_CH6				((0x0234) + DSP_BASE_ADDR)
#define REG_FILT_CTRL2_CH6				((0x0238) + DSP_BASE_ADDR)
#define REG_FILT_CTRL3_CH6				((0x023C) + DSP_BASE_ADDR)
#define REG_BL_FILT0_CH6				((0x0240) + DSP_BASE_ADDR)
#define REG_BL_FILT1_CH6				((0x0244) + DSP_BASE_ADDR)
#define REG_BL_FILT2_CH6				((0x0248) + DSP_BASE_ADDR)
#define REG_BL_FILT3_CH6				((0x024C) + DSP_BASE_ADDR)
#define REG_BL_FILT4_CH6				((0x0250) + DSP_BASE_ADDR)
#define REG_BL_FILT5_CH6				((0x0254) + DSP_BASE_ADDR)
#define REG_BL_FILT6_CH6				((0x0258) + DSP_BASE_ADDR)
#define REG_PROX_CTRL0_CH6				((0x025C) + DSP_BASE_ADDR)
#define REG_PROX_CTRL1_CH6				((0x0260) + DSP_BASE_ADDR)
#define REG_PROX_CTRL2_CH6				((0x0264) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL0_CH6		((0x0268) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL1_CH6		((0x026C) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL2_CH6		((0x0270) + DSP_BASE_ADDR)
#define REG_RAW_CTRL0_CH6				((0x0274) + DSP_BASE_ADDR)
#define REG_RAW_CTRL1_CH6				((0x0278) + DSP_BASE_ADDR)
#define REG_FILT_CTRL0_CH7				((0x027C) + DSP_BASE_ADDR)
#define REG_FILT_CTRL1_CH7				((0x0280) + DSP_BASE_ADDR)
#define REG_FILT_CTRL2_CH7				((0x0284) + DSP_BASE_ADDR)
#define REG_FILT_CTRL3_CH7				((0x0288) + DSP_BASE_ADDR)
#define REG_BL_FILT0_CH7				((0x028C) + DSP_BASE_ADDR)
#define REG_BL_FILT1_CH7				((0x0290) + DSP_BASE_ADDR)
#define REG_BL_FILT2_CH7				((0x0294) + DSP_BASE_ADDR)
#define REG_BL_FILT3_CH7				((0x0298) + DSP_BASE_ADDR)
#define REG_BL_FILT4_CH7				((0x029C) + DSP_BASE_ADDR)
#define REG_BL_FILT5_CH7				((0x02A0) + DSP_BASE_ADDR)
#define REG_BL_FILT6_CH7				((0x02A4) + DSP_BASE_ADDR)
#define REG_PROX_CTRL0_CH7				((0x02A8) + DSP_BASE_ADDR)
#define REG_PROX_CTRL1_CH7				((0x02AC) + DSP_BASE_ADDR)
#define REG_PROX_CTRL2_CH7				((0x02B0) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL0_CH7		((0x02B4) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL1_CH7		((0x02B8) + DSP_BASE_ADDR)
#define REG_FLOAT_COMP_CTRL2_CH7		((0x02BC) + DSP_BASE_ADDR)
#define REG_RAW_CTRL0_CH7				((0x02C0) + DSP_BASE_ADDR)
#define REG_RAW_CTRL1_CH7				((0x02C4) + DSP_BASE_ADDR)
#define REG_REF_CTRL_ENGINE0			((0x02C8) + DSP_BASE_ADDR)
#define REG_REF_CTRL_ENGINE1			((0x02CC) + DSP_BASE_ADDR)
#define REG_REF_CTRL_ENGINE2			((0x02D0) + DSP_BASE_ADDR)
#define REG_REF_CTRL_ENGINE3			((0x02D4) + DSP_BASE_ADDR)

/* registers list */
//A2431A_AW96508QNR_0707_STAT MAP
#define REG_FIREWARE_VERSION_INFO		((0x02D8) + STAT_BASE_ADDR)
#define REG_FIREWARE_INTERNAL_INFO		((0x02DC) + STAT_BASE_ADDR)
#define REG_PST							((0x02E0) + STAT_BASE_ADDR)
#define REG_STAT0						((0x02E4) + STAT_BASE_ADDR)
#define REG_STAT1						((0x02E8) + STAT_BASE_ADDR)
#define REG_PROX_INT_EN					((0x02EC) + STAT_BASE_ADDR)
#define REG_EFUSE_DATA					((0x05A0) + STAT_BASE_ADDR)
#define REG_CS_STATUS					((0x05A4) + STAT_BASE_ADDR)

/* registers list */
//A2431A_AW96508QNR_0707_DATA MAP
#define REG_VALID_CH0					((0x02F0) + DATA_BASE_ADDR)
#define REG_VALID_CH1					((0x02F4) + DATA_BASE_ADDR)
#define REG_VALID_CH2					((0x02F8) + DATA_BASE_ADDR)
#define REG_VALID_CH3					((0x02FC) + DATA_BASE_ADDR)
#define REG_VALID_CH4					((0x0300) + DATA_BASE_ADDR)
#define REG_VALID_CH5					((0x0304) + DATA_BASE_ADDR)
#define REG_VALID_CH6					((0x0308) + DATA_BASE_ADDR)
#define REG_VALID_CH7					((0x030C) + DATA_BASE_ADDR)
#define REG_BASELINE_CH0				((0x0310) + DATA_BASE_ADDR)
#define REG_BASELINE_CH1				((0x0314) + DATA_BASE_ADDR)
#define REG_BASELINE_CH2				((0x0318) + DATA_BASE_ADDR)
#define REG_BASELINE_CH3				((0x031C) + DATA_BASE_ADDR)
#define REG_BASELINE_CH4				((0x0320) + DATA_BASE_ADDR)
#define REG_BASELINE_CH5				((0x0324) + DATA_BASE_ADDR)
#define REG_BASELINE_CH6				((0x0328) + DATA_BASE_ADDR)
#define REG_BASELINE_CH7				((0x032C) + DATA_BASE_ADDR)
#define REG_PREDIFF_CH0					((0x0330) + DATA_BASE_ADDR)
#define REG_PREDIFF_CH1					((0x0334) + DATA_BASE_ADDR)
#define REG_PREDIFF_CH2					((0x0338) + DATA_BASE_ADDR)
#define REG_PREDIFF_CH3					((0x033C) + DATA_BASE_ADDR)
#define REG_PREDIFF_CH4					((0x0340) + DATA_BASE_ADDR)
#define REG_PREDIFF_CH5					((0x0344) + DATA_BASE_ADDR)
#define REG_PREDIFF_CH6					((0x0348) + DATA_BASE_ADDR)
#define REG_PREDIFF_CH7					((0x034C) + DATA_BASE_ADDR)
#define REG_DIFF_CH0					((0x0350) + DATA_BASE_ADDR)
#define REG_DIFF_CH1					((0x0354) + DATA_BASE_ADDR)
#define REG_DIFF_CH2					((0x0358) + DATA_BASE_ADDR)
#define REG_DIFF_CH3					((0x035C) + DATA_BASE_ADDR)
#define REG_DIFF_CH4					((0x0360) + DATA_BASE_ADDR)
#define REG_DIFF_CH5					((0x0364) + DATA_BASE_ADDR)
#define REG_DIFF_CH6					((0x0368) + DATA_BASE_ADDR)
#define REG_DIFF_CH7					((0x036C) + DATA_BASE_ADDR)
#define REG_ADC_MIN_CH0					((0x0370) + DATA_BASE_ADDR)
#define REG_ADC_MIN_CH1					((0x0374) + DATA_BASE_ADDR)
#define REG_ADC_MIN_CH2					((0x0378) + DATA_BASE_ADDR)
#define REG_ADC_MIN_CH3					((0x037C) + DATA_BASE_ADDR)
#define REG_ADC_MIN_CH4					((0x0380) + DATA_BASE_ADDR)
#define REG_ADC_MIN_CH5					((0x0384) + DATA_BASE_ADDR)
#define REG_ADC_MIN_CH6					((0x0388) + DATA_BASE_ADDR)
#define REG_ADC_MIN_CH7					((0x038C) + DATA_BASE_ADDR)
#define REG_ADC_MAX_CH0					((0x0390) + DATA_BASE_ADDR)
#define REG_ADC_MAX_CH1					((0x0394) + DATA_BASE_ADDR)
#define REG_ADC_MAX_CH2					((0x0398) + DATA_BASE_ADDR)
#define REG_ADC_MAX_CH3					((0x039C) + DATA_BASE_ADDR)
#define REG_ADC_MAX_CH4					((0x03A0) + DATA_BASE_ADDR)
#define REG_ADC_MAX_CH5					((0x03A4) + DATA_BASE_ADDR)
#define REG_ADC_MAX_CH6					((0x03A8) + DATA_BASE_ADDR)
#define REG_ADC_MAX_CH7					((0x03AC) + DATA_BASE_ADDR)
#define REG_ADC_AVE_CH0					((0x03B0) + DATA_BASE_ADDR)
#define REG_ADC_AVE_CH1					((0x03B4) + DATA_BASE_ADDR)
#define REG_ADC_AVE_CH2					((0x03B8) + DATA_BASE_ADDR)
#define REG_ADC_AVE_CH3					((0x03BC) + DATA_BASE_ADDR)
#define REG_ADC_AVE_CH4					((0x03C0) + DATA_BASE_ADDR)
#define REG_ADC_AVE_CH5					((0x03C4) + DATA_BASE_ADDR)
#define REG_ADC_AVE_CH6					((0x03C8) + DATA_BASE_ADDR)
#define REG_ADC_AVE_CH7					((0x03CC) + DATA_BASE_ADDR)
#define REG_RAW_CH0						((0x03D0) + DATA_BASE_ADDR)
#define REG_RAW_CH1						((0x03D4) + DATA_BASE_ADDR)
#define REG_RAW_CH2						((0x03D8) + DATA_BASE_ADDR)
#define REG_RAW_CH3						((0x03DC) + DATA_BASE_ADDR)
#define REG_RAW_CH4						((0x03E0) + DATA_BASE_ADDR)
#define REG_RAW_CH5						((0x03E4) + DATA_BASE_ADDR)
#define REG_RAW_CH6						((0x03E8) + DATA_BASE_ADDR)
#define REG_RAW_CH7						((0x03EC) + DATA_BASE_ADDR)
#define REG_LPF_CH0						((0x03F0) + DATA_BASE_ADDR)
#define REG_LPF_CH1						((0x03F4) + DATA_BASE_ADDR)
#define REG_LPF_CH2						((0x03F8) + DATA_BASE_ADDR)
#define REG_LPF_CH3						((0x03FC) + DATA_BASE_ADDR)
#define REG_LPF_CH4						((0x0400) + DATA_BASE_ADDR)
#define REG_LPF_CH5						((0x0404) + DATA_BASE_ADDR)
#define REG_LPF_CH6						((0x0408) + DATA_BASE_ADDR)
#define REG_LPF_CH7						((0x040C) + DATA_BASE_ADDR)
#define REG_SAT_CH0						((0x0410) + DATA_BASE_ADDR)
#define REG_SAT_CH1						((0x0414) + DATA_BASE_ADDR)
#define REG_SAT_CH2						((0x0418) + DATA_BASE_ADDR)
#define REG_SAT_CH3						((0x041C) + DATA_BASE_ADDR)
#define REG_SAT_CH4						((0x0420) + DATA_BASE_ADDR)
#define REG_SAT_CH5						((0x0424) + DATA_BASE_ADDR)
#define REG_SAT_CH6						((0x0428) + DATA_BASE_ADDR)
#define REG_SAT_CH7						((0x042C) + DATA_BASE_ADDR)
#define REG_VALID_LAST_CH0				((0x0430) + DATA_BASE_ADDR)
#define REG_VALID_LAST_CH1				((0x0434) + DATA_BASE_ADDR)
#define REG_VALID_LAST_CH2				((0x0438) + DATA_BASE_ADDR)
#define REG_VALID_LAST_CH3				((0x043C) + DATA_BASE_ADDR)
#define REG_VALID_LAST_CH4				((0x0440) + DATA_BASE_ADDR)
#define REG_VALID_LAST_CH5				((0x0444) + DATA_BASE_ADDR)
#define REG_VALID_LAST_CH6				((0x0448) + DATA_BASE_ADDR)
#define REG_VALID_LAST_CH7				((0x044C) + DATA_BASE_ADDR)
#define REG_DELTAVALID_CH0				((0x0450) + DATA_BASE_ADDR)
#define REG_DELTAVALID_CH1				((0x0454) + DATA_BASE_ADDR)
#define REG_DELTAVALID_CH2				((0x0458) + DATA_BASE_ADDR)
#define REG_DELTAVALID_CH3				((0x045C) + DATA_BASE_ADDR)
#define REG_DELTAVALID_CH4				((0x0460) + DATA_BASE_ADDR)
#define REG_DELTAVALID_CH5				((0x0464) + DATA_BASE_ADDR)
#define REG_DELTAVALID_CH6				((0x0468) + DATA_BASE_ADDR)
#define REG_DELTAVALID_CH7				((0x046C) + DATA_BASE_ADDR)
#define REG_COMP_LAST_AVG_CH0			((0x0470) + DATA_BASE_ADDR)
#define REG_COMP_LAST_AVG_CH1			((0x0474) + DATA_BASE_ADDR)
#define REG_COMP_LAST_AVG_CH2			((0x0478) + DATA_BASE_ADDR)
#define REG_COMP_LAST_AVG_CH3			((0x047C) + DATA_BASE_ADDR)
#define REG_COMP_LAST_AVG_CH4			((0x0480) + DATA_BASE_ADDR)
#define REG_COMP_LAST_AVG_CH5			((0x0484) + DATA_BASE_ADDR)
#define REG_COMP_LAST_AVG_CH6			((0x0488) + DATA_BASE_ADDR)
#define REG_COMP_LAST_AVG_CH7			((0x048C) + DATA_BASE_ADDR)
#define REG_CS_ERR_DATA0				((0x0490) + DATA_BASE_ADDR)
#define REG_CS_ERR_DATA1				((0x0494) + DATA_BASE_ADDR)
#define REG_CS_ERR_DATA2				((0x0498) + DATA_BASE_ADDR)
#define REG_CS_ERR_DATA3				((0x049C) + DATA_BASE_ADDR)
#define REG_AFE0_CH0					((0x04A0) + DATA_BASE_ADDR)
#define REG_AFE1_CH0					((0x04A4) + DATA_BASE_ADDR)
#define REG_AFE2_CH0					((0x04A8) + DATA_BASE_ADDR)
#define REG_AFE3_CH0					((0x04AC) + DATA_BASE_ADDR)
#define REG_AFE4_CH0					((0x04B0) + DATA_BASE_ADDR)
#define REG_AFE5_CH0					((0x04B4) + DATA_BASE_ADDR)
#define REG_AFE6_CH0					((0x04B8) + DATA_BASE_ADDR)
#define REG_AFE7_CH0					((0x04BC) + DATA_BASE_ADDR)
#define REG_AFE0_CH1					((0x04C0) + DATA_BASE_ADDR)
#define REG_AFE1_CH1					((0x04C4) + DATA_BASE_ADDR)
#define REG_AFE2_CH1					((0x04C8) + DATA_BASE_ADDR)
#define REG_AFE3_CH1					((0x04CC) + DATA_BASE_ADDR)
#define REG_AFE4_CH1					((0x04D0) + DATA_BASE_ADDR)
#define REG_AFE5_CH1					((0x04D4) + DATA_BASE_ADDR)
#define REG_AFE6_CH1					((0x04D8) + DATA_BASE_ADDR)
#define REG_AFE7_CH1					((0x04DC) + DATA_BASE_ADDR)
#define REG_AFE0_CH2					((0x04E0) + DATA_BASE_ADDR)
#define REG_AFE1_CH2					((0x04E4) + DATA_BASE_ADDR)
#define REG_AFE2_CH2					((0x04E8) + DATA_BASE_ADDR)
#define REG_AFE3_CH2					((0x04EC) + DATA_BASE_ADDR)
#define REG_AFE4_CH2					((0x04F0) + DATA_BASE_ADDR)
#define REG_AFE5_CH2					((0x04F4) + DATA_BASE_ADDR)
#define REG_AFE6_CH2					((0x04F8) + DATA_BASE_ADDR)
#define REG_AFE7_CH2					((0x04FC) + DATA_BASE_ADDR)
#define REG_AFE0_CH3					((0x0500) + DATA_BASE_ADDR)
#define REG_AFE1_CH3					((0x0504) + DATA_BASE_ADDR)
#define REG_AFE2_CH3					((0x0508) + DATA_BASE_ADDR)
#define REG_AFE3_CH3					((0x050C) + DATA_BASE_ADDR)
#define REG_AFE4_CH3					((0x0510) + DATA_BASE_ADDR)
#define REG_AFE5_CH3					((0x0514) + DATA_BASE_ADDR)
#define REG_AFE6_CH3					((0x0518) + DATA_BASE_ADDR)
#define REG_AFE7_CH3					((0x051C) + DATA_BASE_ADDR)
#define REG_AFE0_CH4					((0x0520) + DATA_BASE_ADDR)
#define REG_AFE1_CH4					((0x0524) + DATA_BASE_ADDR)
#define REG_AFE2_CH4					((0x0528) + DATA_BASE_ADDR)
#define REG_AFE3_CH4					((0x052C) + DATA_BASE_ADDR)
#define REG_AFE4_CH4					((0x0530) + DATA_BASE_ADDR)
#define REG_AFE5_CH4					((0x0534) + DATA_BASE_ADDR)
#define REG_AFE6_CH4					((0x0538) + DATA_BASE_ADDR)
#define REG_AFE7_CH4					((0x053C) + DATA_BASE_ADDR)
#define REG_AFE0_CH5					((0x0540) + DATA_BASE_ADDR)
#define REG_AFE1_CH5					((0x0544) + DATA_BASE_ADDR)
#define REG_AFE2_CH5					((0x0548) + DATA_BASE_ADDR)
#define REG_AFE3_CH5					((0x054C) + DATA_BASE_ADDR)
#define REG_AFE4_CH5					((0x0550) + DATA_BASE_ADDR)
#define REG_AFE5_CH5					((0x0554) + DATA_BASE_ADDR)
#define REG_AFE6_CH5					((0x0558) + DATA_BASE_ADDR)
#define REG_AFE7_CH5					((0x055C) + DATA_BASE_ADDR)
#define REG_AFE0_CH6					((0x0560) + DATA_BASE_ADDR)
#define REG_AFE1_CH6					((0x0564) + DATA_BASE_ADDR)
#define REG_AFE2_CH6					((0x0568) + DATA_BASE_ADDR)
#define REG_AFE3_CH6					((0x056C) + DATA_BASE_ADDR)
#define REG_AFE4_CH6					((0x0570) + DATA_BASE_ADDR)
#define REG_AFE5_CH6					((0x0574) + DATA_BASE_ADDR)
#define REG_AFE6_CH6					((0x0578) + DATA_BASE_ADDR)
#define REG_AFE7_CH6					((0x057C) + DATA_BASE_ADDR)
#define REG_AFE0_CH7					((0x0580) + DATA_BASE_ADDR)
#define REG_AFE1_CH7					((0x0584) + DATA_BASE_ADDR)
#define REG_AFE2_CH7					((0x0588) + DATA_BASE_ADDR)
#define REG_AFE3_CH7					((0x058C) + DATA_BASE_ADDR)
#define REG_AFE4_CH7					((0x0590) + DATA_BASE_ADDR)
#define REG_AFE5_CH7					((0x0594) + DATA_BASE_ADDR)
#define REG_AFE6_CH7					((0x0598) + DATA_BASE_ADDR)
#define REG_AFE7_CH7					((0x059C) + DATA_BASE_ADDR)
#define REG_BASELINE_MULTI_CH0			((0x06A8) + DATA_BASE_ADDR)
#define REG_BASELINE_MULTI_CH1			((0x06AC) + DATA_BASE_ADDR)
#define REG_BASELINE_MULTI_CH2			((0x06B0) + DATA_BASE_ADDR)
#define REG_BASELINE_MULTI_CH3			((0x06B4) + DATA_BASE_ADDR)
#define REG_BASELINE_MULTI_CH4			((0x06B8) + DATA_BASE_ADDR)
#define REG_BASELINE_MULTI_CH5			((0x06BC) + DATA_BASE_ADDR)
#define REG_BASELINE_MULTI_CH6			((0x06C0) + DATA_BASE_ADDR)
#define REG_BASELINE_MULTI_CH7			((0x06C4) + DATA_BASE_ADDR)

/* registers list */
//A2431A_AW96508QNR_0707_DSPEX MAP
#define REG_SSR_CTRL0_CH0				((0x06C8) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL1_CH0				((0x06CC) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL0_CH1				((0x06D0) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL1_CH1				((0x06D4) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL0_CH2				((0x06D8) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL1_CH2				((0x06DC) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL0_CH3				((0x06E0) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL1_CH3				((0x06E4) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL0_CH4				((0x06E8) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL1_CH4				((0x06EC) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL0_CH5				((0x06F0) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL1_CH5				((0x06F4) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL0_CH6				((0x06F8) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL1_CH6				((0x06FC) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL0_CH7				((0x0700) + DSPEX_BASE_ADDR)
#define REG_SSR_CTRL1_CH7				((0x0704) + DSPEX_BASE_ADDR)

/* registers list */
//A2431A_AW96508QNR_0707_SFR MAP
#define REG_CMD							((0xF008) + SFR_BASE_ADDR)
#define REG_IRQSRC						((0xF080) + SFR_BASE_ADDR)
#define REG_IRQEN						((0xF084) + SFR_BASE_ADDR)
#define REG_I2CTIMEOUTEN				((0xF0E4) + SFR_BASE_ADDR)
#define REG_I2CDEVID					((0xF0F0) + SFR_BASE_ADDR)
#define REG_MCFG00						((0xF800) + SFR_BASE_ADDR)
#define REG_ANACFG						((0xF804) + SFR_BASE_ADDR)
#define REG_I2C_VIHL_SEL				((0xF808) + SFR_BASE_ADDR)
#define REG_RAMBIST_IN					((0xF8D0) + SFR_BASE_ADDR)
#define REG_RAMBIST_OUT					((0xF8D4) + SFR_BASE_ADDR)
#define REG_HOSTCTRL					((0xFF00) + SFR_BASE_ADDR)
#define REG_HOSTCTRL2					((0xFF0C) + SFR_BASE_ADDR)
#define REG_CHIPID						((0xFF10) + SFR_BASE_ADDR)
#define REG_EFUSE_WORD					((0xFF80) + SFR_BASE_ADDR)

#define AW_EFUSE_DATA_CHECK_BIT		(31)
#define AW_EFUSE_STATUS_CHECK_BIT	(27)
#define AW_RESET_DELAY_MS			(25)
#define AW_READ_RESET_NUMS			(10)
#define AW965XX_AOT_ALL_CH              (0xFF00)
#define REG_ENABLE_RAM					(0xfff4)
#define RAM_ACCESS_ENABLE				(0x3C004411)
#define RAM_ACCESS_DISABLE				(0x3C004011)


#define AW965XX_AFE_SOFT_CV_MASK	(0x3)
#define AW965XX_AFE_CV_VREF_SEL_CH0_START_BIT	(29)
#define AW965XX_AFE_CV_VREF_SEL_CH0_BITS_LEN	(2)
#define AW965XX_AFE_CV_VREF_SEL_CH0_MASK	\
	(~(((1<<AW965XX_AFE_CV_VREF_SEL_CH0_BITS_LEN)-1) << AW965XX_AFE_CV_VREF_SEL_CH0_START_BIT))

#define AW965XX_AFE_CV_VREF_SEL_CH0_VREF_IS_0P25VCC_0P75VCC_400PF	(0)
#define AW965XX_AFE_CV_VREF_SEL_CH0_VREF_IS_0P25VCC_0P75VCC_400PF_VALUE	\
	(AW965XX_AFE_CV_VREF_SEL_CH0_VREF_IS_0P25VCC_0P75VCC_400PF << AW965XX_AFE_CV_VREF_SEL_CH0_START_BIT)

#define AW965XX_AFE_CV_VREF_SEL_CH0_VREF_IS_0P4VCC_0P6VCC_500PF	(1)
#define AW965XX_AFE_CV_VREF_SEL_CH0_VREF_IS_0P4VCC_0P6VCC_500PF_VALUE	\
	(AW965XX_AFE_CV_VREF_SEL_CH0_VREF_IS_0P4VCC_0P6VCC_500PF << AW965XX_AFE_CV_VREF_SEL_CH0_START_BIT)

#define AW965XX_AFE_CV_VREF_SEL_CH0_VREF_IS_0P5VCC_0P5VCC_600PF	(2)
#define AW965XX_AFE_CV_VREF_SEL_CH0_VREF_IS_0P5VCC_0P5VCC_600PF_VALUE	\
	(AW965XX_AFE_CV_VREF_SEL_CH0_VREF_IS_0P5VCC_0P5VCC_600PF << AW965XX_AFE_CV_VREF_SEL_CH0_START_BIT)
#define AW965XX_AFE_CV_VREF_SEL_CH0_DEFAULT_VALUE	\
	(AW965XX_AFE_CV_VREF_SEL_CH0_DEFAULT << AW965XX_AFE_CV_VREF_SEL_CH0_START_BIT)

#define AW965XX_AFE_CV_VREF_SEL_CH0_DEFAULT	(0)
#define AW965XX_AFE_CV_VREF_SEL_CH0_DEFAULT_VALUE	\
	(AW965XX_AFE_CV_VREF_SEL_CH0_DEFAULT << AW965XX_AFE_CV_VREF_SEL_CH0_START_BIT)

/* CV_MODE_SEL_CH0 bit 28:27 (AFE_SOFT_CFG0_CH0 0x0008) */
#define AW965XX_AFE_CV_MODE_SEL_CH0_START_BIT	(27)
#define AW965XX_AFE_CV_MODE_SEL_CH0_BITS_LEN	(2)
#define AW965XX_AFE_CV_MODE_SEL_CH0_MASK	\
	(~(((1<<AW965XX_AFE_CV_MODE_SEL_CH0_BITS_LEN)-1) << AW965XX_AFE_CV_MODE_SEL_CH0_START_BIT))

#define AW965XX_AFE_CV_MODE_SEL_CH0_X1NORMAL	(0)
#define AW965XX_AFE_CV_MODE_SEL_CH0_X1NORMAL_VALUE	\
	(AW965XX_AFE_CV_MODE_SEL_CH0_X1NORMAL << AW965XX_AFE_CV_MODE_SEL_CH0_START_BIT)

#define AW965XX_AFE_CV_MODE_SEL_CH0_X2VCM	(1)
#define AW965XX_AFE_CV_MODE_SEL_CH0_X2VCM_VALUE	\
	(AW965XX_AFE_CV_MODE_SEL_CH0_X2VCM << AW965XX_AFE_CV_MODE_SEL_CH0_START_BIT)

#define AW965XX_AFE_CV_MODE_SEL_CH0_X3DRV	(2)
#define AW965XX_AFE_CV_MODE_SEL_CH0_X3DRV_VALUE	\
	(AW965XX_AFE_CV_MODE_SEL_CH0_X3DRV << AW965XX_AFE_CV_MODE_SEL_CH0_START_BIT)

#define AW965XX_AFE_CV_MODE_SEL_CH0_OFF2XFB	(3)
#define AW965XX_AFE_CV_MODE_SEL_CH0_OFF2XFB_VALUE	\
	(AW965XX_AFE_CV_MODE_SEL_CH0_OFF2XFB << AW965XX_AFE_CV_MODE_SEL_CH0_START_BIT)

#define AW965XX_AFE_CV_MODE_SEL_CH0_DEFAULT	(0)
#define AW965XX_AFE_CV_MODE_SEL_CH0_DEFAULT_VALUE	\
	(AW965XX_AFE_CV_MODE_SEL_CH0_DEFAULT << AW965XX_AFE_CV_MODE_SEL_CH0_START_BIT)

/* CV_OFFSET_F_CH0 bit 25:18 (AFE_SOFT_CFG0_CH0 0x0008) */
#define AW965XX_AFE_CV_OFFSET_F_CH0_START_BIT	(18)
#define AW965XX_AFE_CV_OFFSET_F_CH0_BITS_LEN	(8)
#define AW965XX_AFE_CV_OFFSET_F_CH0_MASK	\
	(~(((1<<AW965XX_AFE_CV_OFFSET_F_CH0_BITS_LEN)-1) << AW965XX_AFE_CV_OFFSET_F_CH0_START_BIT))

#define AW965XX_AFE_CV_OFFSET_F_CH0_DEFAULT	(0)
#define AW965XX_AFE_CV_OFFSET_F_CH0_DEFAULT_VALUE	\
	(AW965XX_AFE_CV_OFFSET_F_CH0_DEFAULT << AW965XX_AFE_CV_OFFSET_F_CH0_START_BIT)

/* CV_OFFSET_C_CH0 bit 17:10 (AFE_SOFT_CFG0_CH0 0x0008) */
#define AW965XX_AFE_CV_OFFSET_C_CH0_START_BIT	(10)
#define AW965XX_AFE_CV_OFFSET_C_CH0_BITS_LEN	(8)
#define AW965XX_AFE_CV_OFFSET_C_CH0_MASK	\
	(~(((1<<AW965XX_AFE_CV_OFFSET_C_CH0_BITS_LEN)-1) << AW965XX_AFE_CV_OFFSET_C_CH0_START_BIT))

#define AW965XX_AFE_CV_OFFSET_C_CH0_DEFAULT	(0)
#define AW965XX_AFE_CV_OFFSET_C_CH0_DEFAULT_VALUE	\
	(AW965XX_AFE_CV_OFFSET_C_CH0_DEFAULT << AW965XX_AFE_CV_OFFSET_C_CH0_START_BIT)


/* CHIPID (0xFF10) detail */
/* ID_CHIPID bit 31:0 (CHIPID 0xFF10) */
#define AW965XX_SFR_ID_CHIPID_START_BIT	(0)
#define AW965XX_SFR_ID_CHIPID_BITS_LEN	(32)
#define AW965XX_SFR_ID_CHIPID_MASK		\
	(~(((1<<AW965XX_SFR_ID_CHIPID_BITS_LEN)-1) << AW965XX_SFR_ID_CHIPID_START_BIT))

#define AW965XX_SFR_ID_CHIPID_AW96503CSR	(168361985)
#define AW965XX_SFR_ID_CHIPID_AW96503CSR_VALUE	\
	(AW965XX_SFR_ID_CHIPID_AW96503CSR << AW965XX_SFR_ID_CHIPID_START_BIT)

#define AW965XX_SFR_ID_CHIPID_AW96505CSR	(168361986)
#define AW965XX_SFR_ID_CHIPID_AW96505CSR_VALUE	\
	(AW965XX_SFR_ID_CHIPID_AW96505CSR << AW965XX_SFR_ID_CHIPID_START_BIT)

#define AW965XX_SFR_ID_CHIPID_AW96505DNR	(168361987)
#define AW965XX_SFR_ID_CHIPID_AW96505DNR_VALUE	\
	(AW965XX_SFR_ID_CHIPID_AW96505DNR << AW965XX_SFR_ID_CHIPID_START_BIT)

#define AW965XX_SFR_ID_CHIPID_AW96506QNR	(168361988)
#define AW965XX_SFR_ID_CHIPID_AW96506QNR_VALUE	\
	(AW965XX_SFR_ID_CHIPID_AW96506QNR << AW965XX_SFR_ID_CHIPID_START_BIT)

#define AW965XX_SFR_ID_CHIPID_AW96508QNR	(168361989)
#define AW965XX_SFR_ID_CHIPID_AW96508QNR_VALUE	\
	(AW965XX_SFR_ID_CHIPID_AW96508QNR << AW965XX_SFR_ID_CHIPID_START_BIT)

#define AW965XX_SFR_ID_CHIPID_DEFAULT	(168361986)
#define AW965XX_SFR_ID_CHIPID_DEFAULT_VALUE	\
	(AW965XX_SFR_ID_CHIPID_DEFAULT << AW965XX_SFR_ID_CHIPID_START_BIT)

struct reg_data {
	unsigned char rw;
	unsigned short reg;
};
/********************************************
 * Register Access
 *******************************************/
#define REG_NONE_ACCESS					(0)
#define REG_RD_ACCESS					(1 << 0)
#define REG_WR_ACCESS					(1 << 1)

static const struct reg_data g_aw965xx_reg_access[] = {
	//AFE MAP
	{ .reg = REG_SCANCTRL0,			.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SCANCTRL1,			.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG0_CH0,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG1_CH0,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG2_CH0,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG0_CH1,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG1_CH1,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG2_CH1,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG0_CH2,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG1_CH2,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG2_CH2,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG0_CH3,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG1_CH3,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG2_CH3,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG0_CH4,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG1_CH4,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG2_CH4,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG0_CH5,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG1_CH5,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG2_CH5,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG0_CH6,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG1_CH6,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG2_CH6,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG0_CH7,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG1_CH7,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_AFE_SOFT_CFG2_CH7,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },

	//DSP MAP
	{ .reg = REG_FILT_CTRL0_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL1_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL2_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL3_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT0_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT1_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT2_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT3_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT4_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT5_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT6_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL0_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL1_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL2_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL0_CH0,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL1_CH0,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL2_CH0,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL0_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL1_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL0_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL1_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL2_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL3_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT0_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT1_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT2_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT3_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT4_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT5_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT6_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL0_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL1_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL2_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL0_CH1,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL1_CH1,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL2_CH1,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL0_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL1_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL0_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL1_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL2_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL3_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT0_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT1_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT2_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT3_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT4_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT5_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT6_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL0_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL1_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL2_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL0_CH2,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL1_CH2,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL2_CH2,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL0_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL1_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL0_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL1_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL2_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL3_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT0_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT1_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT2_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT3_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT4_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT5_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT6_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL0_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL1_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL2_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL0_CH3,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL1_CH3,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL2_CH3,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL0_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL1_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL0_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL1_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL2_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL3_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT0_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT1_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT2_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT3_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT4_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT5_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT6_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL0_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL1_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL2_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL0_CH4,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL1_CH4,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL2_CH4,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL0_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL1_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL0_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL1_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL2_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL3_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT0_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT1_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT2_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT3_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT4_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT5_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT6_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL0_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL1_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL2_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL0_CH5,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL1_CH5,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL2_CH5,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL0_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL1_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL0_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL1_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL2_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL3_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT0_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT1_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT2_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT3_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT4_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT5_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT6_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL0_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL1_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL2_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL0_CH6,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL1_CH6,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL2_CH6,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL0_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL1_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL0_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL1_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL2_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FILT_CTRL3_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT0_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT1_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT2_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT3_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT4_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT5_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_BL_FILT6_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL0_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL1_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_PROX_CTRL2_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL0_CH7,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL1_CH7,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_FLOAT_COMP_CTRL2_CH7,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL0_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAW_CTRL1_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_REF_CTRL_ENGINE0,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_REF_CTRL_ENGINE1,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_REF_CTRL_ENGINE2,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_REF_CTRL_ENGINE3,	.rw = REG_RD_ACCESS | REG_WR_ACCESS, },

	//STAT MAP
	{ .reg = REG_FIREWARE_VERSION_INFO,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_FIREWARE_INTERNAL_INFO,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_PST,					.rw = REG_RD_ACCESS, },
	{ .reg = REG_STAT0,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_STAT1,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_PROX_INT_EN,			.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_EFUSE_DATA,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_CS_STATUS,			.rw = REG_RD_ACCESS, },

	//DATA MAP
	{ .reg = REG_VALID_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_CH0,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_CH1,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_CH2,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_CH3,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_CH4,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_CH5,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_CH6,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_CH7,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_PREDIFF_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_PREDIFF_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_PREDIFF_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_PREDIFF_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_PREDIFF_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_PREDIFF_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_PREDIFF_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_PREDIFF_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_DIFF_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_DIFF_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_DIFF_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_DIFF_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_DIFF_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_DIFF_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_DIFF_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_DIFF_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MIN_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MIN_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MIN_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MIN_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MIN_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MIN_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MIN_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MIN_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MAX_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MAX_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MAX_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MAX_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MAX_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MAX_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MAX_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_MAX_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_AVE_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_AVE_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_AVE_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_AVE_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_AVE_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_AVE_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_AVE_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_ADC_AVE_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_RAW_CH0,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_RAW_CH1,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_RAW_CH2,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_RAW_CH3,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_RAW_CH4,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_RAW_CH5,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_RAW_CH6,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_RAW_CH7,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_LPF_CH0,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_LPF_CH1,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_LPF_CH2,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_LPF_CH3,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_LPF_CH4,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_LPF_CH5,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_LPF_CH6,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_LPF_CH7,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_SAT_CH0,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_SAT_CH1,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_SAT_CH2,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_SAT_CH3,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_SAT_CH4,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_SAT_CH5,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_SAT_CH6,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_SAT_CH7,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_LAST_CH0,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_LAST_CH1,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_LAST_CH2,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_LAST_CH3,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_LAST_CH4,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_LAST_CH5,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_LAST_CH6,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_VALID_LAST_CH7,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_DELTAVALID_CH0,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_DELTAVALID_CH1,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_DELTAVALID_CH2,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_DELTAVALID_CH3,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_DELTAVALID_CH4,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_DELTAVALID_CH5,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_DELTAVALID_CH6,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_DELTAVALID_CH7,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_COMP_LAST_AVG_CH0,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_COMP_LAST_AVG_CH1,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_COMP_LAST_AVG_CH2,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_COMP_LAST_AVG_CH3,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_COMP_LAST_AVG_CH4,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_COMP_LAST_AVG_CH5,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_COMP_LAST_AVG_CH6,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_COMP_LAST_AVG_CH7,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_CS_ERR_DATA0,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_CS_ERR_DATA1,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_CS_ERR_DATA2,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_CS_ERR_DATA3,		.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE0_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE1_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE2_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE3_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE4_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE5_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE6_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE7_CH0,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE0_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE1_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE2_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE3_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE4_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE5_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE6_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE7_CH1,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE0_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE1_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE2_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE3_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE4_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE5_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE6_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE7_CH2,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE0_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE1_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE2_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE3_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE4_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE5_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE6_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE7_CH3,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE0_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE1_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE2_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE3_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE4_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE5_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE6_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE7_CH4,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE0_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE1_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE2_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE3_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE4_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE5_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE6_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE7_CH5,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE0_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE1_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE2_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE3_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE4_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE5_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE6_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE7_CH6,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE0_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE1_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE2_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE3_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE4_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE5_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE6_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_AFE7_CH7,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_MULTI_CH0,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_MULTI_CH1,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_MULTI_CH2,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_MULTI_CH3,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_MULTI_CH4,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_MULTI_CH5,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_MULTI_CH6,	.rw = REG_RD_ACCESS, },
	{ .reg = REG_BASELINE_MULTI_CH7,	.rw = REG_RD_ACCESS, },

	//DSPEX MAP
	{ .reg = REG_SSR_CTRL0_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL1_CH0,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL0_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL1_CH1,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL0_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL1_CH2,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL0_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL1_CH3,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL0_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL1_CH4,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL0_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL1_CH5,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL0_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL1_CH6,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL0_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_SSR_CTRL1_CH7,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },

	//SFR MAP
	{ .reg = REG_CMD,					.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_IRQSRC,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_IRQEN,				.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_I2CTIMEOUTEN,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_I2CDEVID,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_MCFG00,				.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_ANACFG,				.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_I2C_VIHL_SEL,		.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAMBIST_IN,			.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_RAMBIST_OUT,			.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_HOSTCTRL,			.rw = REG_RD_ACCESS, },
	{ .reg = REG_HOSTCTRL2,			.rw = REG_RD_ACCESS | REG_WR_ACCESS, },
	{ .reg = REG_CHIPID,				.rw = REG_RD_ACCESS, },
	{ .reg = REG_EFUSE_WORD,			.rw = REG_RD_ACCESS, },

};


static const uint32_t aw965xx_reg_default[] = {
	0x073C, 0x34049207,
	0x075C, 0x34049207,
	0x077C, 0x34049207,
	0x079C, 0x34049207,
	0x07BC, 0x34049207,
	0x0000, 0x000F1F1F,
	0x0008, 0x0000018C,
	0x0010, 0x016DB6D9,
	0x0014, 0x0000018C,
	0x001C, 0x016DB6CB,
	0x0020, 0x0000018C,
	0x0028, 0x016DB65B,
	0x002C, 0x0000018C,
	0x0034, 0x016DB2DB,
	0x0038, 0x0000018C,
	0x0040, 0x0165B6DB,
	0x0094, 0x0000C350,
	0x00E0, 0x0000C350,
	0x012C, 0x0000C350,
	0x0178, 0x0000C350,
	0x01C4, 0x0000C350,
	0xF084, 0x00000007,

};
/* default value of EFUSE_WORD (0xFF80) */
/* #define A2431A_AW96508QNR_0218_SFR_EFUSE_WORD_DEFAULT		(0x00000000) */

/* detail information of registers end */


#endif
