load("//soc-repo:kleaf-scripts/moto/moto_modules_define.bzl", "moto_ddk_module")

exports_files(["Kconfig"])

moto_ddk_module(
    name = "aw965xx_sar",
    srcs = [
        "aw965xx.h",
        "aw_sar.h",
        "comm/aw_sar_type.h",
        "comm/aw_sar_comm_interface.h",
        "comm/aw_sar_chip_interface.h",
        "aw_sar.c",
        "comm/aw_sar_comm_interface.c",
        "aw965xx.c",
    ],
    deps_ext = [
        "//soc-repo:drivers/soc/qcom/smem",
        "//motorola/kernel/modules/drivers/sensors:sensors_class",
        "//motorola/kernel/modules/drivers/misc/hall:hall_phone_case",
    ],
)
