# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

obj-m	+= aw_haptic_hv_v1_10.o
aw_haptic_hv_v1_10-objs	:= aw869x.o aw869xx.o aw8671x.o aw8672x.o aw8692x.o aw8693x.o aw8693xs.o haptic_hv.o

