ifeq ($(ANDROID_BUILD_TOP),)
	ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
#EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/wt6670f_qc3p_mmi


obj-m += wt6670f_qc3p_mmi.o
wt6670f_qc3p_mmi-objs += wt6670f_qc3p.o
