ifeq ($(ANDROID_BUILD_TOP),)
	ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/bq25980_mmi \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/kernel-5.15/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1/include \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/kernel-6.6/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.6/include \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.6/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.12/include \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.12/drivers/power/supply

obj-m += bq25980_mmi.o
