# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/misc/awinic/aw862x_haptic_nv

ifneq (,$(filter kobe%, $(TARGET_PRODUCT)))
       EXTRA_CFLAGS += -DFCNT_VIBRATION
       EXTRA_CFLAGS += -DAW_UEFI_F0_CALIBRATION
endif

ifneq (,$(filter kobe, $(TARGET_PRODUCT)))
       EXTRA_CFLAGS += -DCONFIG_AF_NOISE_ELIMINATION
endif

obj-m += aw862x_haptic_nv.o

aw862x_haptic_nv-objs += haptic_nv.o
aw862x_haptic_nv-objs += aw862xx.o
aw862x_haptic_nv-objs += aw8623x.o
aw862x_haptic_nv-objs += aw8624.o

