DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

ifeq ($(DRM_PANEL_EVENT_NOTIFICATIONS),true)
	KBUILD_OPTIONS += CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS=y
endif

ifeq ($(TOUCHSCREEN_LAST_TIME),true)
	KBUILD_OPTIONS += CONFIG_GTP_LAST_TIME=y
endif

ifeq ($(ENABLE_GTP_PALM_CANCEL),true)
	KBUILD_OPTIONS += CONFIG_ENABLE_GTP_PALM_CANCEL=y
endif

ifneq ($(GTP_ENABLE_TOUCH_PALM_BY_ID),)
	KBUILD_OPTIONS += CONFIG_GTP_ENABLE_TOUCH_PALM_BY_ID=y
endif

ifeq ($(GTP_ENABLE_PM_QOS),true)
	KBUILD_OPTIONS += CONFIG_GTP_ENABLE_PM_QOS=y
endif

include $(CLEAR_VARS)
LOCAL_MODULE := goodix_brl_thp.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/mmi_info.ko

ifneq ($(findstring touchscreen_u_mmi.ko,$(BOARD_VENDOR_KERNEL_MODULES)),)
	KBUILD_OPTIONS += CONFIG_INPUT_TOUCHSCREEN_MMI=y
	LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/touchscreen_u_mmi.ko
	LOCAL_REQUIRED_MODULES += touchscreen_u_mmi.ko
endif
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
include $(DLKM_DIR)/AndroidKernelModule.mk
