# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

obj-m := goodix_brl_thp.o
goodix_brl_thp-objs := \
					goodix_thp.o \
					goodix_thp_spi.o \
					goodix_thp_config.o

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_GTP_LAST_TIME)),)
	EXTRA_CFLAGS += -DCONFIG_GTP_LAST_TIME
endif

ifneq ($(filter m y,$(CONFIG_ENABLE_GTP_PALM_CANCEL)),)
	EXTRA_CFLAGS += -DCONFIG_ENABLE_GTP_PALM_CANCEL
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
	EXTRA_CFLAGS += -DCONFIG_INPUT_TOUCHSCREEN_MMI
	goodix_brl_thp-objs += goodix_thp_mmi.o
endif

ifneq ($(filter m y,$(CONFIG_GTP_ENABLE_TOUCH_PALM_BY_ID)),)
	EXTRA_CFLAGS += -DCONFIG_ENABLE_GTP_PALM_CANCEL_BY_ID
endif

ifneq ($(filter m y,$(CONFIG_GTP_ENABLE_PM_QOS)),)
    EXTRA_CFLAGS += -DCONFIG_TOUCHIRQ_UPDATE_QOS
endif

ifneq ($(filter m y,$(CONFIG_INPUT_GTP_PASSIVE_PEN_NOTIFIER)),)
	EXTRA_CFLAGS += -DGTP_PEN_NOTIFIER
endif
ifneq ($(filter m y,$(CONFIG_ENABLE_TOUCH_CPU_BOOST)),)
    EXTRA_CFLAGS += -DCONFIG_ENABLE_TOUCH_CPU_BOOST
endif

ifneq ($(filter m y,$(CONFIG_TOUCH_HARDWARE_STATUS)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_HARDWARE_STATUS
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
ifneq ($(filter m y, $(CONFIG_INPUT_GTP_PASSIVE_PEN_NOTIFIER)),)
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../misc/hall/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif
