load("//soc-repo:kleaf-scripts/moto/moto_modules_define.bzl", "moto_ddk_module")

moto_ddk_module(
    name = "sys_monitor",
    srcs = [
        "monitor.h",
        "main.c",
        "sleep.c",
        "misc.c",
        "wakelock_profiler.c",
    ],
    deps_ext = [
        "//soc-repo:drivers/soc/qcom/smem",
        "//soc-repo:net/qrtr/qrtr"
    ],
)
