load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")

moto_ddk_module(
    name = "sys_monitor",
    srcs = [
        "monitor.h",
        "main.c",
        "sleep.c",
    ],
    deps_ext = [
        "//soc-repo:drivers/soc/qcom/smem",
        "//soc-repo:net/qrtr/qrtr",
        "//soc-repo:drivers/base/power"
    ],
)
