# Allow include external library files.
subdir-ccflags-y += -I$(src)/libqmrom/include -I$(src)/libfwupdater/include -I$(src)/../../base/qm\
 -I$(srctree)/$(src)/libqmrom/include -I$(srctree)/$(src)/libfwupdater/include -I$(srctree)/../../base/qm

# QM35 transport modules
# Build qm35_spi.ko only if SPI supported on target kernel.
qm35_spi-y := \
		libfwupdater/src/fwupdater.o \
		libqmrom/src/qm357xx_rom_b0.o \
		libqmrom/src/qm357xx_rom_c0.o \
		libqmrom/src/qm357xx_rom_common.o \
		libqmrom/src/qm358xx_rom.o \
		libqmrom/src/qmrom_common.o \
		libqmrom/src/qmrom_log.o \
		qm35_hsspi.o \
		qm35_spi_fw.o \
		qm35_spi_main.o \
		qm35_spi_pm.o \
		qm35_spi_setup.o \
		qm35_spi_thread.o \
		qm35_spi_transport.o \
		qm35_spi_trc.o \
		qm35_uci_probe.o \
		qmrom_wrapper.o

# Uncomment to change default debug_flags to 18 (AUTO_TRACE|NO_RESET_ON_SUSPEND)
#CFLAGS_qm35_spi_main.o := -DDEFAULT_DEBUG_FLAGS=18
# Uncomment to change default auto suspend delay value to 250 MS
CFLAGS_qm35_spi_pm.o := -DAUTOSUSPEND_DELAY_MS=0

CFLAGS_libqmrom/src/qm357xx_rom_c0.o := -DCONFIG_FLASHING_STATS
CFLAGS_libqmrom/src/qm358xx_rom.o := -DCONFIG_FLASHING_STATS
CFLAGS_libfwupdater/src/fwupdater.o := -DCONFIG_FLASHING_STATS
obj-m += ../../../qm35_spi.o

