# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/gpu/drm/mediatek/mediatek_v2/
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/nova_0flash_mmi_v2

ifeq ($(filter m y, $(CONFIG_TOUCHSCREEN_NT36xxx_HOSTDL_SPI)),)
	obj-m := nova_0flash_mmi_v2.o
endif
ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DNVT_SENSOR_EN
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif
ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_NOTIFY_TOUCH_STATE)),)
	EXTRA_CFLAGS += -DNVT_SET_TOUCH_STATE
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DNVT_DOUBLE_TAP_CTRL
endif

ifneq ($(filter m y, $(CONFIG_MTK_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCFG_MTK_PANEL_NOTIFIER
endif

ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_MULTI_SUPPLIER)),)
	EXTRA_CFLAGS += -DNVT_CONFIG_MULTI_SUPPLIER
endif

ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_CHIP_VER_1)),)
	EXTRA_CFLAGS += -DNVT_CONFIG_CHIP_VER_1
endif

ifneq ($(filter m y,$(CONFIG_NOVA_ESD_ENABLE)),)
	EXTRA_CFLAGS += -DNVT_CONFIG_ESD_ENABLE
endif

ifneq ($(filter m y,$(CONFIG_NOVA_LCM_FAST_LIGHTUP)),)
	EXTRA_CFLAGS += -DLCM_FAST_LIGHTUP
endif

ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_STYLUS_PALM)),)
	EXTRA_CFLAGS += -DPALM_GESTURE
endif
ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_STYLUS_PALM_RANGE)),)
	EXTRA_CFLAGS += -DPALM_GESTURE_RANGE
endif
ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_PEN_NOTIFIER)),)
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../misc/pen/$(GKI_OBJ_MODULE_DIR)/Module.symvers
	EXTRA_CFLAGS += -DNOVATECH_PEN_NOTIFIER
endif
ifneq ($(filter m y,$(CONFIG_INPUT_NOVA_0FLASH_MMI_MTK_GET_PANEL)),)
	EXTRA_CFLAGS += -DNVT_MTK_GET_PANEL
endif

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
	EXTRA_CFLAGS += -DNVT_BUILD_USERDEBUG
endif

nova_0flash_mmi_v2-objs += nt36xxx.o
nova_0flash_mmi_v2-objs += nt36xxx_ext_proc.o
nova_0flash_mmi_v2-objs += nt36xxx_fw_update.o
nova_0flash_mmi_v2-objs += nt36xxx_mp_ctrlram.o
