DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
KERNEL_CFLAGS += CONFIG_ZRAM_EXT=y
KERNEL_CFLAGS += CONFIG_VENDOR_ZRAM_WRITEBACK=y

KBUILD_OPTIONS += CONFIG_ZRAM_EXT=y
KBUILD_OPTIONS += CONFIG_VENDOR_ZRAM_WRITEBACK=y

LOCAL_MODULE := moto_swap5.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki

include $(DLKM_DIR)/AndroidKernelModule.mk

