// SPDX-License-Identifier: GPL-2.0 OR Apache-2.0
/*
 * Copyright 2022 Qorvo US, Inc.
 *
 */

#include <qm358xx_firmware_pack_handling.h>
#include <qmrom.h>
#include <qmrom_log.h>
#include <qmrom_spi.h>
#include <qmrom_utils.h>
#include <spi_rom_protocol.h>

#define DEFAULT_SPI_CLOCKRATE 5000000
#define CHIP_VERSION_CHIP_REV_PAYLOAD_OFFSET (sizeof(resp_t))
#define CHIP_VERSION_DEV_REV_PAYLOAD_OFFSET \
	(CHIP_VERSION_CHIP_REV_PAYLOAD_OFFSET + 2)
#define CHUNK_SIZE 2036
#define CHUNK_PAYLOAD_MAX_SIZE (CHUNK_SIZE - CRYPTO_FIRMWARE_CHUNK_HDR_SIZE)

enum qm358xx_rom_cmd_e {
	/*! Defines the null placeholder for no command code. */
	CMD_NONE = 0x0u,
	/*! Defines the get chip version command code. */
	CMD_GET_CHIP_VERSION = 0x2u,
	/*! Defines the get soc info command code. */
	CMD_GET_SOC_INFO,
	/*! Defines the load firmware package command code. */
	CMD_LOAD_FW_PKG,
	/*! Defines the load asset package command code. */
	CMD_LOAD_ASSET_PKG,
	/*! Defines the load secure debug package command code. */
	CMD_LOAD_SECURE_DEBUG_PKG,
	/*! Defines the erase secure debug package command code. */
	CMD_ERASE_SECURE_DEBUG_PKG,
	/*! Defines the load SRAM firmware command code. */
	CMD_LOAD_SRAM,
	/*! Defines the run test mode command code. */
	CMD_RUN_TEST_MODE,
	/*! Defines the generate master secret and uuid command code. */
	CMD_GENERATE_MASTER_SECRET_AND_UUID,
};

/*! Defines the null placeholder for no sub-command code. */
#define SUB_CMD_NONE 0x0
/*! Defines the sub-command code base value. */
#define SUB_CMD_BASE 0x0

enum qm358xx_rom_sub_cmd_load_fw_pkg_e {
	/*! Defines the load firmware package header sub-command code. */
	SUB_CMD_LOAD_FW_PKG_HDR = SUB_CMD_BASE,
	/*! Defines the load firmware package payload chunk sub-command code. */
	SUB_CMD_LOAD_FW_PKG_PAYLOAD_CHUNK
};

enum qm358xx_rom_sub_cmd_load_sram_e {
	/*! Defines the load SRAM file size sub-command code. */
	SUB_CMD_LOAD_SRAM_FILE_SIZE = SUB_CMD_BASE,
	/*! Defines the load SRAM image data sub-command code. */
	SUB_CMD_LOAD_SRAM_IMG_DATA
};

enum response_code_e {
	/*! Defines the null placeholder for no response code. */
	RESP_NONE = 0x0000,
	/*! Defines the response code base value. */
	RESP_OK = 0xA000,
	/*! Defines the command mode ready response code. */
	RESP_CMD_MODE_READY = RESP_OK,
	/*! Defines the get chip version success response code. */
	RESP_GET_CHIP_VERSION_SUCCESS = (RESP_OK + CMD_GET_CHIP_VERSION),
	/*! Defines the soc info success response code. */
	RESP_GET_SOC_INFO_SUCCESS = (RESP_OK + CMD_GET_SOC_INFO),
	/*! Defines the load asset package completed successfully response code */
	RESP_LOAD_ASSET_PKG_SUCCESS = (RESP_OK + CMD_LOAD_ASSET_PKG),
	/*! Defines the load firmware package all images verified response code. */
	RESP_LOAD_FW_PKG_VERIFIED_IMGS_COMPLETED = (RESP_OK + CMD_LOAD_FW_PKG),
	/*! Defines the load secure debug package success response code. */
	RESP_LOAD_SEC_DEBUG_PKG_SUCCESS = (RESP_OK + CMD_LOAD_SECURE_DEBUG_PKG),
	/*! Defines the load secure debug package storing failed response code. */
	RESP_ERASE_SEC_DEBUG_PKG_SUCCESS =
		(RESP_OK + CMD_ERASE_SECURE_DEBUG_PKG),
	/*! Defines the generation of master secret and UUID success response code. */
	RESP_GENERATE_MASTER_SECRET_AND_UUID_SUCCESS =
		(RESP_OK + CMD_GENERATE_MASTER_SECRET_AND_UUID),
	/*! Defines the response code error base value. */
	RESP_ERR_BASE = 0xE000,
	/*! Defines the invalid command response code. */
	RESP_INVALID_CMD = (RESP_ERR_BASE + 0x101),
	/*! Defines the invalid I3C command response code. */
	RESP_INVALID_I3C_CMD,
	/*! Defines the soc info failed response code. */
	RESP_GET_SOC_INFO_FAILED = (RESP_ERR_BASE + 0x201),
	/*! Defines the load asset package failed response code. */
	RESP_LOAD_ASSET_PKG_FAILED = (RESP_ERR_BASE + 0x301),
	/*! Defines the load asset package failed response code. Cmd not allowed for this LCS */
	RESP_LOAD_ASSET_PKG_CMD_NOT_ALLOWED_FOR_CURRENT_LCS,
	/*! Defines the load asset package invalid size response code. */
	RESP_LOAD_ASSET_PKG_INVALID_ASSET_SIZE,
	/*! Defines the load firmware package invalid command response code. */
	RESP_LOAD_FW_PKG_INVALID_CMD = (RESP_ERR_BASE + 0x401),
	/*! Defines the load firmware package invalid sub-command response code. */
	RESP_LOAD_FW_PKG_INVALID_SUB_CMD,
	/*! Defines the load firmware package invalid certificate size response code. */
	RESP_LOAD_FW_PKG_INVALID_CERT_SIZE,
	/*! Defines the load firmware package header verification failed response code. */
	RESP_LOAD_FW_PKG_HDR_VERIFY_FAILED,
	/*! Defines the load firmware package payload chunk verification failed response code. */
	RESP_LOAD_FW_PKG_PAYLOAD_CHUNK_VERIFY_FAILED,
	/*! Defines the load firmware package set IV failed response code. */
	RESP_LOAD_FW_PKG_SET_IV_FAILED,
	/*! Defines the load firmware package decrypt payload failed response code. */
	RESP_LOAD_FW_PKG_DECRYPT_PAYLOAD_FAILED,
	/*! Defines the load firmware package image header verification failed response code. */
	RESP_LOAD_FW_PKG_VERIFY_IMG_HDR_FAILED,
	/*! Defines the load firmware package secure boot package verification failed response code. */
	RESP_LOAD_FW_PKG_VERIFY_SB_PKG_FAILED,
	/*! Defines the load firmware package secure boot package storing failed response code. */
	RESP_LOAD_FW_PKG_STORE_SB_PKG_FAILED,
	/*! Defines the load firmware package image storing failed response code. */
	RESP_LOAD_FW_PKG_STORE_IMG_FAILED,
	/*! Defines the load firmware package image verification failed response code. */
	RESP_LOAD_FW_PKG_VERIFY_IMG_FAILED,
	/*! Defines the load firmware package invalid chunk size response code. */
	RESP_LOAD_FW_PKG_INVALID_CHUNK_SIZE,
	/*! Defines the load firmware package secure boot package L2 encryption lock check failed response code. */
	RESP_LOAD_FW_PKG_LOCK_L2_ENC_CHECK_FAILED,
	/*! Defines the load to SRAM response code. Size is 0*/
	RESP_LOAD_SRAM_SIZE_0 = (RESP_ERR_BASE + 0x501),
	/*! Defines the load to SRAM response code. Size is too big */
	RESP_LOAD_SRAM_SIZE_TOO_BIG,
	/*! Defines the load to SRAM response code. Wrong sub command */
	RESP_LOAD_SRAM_INVALID_SUB_CMD,
	/*! Defines the load to SRAM response code. Cmd not allowed for this LCS */
	RESP_LOAD_SRAM_CMD_NOT_ALLOWED_FOR_CURRENT_LCS,
	/*! Defines the load to SRAM got data more data than expected */
	RESP_LOAD_SRAM_GOT_DATA_MORE_THAN_EXPECTED,
	/*! Defines the load to SRAM got wrong command */
	RESP_LOAD_SRAM_INVALID_CMD,
	/*! Defines run test failed response code. */
	RESP_RUN_TEST_FAILED = (RESP_ERR_BASE + 0x601),
	/*! Defines run test failed response code. Cmd not allowed for this LCS */
	RESP_RUN_TEST_CMD_NOT_ALLOWED_FOR_CURRENT_LCS,
	/*! Defines the load secure debug package failed response code. */
	RESP_LOAD_SEC_DEBUG_PKG_FAILED = (RESP_ERR_BASE + 0x701),
	/*! Defines the load secure debug package storing failed response code. */
	RESP_LOAD_SEC_DEBUG_PKG_STORE_FAILED,
	/*! Defines the load secure debug package command not allowed for this LCS. */
	RESP_LOAD_SEC_DEBUG_PKG_NOT_ALLOWED_FOR_CURRENT_LCS,
	/*! Defines the load secure debug package invalid size response code. */
	RESP_LOAD_SEC_DEBUG_PKG_INVALID_SIZE,
	/*! Defines the erase secure debug package wiping failed response code. */
	RESP_ERASE_SEC_DEBUG_PKG_WIPE_FAILED = (RESP_ERR_BASE + 0x801),
	/*! Defines the generate master secret and UUID error during master secret generation. */
	RESP_GENERATE_MASTER_SECRET_ERROR = (RESP_ERR_BASE + 0xA01),
	/*! Defines the generate master secret and UUID error during UUID loading. */
	RESP_GENERATE_UUID_ERROR,
	/*! Defines the generate master secret and UUID return code for when the UUID has already been generated. */
	RESP_GENERATE_UUID_ALREADY_GENERATED,
	/*! Defines the generate master secret and UUID return code for when the current LCS does not allow the
         * command. */
	RESP_GENERATE_MASTER_SECRETS_NOT_ALLOWED_LCS
};

enum qm358xx_error_code_e {
	SB_OK = 0x3E9,
	RRAM_ERROR_ADDRESS_RANGE = 1,
	RRAM_ERROR_ADDRESS_ALIGN = 2,
	RRAM_ERROR_DATA_SIZE = 3,
	RRAM_ERROR_TIMEOUT = 4,
	RRAM_ERROR_WR_ERROR = 5,
	RRAM_ERROR_UNSUPPORTED_API = 6,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_MAGIC_INVALID = 0xF1000101,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_VERSION_INVALID = 0xF1000102,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_SIZE_INVALID = 0xF1000103,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_CONTEXT_INVALID = 0xF1000104,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_CUST_ID_INVALID = 0xF1000105,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_PROD_ID_INVALID = 0xF1000106,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_SEC_VERSION_INVALID = 0xF1000107,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_ARB_VERSION_INVALID = 0xF1000108,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_LENGTH_INVALID = 0xF1000109,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_LOAD_VERIF_INVALID =
		0xF100010A,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_HASH_INVALID = 0xF100010B,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_FLASH_ADDR_INVALID =
		0xF100010C,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_LOAD_ADDR_INVALID =
		0xF100010D,
	CRYPTO_IMAGES_CERT_ERROR_CONTENT_VERIFICATION_FAILED = 0xF100010E,
	CRYPTO_IMAGES_CERT_ERROR_KEY_MAGIC_INVALID = 0xF1000201,
	CRYPTO_IMAGES_CERT_ERROR_KEY_VERSION_INVALID = 0xF1000202,
	CRYPTO_IMAGES_CERT_ERROR_KEY_SIZE_INVALID = 0xF1000203,
	CRYPTO_IMAGES_CERT_ERROR_KEY_CONTEXT_INVALID = 0xF1000204,
	CRYPTO_IMAGES_CERT_ERROR_KEY_CUST_ID_INVALID = 0xF1000205,
	CRYPTO_IMAGES_CERT_ERROR_KEY_PROD_ID_INVALID = 0xF1000206,
	CRYPTO_IMAGES_CERT_ERROR_KEY_SEC_VERSION_INVALID = 0xF1000207,
	CRYPTO_IMAGES_CERT_ERROR_KEY_ARB_VERSION_INVALID = 0xF1000208,
	CRYPTO_IMAGES_CERT_ERROR_KEY_HASH_ID_INVALID = 0xF1000209,
	CRYPTO_IMAGES_CERT_ERROR_KEY_HASH_INVALID = 0xF100020A,
	CRYPTO_IMAGES_CERT_ERROR_KEY_PUBLIC_KEY_INVALID = 0xF100020B,
	CRYPTO_IMAGES_CERT_STATUS_KEY_PARTLY_VERIFIED_LCS = 0xA3E9,
	CRYPTO_IMAGES_CERT_STATUS_KEY_PARTLY_VERIFIED_NON_SECURE = 0x5539,
	CRYPTO_IMAGES_CERT_STATUS_CONTENT_PARTLY_VERIFIED = 0xE3E9,
	E_KSSL_ONGOING = 0xF2000000,
	E_KSSL_SUCCESS = 0xF2000001,
	E_KSSL_ABORTED = 0xF2000002,
	E_KSSL_ERR_HW_BUSY = 0xF2000003,
	E_KSSL_ERR_NOT_PENDING = 0xF2000004,
	E_KSSL_ERR_PARAMETERS = 0xF2000005,
	E_KSSL_ERR_SEED_NOT_LOADED = 0xF2000006,
	E_KSSL_ERR_NOT_SUPPORTED = 0xF2000007,
	E_KSSL_ERR_INVALID_KEY = 0xF2000008,
	E_KSSL_ERR_WRONG_AUTH_TAG = 0xF2000009,
	E_KSSL_ERR_WRONG_SIGNATURE = 0xF200000A,
	E_KSSL_ERR_POINT_CHECK = 0xF200000B,
	E_KSSL_ERR_NOT_AVAILABLE = 0xF200000C,
	E_KSSL_ERR_HW_FAILURE = 0xF200000D,
	E_KSSL_ERR_BAD_SEQUENCE = 0xF200000E,
	E_KSSL_ERR_INVALID_EXEC_CTX = 0xF200000F,
	E_KSSL_ERR_DRBG_CONTEXT = 0xF2000010,
	E_KSSL_ERR_POINT_AT_INFINITY = 0xF2000011,
	E_KSSL_ERR_AEAD_WRONG_TAG = 0xF2000012,
	E_KSSL_ERR_BAD_STATE = 0xF2000013,
	E_KSSL_ERR_RESTRICTION = 0xF2000014,
	E_KSSL_ERR_MISSING_KEY = 0xF2000015,
	E_KSSL_ERR_DBG_OBJ_REVOKED = 0xF2000016,
	E_KSSL_ERR_INVALID_FORMAT = 0xF2000017,
	E_KSSL_ERR_OTP = 0xF2000018,
	CRYPTO_KEY_GEN_INVALID_KEY_ID_ERROR = 0xF4000001,
	CRYPTO_KEY_GEN_NULL_POINTER_ERROR = 0xF4000002,
	CRYPTO_KEY_GEN_INVALID_CONFIG_CERT_ERROR = 0xF4000003,
	CRYPTO_KEY_GEN_INVALID_FW_PACK_ERROR = 0xF4000004,
	WDT_ERROR = 0xF6000001,
	ECC_SRAM_ERROR = 0xF6000002,
	EFLASH_STR_ERROR = 0xF6000003,
	VWARN_ERROR = 0xF6000004,
	CRYPTO_COMMON_ERROR_BASE = 0xF6000100,
	CRYPTO_COMMON_ERROR_INVALID_SEC_VERSION = 0xF6000101,
	CRYPTO_COMMON_ERROR_INVALID_ARB_VERSION = 0xF6000102,
	CRYPTO_UTIL_ERROR_MEMCPY_DEST_ADDR_IS_NULL = 0xF6004101,
	CRYPTO_UTIL_ERROR_MEMCPY_DEST_SIZE_INVALID = 0xF6004102,
	CRYPTO_UTIL_ERROR_MEMCPY_SRC_ADDR_IS_NULL = 0xF6004103,
	CRYPTO_UTIL_ERROR_MEMCPY_SRC_SIZE_INVALID = 0xF6004104,
	CRYPTO_UTIL_ERROR_MEMCPY_MEM_OVERLAP = 0xF6004105,
	CRYPTO_UTIL_ERROR_MEMCPY_RAND_ERROR = 0xF6004106,
	CRYPTO_UTIL_ERROR_MEMCPY_SEC_CHECK_VAL_INVALID = 0xF6004107,
	CRYPTO_UTIL_ERROR_MEMCMP_NOT_EQUAL = 0xF6004201,
	CRYPTO_UTIL_ERROR_MEMCMP_INVALID_PARAM = 0xF6004202,
	CRYPTO_OTP_ERROR_BASE = 0xF6010000,
	CRYPTO_OTP_ERROR_READ_BASE = 0xF6010100,
	CRYPTO_OTP_ERROR_INVALID_BASE = 0xF6010200,
	CRYPTO_OTP_ERROR_INVALID_KEY = 0xF6010201,
	CRYPTO_OTP_ERROR_WRITE_BASE = 0xF6010400,
	CRYPTO_OTP_ERROR_WRITE_UUID = 0xF6010401,
	CRYPTO_ASSET_ERROR_BASE = 0xF6020000,
	CRYPTO_ASSET_ERROR_READ_BASE = 0xF6020100,
	CRYPTO_ASSET_ERROR_READ_CONTEXT = 0xF6020101,
	CRYPTO_ASSET_ERROR_READ_WORKMODEL = 0xF6020102,
	CRYPTO_ASSET_ERROR_READ_ICV_SEC_VERSION = 0xF6020103,
	CRYPTO_ASSET_ERROR_READ_OEM_SEC_VERSION = 0xF6020104,
	CRYPTO_ASSET_ERROR_READ_ICV_ARB_VERSION = 0xF6020105,
	CRYPTO_ASSET_ERROR_READ_OEM_ARB_VERSION = 0xF6020106,
	CRYPTO_ASSET_ERROR_READ_LCS = 0xF6020107,
	CRYPTO_ASSET_ERROR_READ_SECURE_BOOT = 0xF6020108,
	CRYPTO_ASSET_ERROR_READ_PROGRAM_CIPHER = 0xF6020109,
	CRYPTO_ASSET_ERROR_READ_SECURE_DEBUG = 0xF602010A,
	CRYPTO_ASSET_ERROR_READ_SECURE_DEBUG_LOCK = 0xF602010B,
	CRYPTO_ASSET_ERROR_READ_ENC_L2_LOCK = 0xF602010C,
	CRYPTO_ASSET_ERROR_READ_INVALID_BIT = 0xF602050D,
	CRYPTO_ASSET_ERROR_READ_DISABLE_CMDS = 0xF602050E,
	CRYPTO_ASSET_ERROR_READ_DISABLE_PLAIN_KOEM = 0xF602050F,
	CRYPTO_ASSET_ERROR_INVALID_CONTEXT = 0xF6020201,
	CRYPTO_ASSET_ERROR_INVALID_WORKMODEL = 0xF6020202,
	CRYPTO_ASSET_ERROR_INVALID_LCS = 0xF6020207,
	CRYPTO_ASSET_ERROR_WRITE_BASE = 0xF6020400,
	CRYPTO_ASSET_ERROR_WRITE_CONTEXT = 0xF6020401,
	CRYPTO_ASSET_ERROR_WRITE_WORKMODEL = 0xF6020402,
	CRYPTO_ASSET_ERROR_WRITE_ICV_SEC_VERSION = 0xF6020403,
	CRYPTO_ASSET_ERROR_WRITE_OEM_SEC_VERSION = 0xF6020404,
	CRYPTO_ASSET_ERROR_WRITE_ICV_ARB_VERSION = 0xF6020405,
	CRYPTO_ASSET_ERROR_WRITE_OEM_ARB_VERSION = 0xF6020406,
	CRYPTO_ASSET_ERROR_WRITE_LCS = 0xF6020407,
	CRYPTO_ASSET_ERROR_WRITE_SECURE_BOOT = 0xF6020408,
	CRYPTO_ASSET_ERROR_WRITE_PROGRAM_CIPHER = 0xF6020409,
	CRYPTO_ASSET_ERROR_WRITE_SECURE_DEBUG = 0xF602040A,
	CRYPTO_ASSET_ERROR_WRITE_DEBUG_LOCK = 0xF602040B,
	CRYPTO_ASSET_ERROR_WRITE_ENC_L2_LOCK = 0xF602040C,
	CRYPTO_ASSET_ERROR_WRITE_INVALID_BIT = 0xF602040D,
	SEC_AOR_ERROR_BASE = 0xF6030000,
	SEC_AOR_LCS_ERROR_BASE = 0xF6030100,
	SEC_AOR_LCS_ERROR_NULL_PARAM = 0xF6030101,
	SEC_AOR_LCS_ERROR_INVALID = 0xF6030102,
	CRYPTO_RSA_SIGNATURE_VERIFICATION_ALG_FAILURE = 0xF7000001,
	CRYPTO_RSA_SIGNATURE_VERIFICATION_CMP_FAILURE = 0xF7000002,
	FW_PKG_VERIFIER_CERT_MAGIC_NUM_INVALID = 0xF9000001,
	FW_PKG_VERIFIER_CERT_VERSION_INVALID = 0xF9000002,
	FW_PKG_VERIFIER_CERT_ENCRYPTION_MODE_INVALID = 0xF9000003,
	FW_PKG_VERIFIER_CERT_ENC_ALGO_INVALID = 0xF9000004,
	FW_PKG_VERIFIER_CERT_PACKAGE_TYPE_INVALID = 0xF9000005,
	FW_PKG_VERIFIER_CERT_TAG_INVALID = 0xF9000006,
	FW_PKG_VERIFIER_PAYLOAD_CHUNK_MAGIC_NUM_INVALID = 0xF9000007,
	FW_PKG_VERIFIER_PAYLOAD_CHUNK_VERSION_INVALID = 0xF9000008,
	FW_PKG_VERIFIER_IMG_HDR_MAGIC_NUM_INVALID = 0xF9000009,
	FW_PKG_VERIFIER_IMG_HDR_VERSION_INVALID = 0xF900000A,
	FW_PKG_VERIFIER_IMG_HDR_CERT_SIZE_INVALID = 0xF900000B,
	FW_PKG_VERIFIER_IMG_HDR_IMG_NUM_INVALID = 0xF900000C,
	FW_PKG_IV_TYPE_INVALID = 0xF900000D,
	FW_PKG_HDR_INVALID = 0xF900000E,
	FW_PKG_VERIFIER_PAYLOAD_CHUNK_LENGTH_INVALID = 0xF900000F,
	FW_PKG_VERIFIER_HEADER_USE_ENC_L2_INVALID = 0xF9000010,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_MW = 0xFA000101,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_VERSION = 0xFA000102,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_SIZE = 0xFA000103,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_CONTEXT = 0xFA000104,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_CUST_ID = 0xFA000105,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_PROD_ID = 0xFA000106,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_HASH_ID = 0xFA000107,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_SEC_VERSION = 0xFA000108,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_ARB_VERSION = 0xFA000109,
	CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_SIGNATURE = 0xFA00010A,
	CRYPTO_DEBUG_CERT_STATUS_NULL_POINTER = 0xFA000201,
	CRYPTO_DEBUG_CERT_STATUS_INVALID_LCS = 0xFA000202,
	CRYPTO_DEBUG_CERT_STATUS_SOC_ID_NULL = 0xFA000203,
	CRYPTO_DEBUG_CERT_STATUS_RANDOM_NULL = 0xFA000204,
	CRYPTO_DEBUG_CERT_STATUS_CA_NOT_VERIFIED = 0xFA000205,
	CRYPTO_DEBUG_CERT_STATUS_NO_CA_CERT_PRESENT = 0x5539,
	CRYPTO_DEBUG_CERT_STATUS_CA_PARTLY_VERIFIED = 0xA3E9,
	CRYPTO_DEBUG_CERT_STATUS_CA_VERIFIED = 0xB3E9,
	CRYPTO_DEBUG_CERT_ERROR_SERVICE_INVALID_CA_ID = 0xFA000401,
	CRYPTO_DEBUG_CERT_ERROR_SERVICE_INVALID_VERSION = 0xFA000402,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_ENTRY_KEY = 0xFB000101,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_MAGIC = 0xFB000102,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_VERSION = 0xFB000103,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_SIZE = 0xFB000104,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_KEY_ID = 0xFB000105,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_PROV_KEY = 0xFB000106,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_CUST_ID = 0xFB000107,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_PROD_ID = 0xFB000108,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_SEC_VERSION_ICV = 0xFB000109,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_SEC_VERSION_OEM = 0xFB00010A,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_ARB_VERSION_ICV = 0xFB00010B,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_ARB_VERSION_OEM = 0xFB00010C,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_SEC_BOOT_FLAG = 0xFB00010D,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_PRGM_CIPHER_FLAG = 0xFB00010E,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_SEC_DEBUG_FLAG = 0xFB00010F,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_SD_LOCK_FLAG = 0xFB000110,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_WORK_MODEL = 0xFB000111,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_CONTEXT = 0xFB000112,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_LCS = 0xFB000113,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_TAG = 0xFB000114,
	CRYPTO_CONFIG_CERT_ERROR_INVALID_NUMBER_OF_ENTRIES = 0xFB000115,
	CRYPTO_CONFIG_CERT_ERROR_PROV_LCS_NOT_TEST = 0xFB000201,
	CRYPTO_CONFIG_CERT_ERROR_PROV_LCS_NOT_OEM = 0xFB000202,
	CRYPTO_CONFIG_CERT_ERROR_PROV_NO_CUST_OR_PROD_ID = 0xFB000203,
	CRYPTO_CONFIG_CERT_ERROR_PROV_HBK0_ALREADY_SET = 0xFB000204,
	CRYPTO_CONFIG_CERT_ERROR_PROV_HBK1_ALREADY_SET = 0xFB000205,
	CRYPTO_CONFIG_CERT_ERROR_PROV_KCEICV_ALREADY_SET = 0xFB000206,
	CRYPTO_CONFIG_CERT_ERROR_PROV_KPICV_ALREADY_SET = 0xFB000207,
	CRYPTO_CONFIG_CERT_ERROR_PROV_KCE_ALREADY_SET = 0xFB000208,
	CRYPTO_CONFIG_CERT_ERROR_PROV_1EN_CA_ALREADY_SET = 0xFB000209,
	CRYPTO_CONFIG_CERT_ERROR_PROV_2EN_CA_ALREADY_SET = 0xFB00020A,
	CRYPTO_CONFIG_CERT_ERROR_PROV_TEST_2_OEM_ILLEGAL = 0xFB00020B,
	CRYPTO_CONFIG_CERT_ERROR_PROV_TEST_2_USER_ILLEGAL = 0xFB00020C,
	CRYPTO_CONFIG_CERT_ERROR_PROV_TEST_2_RMA_ILLEGAL = 0xFB00020D,
	CRYPTO_CONFIG_CERT_ERROR_PROV_OEM_2_USER_ILLEGAL = 0xFB00020E,
	CRYPTO_CONFIG_CERT_ERROR_PROV_HSUPCA_ALREADY_SET = 0xFB00020F,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_HBK = 0xFB000401,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_KCE = 0xFB000402,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_KP = 0xFB000403,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_1E_CA = 0xFB000404,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_2E_CA = 0xFB000405,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_CUST_ID = 0xFB000406,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_PROD_ID = 0xFB000407,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_SEC_VER = 0xFB000408,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_ARB_VER = 0xFB000409,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_CONTEXT = 0xFB00040A,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_LCS = 0xFB00040B,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_SB_OEM = 0xFB00040C,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_CIPHER_OEM = 0xFB00040D,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_SEC_DEBUG = 0xFB00040E,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_DEBUG_LOCK = 0xFB00040F,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_WORK_MODEL = 0xFB000410,
	CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_HSUPCA = 0xFB000411
};

typedef struct {
	const char *name;
	uint32_t value;
} enum_tuple_t;

#define ENUM_TUPLE(__num)                                  \
	{                                                  \
		.name = #__num, .value = (uint32_t)(__num) \
	}

#define ENUM_TUPLE_END                   \
	{                                \
		.name = NULL, .value = 0 \
	}

const enum_tuple_t cmd_enum_tuples[] = {
	ENUM_TUPLE(CMD_NONE),
	ENUM_TUPLE(CMD_GET_CHIP_VERSION),
	ENUM_TUPLE(CMD_GET_SOC_INFO),
	ENUM_TUPLE(CMD_LOAD_FW_PKG),
	ENUM_TUPLE(CMD_LOAD_ASSET_PKG),
	ENUM_TUPLE(CMD_LOAD_SECURE_DEBUG_PKG),
	ENUM_TUPLE(CMD_ERASE_SECURE_DEBUG_PKG),
	ENUM_TUPLE(CMD_LOAD_SRAM),
	ENUM_TUPLE(CMD_RUN_TEST_MODE),
	ENUM_TUPLE(CMD_GENERATE_MASTER_SECRET_AND_UUID),
	ENUM_TUPLE_END /* End of list marker. */
};

const enum_tuple_t sub_cmd_load_fw_pkg_enum_tuples[] = {
	ENUM_TUPLE(SUB_CMD_LOAD_FW_PKG_HDR),
	ENUM_TUPLE(SUB_CMD_LOAD_FW_PKG_PAYLOAD_CHUNK),
	ENUM_TUPLE_END /* End of list marker. */
};

const enum_tuple_t sub_cmd_load_sram_enum_tuples[] = {
	ENUM_TUPLE(SUB_CMD_LOAD_SRAM_FILE_SIZE),
	ENUM_TUPLE(SUB_CMD_LOAD_SRAM_IMG_DATA),
	ENUM_TUPLE_END /* End of list marker. */
};

const enum_tuple_t resp_code_enum_tuples[] = {
	ENUM_TUPLE(RESP_OK),
	ENUM_TUPLE(RESP_GET_CHIP_VERSION_SUCCESS),
	ENUM_TUPLE(RESP_GET_SOC_INFO_SUCCESS),
	ENUM_TUPLE(RESP_LOAD_ASSET_PKG_SUCCESS),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_VERIFIED_IMGS_COMPLETED),
	ENUM_TUPLE(RESP_LOAD_SEC_DEBUG_PKG_SUCCESS),
	ENUM_TUPLE(RESP_ERASE_SEC_DEBUG_PKG_SUCCESS),
	ENUM_TUPLE(RESP_GENERATE_MASTER_SECRET_AND_UUID_SUCCESS),
	ENUM_TUPLE(RESP_INVALID_CMD),
	ENUM_TUPLE(RESP_INVALID_I3C_CMD),
	ENUM_TUPLE(RESP_GET_SOC_INFO_FAILED),
	ENUM_TUPLE(RESP_LOAD_ASSET_PKG_FAILED),
	ENUM_TUPLE(RESP_LOAD_ASSET_PKG_CMD_NOT_ALLOWED_FOR_CURRENT_LCS),
	ENUM_TUPLE(RESP_LOAD_ASSET_PKG_INVALID_ASSET_SIZE),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_INVALID_CMD),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_INVALID_SUB_CMD),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_INVALID_CERT_SIZE),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_HDR_VERIFY_FAILED),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_PAYLOAD_CHUNK_VERIFY_FAILED),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_SET_IV_FAILED),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_DECRYPT_PAYLOAD_FAILED),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_VERIFY_IMG_HDR_FAILED),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_VERIFY_SB_PKG_FAILED),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_STORE_SB_PKG_FAILED),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_STORE_IMG_FAILED),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_VERIFY_IMG_FAILED),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_INVALID_CHUNK_SIZE),
	ENUM_TUPLE(RESP_LOAD_FW_PKG_LOCK_L2_ENC_CHECK_FAILED),
	ENUM_TUPLE(RESP_LOAD_SRAM_SIZE_0),
	ENUM_TUPLE(RESP_LOAD_SRAM_SIZE_TOO_BIG),
	ENUM_TUPLE(RESP_LOAD_SRAM_INVALID_SUB_CMD),
	ENUM_TUPLE(RESP_LOAD_SRAM_CMD_NOT_ALLOWED_FOR_CURRENT_LCS),
	ENUM_TUPLE(RESP_LOAD_SRAM_GOT_DATA_MORE_THAN_EXPECTED),
	ENUM_TUPLE(RESP_LOAD_SRAM_INVALID_CMD),
	ENUM_TUPLE(RESP_RUN_TEST_FAILED),
	ENUM_TUPLE(RESP_RUN_TEST_CMD_NOT_ALLOWED_FOR_CURRENT_LCS),
	ENUM_TUPLE(RESP_LOAD_SEC_DEBUG_PKG_FAILED),
	ENUM_TUPLE(RESP_LOAD_SEC_DEBUG_PKG_STORE_FAILED),
	ENUM_TUPLE(RESP_LOAD_SEC_DEBUG_PKG_NOT_ALLOWED_FOR_CURRENT_LCS),
	ENUM_TUPLE(RESP_LOAD_SEC_DEBUG_PKG_INVALID_SIZE),
	ENUM_TUPLE(RESP_ERASE_SEC_DEBUG_PKG_WIPE_FAILED),
	ENUM_TUPLE(RESP_GENERATE_MASTER_SECRET_ERROR),
	ENUM_TUPLE(RESP_GENERATE_UUID_ERROR),
	ENUM_TUPLE(RESP_GENERATE_UUID_ALREADY_GENERATED),
	ENUM_TUPLE(RESP_GENERATE_MASTER_SECRETS_NOT_ALLOWED_LCS),
	ENUM_TUPLE_END /* End of list marker. */
};

const enum_tuple_t error_code_enum_tuples[] = {
	ENUM_TUPLE(SB_OK),
	ENUM_TUPLE(RRAM_ERROR_ADDRESS_RANGE),
	ENUM_TUPLE(RRAM_ERROR_ADDRESS_ALIGN),
	ENUM_TUPLE(RRAM_ERROR_DATA_SIZE),
	ENUM_TUPLE(RRAM_ERROR_TIMEOUT),
	ENUM_TUPLE(RRAM_ERROR_WR_ERROR),
	ENUM_TUPLE(RRAM_ERROR_UNSUPPORTED_API),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_MAGIC_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_VERSION_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_SIZE_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_CONTEXT_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_CUST_ID_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_PROD_ID_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_SEC_VERSION_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_ARB_VERSION_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_LENGTH_INVALID),
	ENUM_TUPLE(
		CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_LOAD_VERIF_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_HASH_INVALID),
	ENUM_TUPLE(
		CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_FLASH_ADDR_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_METADATA_LOAD_ADDR_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_CONTENT_VERIFICATION_FAILED),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_MAGIC_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_VERSION_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_SIZE_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_CONTEXT_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_CUST_ID_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_PROD_ID_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_SEC_VERSION_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_ARB_VERSION_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_HASH_ID_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_HASH_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_ERROR_KEY_PUBLIC_KEY_INVALID),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_STATUS_KEY_PARTLY_VERIFIED_LCS),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_STATUS_KEY_PARTLY_VERIFIED_NON_SECURE),
	ENUM_TUPLE(CRYPTO_IMAGES_CERT_STATUS_CONTENT_PARTLY_VERIFIED),
	ENUM_TUPLE(E_KSSL_ONGOING),
	ENUM_TUPLE(E_KSSL_SUCCESS),
	ENUM_TUPLE(E_KSSL_ABORTED),
	ENUM_TUPLE(E_KSSL_ERR_HW_BUSY),
	ENUM_TUPLE(E_KSSL_ERR_NOT_PENDING),
	ENUM_TUPLE(E_KSSL_ERR_PARAMETERS),
	ENUM_TUPLE(E_KSSL_ERR_SEED_NOT_LOADED),
	ENUM_TUPLE(E_KSSL_ERR_NOT_SUPPORTED),
	ENUM_TUPLE(E_KSSL_ERR_INVALID_KEY),
	ENUM_TUPLE(E_KSSL_ERR_WRONG_AUTH_TAG),
	ENUM_TUPLE(E_KSSL_ERR_WRONG_SIGNATURE),
	ENUM_TUPLE(E_KSSL_ERR_POINT_CHECK),
	ENUM_TUPLE(E_KSSL_ERR_NOT_AVAILABLE),
	ENUM_TUPLE(E_KSSL_ERR_HW_FAILURE),
	ENUM_TUPLE(E_KSSL_ERR_BAD_SEQUENCE),
	ENUM_TUPLE(E_KSSL_ERR_INVALID_EXEC_CTX),
	ENUM_TUPLE(E_KSSL_ERR_DRBG_CONTEXT),
	ENUM_TUPLE(E_KSSL_ERR_POINT_AT_INFINITY),
	ENUM_TUPLE(E_KSSL_ERR_AEAD_WRONG_TAG),
	ENUM_TUPLE(E_KSSL_ERR_BAD_STATE),
	ENUM_TUPLE(E_KSSL_ERR_RESTRICTION),
	ENUM_TUPLE(E_KSSL_ERR_MISSING_KEY),
	ENUM_TUPLE(E_KSSL_ERR_DBG_OBJ_REVOKED),
	ENUM_TUPLE(E_KSSL_ERR_INVALID_FORMAT),
	ENUM_TUPLE(E_KSSL_ERR_OTP),
	ENUM_TUPLE(CRYPTO_KEY_GEN_INVALID_KEY_ID_ERROR),
	ENUM_TUPLE(CRYPTO_KEY_GEN_NULL_POINTER_ERROR),
	ENUM_TUPLE(CRYPTO_KEY_GEN_INVALID_CONFIG_CERT_ERROR),
	ENUM_TUPLE(CRYPTO_KEY_GEN_INVALID_FW_PACK_ERROR),
	ENUM_TUPLE(WDT_ERROR),
	ENUM_TUPLE(ECC_SRAM_ERROR),
	ENUM_TUPLE(EFLASH_STR_ERROR),
	ENUM_TUPLE(VWARN_ERROR),
	ENUM_TUPLE(CRYPTO_COMMON_ERROR_BASE),
	ENUM_TUPLE(CRYPTO_COMMON_ERROR_INVALID_SEC_VERSION),
	ENUM_TUPLE(CRYPTO_COMMON_ERROR_INVALID_ARB_VERSION),
	ENUM_TUPLE(CRYPTO_UTIL_ERROR_MEMCPY_DEST_ADDR_IS_NULL),
	ENUM_TUPLE(CRYPTO_UTIL_ERROR_MEMCPY_DEST_SIZE_INVALID),
	ENUM_TUPLE(CRYPTO_UTIL_ERROR_MEMCPY_SRC_ADDR_IS_NULL),
	ENUM_TUPLE(CRYPTO_UTIL_ERROR_MEMCPY_SRC_SIZE_INVALID),
	ENUM_TUPLE(CRYPTO_UTIL_ERROR_MEMCPY_MEM_OVERLAP),
	ENUM_TUPLE(CRYPTO_UTIL_ERROR_MEMCPY_RAND_ERROR),
	ENUM_TUPLE(CRYPTO_UTIL_ERROR_MEMCPY_SEC_CHECK_VAL_INVALID),
	ENUM_TUPLE(CRYPTO_UTIL_ERROR_MEMCMP_NOT_EQUAL),
	ENUM_TUPLE(CRYPTO_UTIL_ERROR_MEMCMP_INVALID_PARAM),
	ENUM_TUPLE(CRYPTO_OTP_ERROR_BASE),
	ENUM_TUPLE(CRYPTO_OTP_ERROR_READ_BASE),
	ENUM_TUPLE(CRYPTO_OTP_ERROR_INVALID_BASE),
	ENUM_TUPLE(CRYPTO_OTP_ERROR_INVALID_KEY),
	ENUM_TUPLE(CRYPTO_OTP_ERROR_WRITE_BASE),
	ENUM_TUPLE(CRYPTO_OTP_ERROR_WRITE_UUID),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_BASE),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_BASE),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_CONTEXT),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_WORKMODEL),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_ICV_SEC_VERSION),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_OEM_SEC_VERSION),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_ICV_ARB_VERSION),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_OEM_ARB_VERSION),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_LCS),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_SECURE_BOOT),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_PROGRAM_CIPHER),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_SECURE_DEBUG),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_SECURE_DEBUG_LOCK),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_ENC_L2_LOCK),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_INVALID_BIT),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_DISABLE_CMDS),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_READ_DISABLE_PLAIN_KOEM),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_INVALID_CONTEXT),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_INVALID_WORKMODEL),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_INVALID_LCS),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_BASE),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_CONTEXT),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_WORKMODEL),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_ICV_SEC_VERSION),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_OEM_SEC_VERSION),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_ICV_ARB_VERSION),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_OEM_ARB_VERSION),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_LCS),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_SECURE_BOOT),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_PROGRAM_CIPHER),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_SECURE_DEBUG),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_DEBUG_LOCK),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_ENC_L2_LOCK),
	ENUM_TUPLE(CRYPTO_ASSET_ERROR_WRITE_INVALID_BIT),
	ENUM_TUPLE(SEC_AOR_ERROR_BASE),
	ENUM_TUPLE(SEC_AOR_LCS_ERROR_BASE),
	ENUM_TUPLE(SEC_AOR_LCS_ERROR_NULL_PARAM),
	ENUM_TUPLE(SEC_AOR_LCS_ERROR_INVALID),
	ENUM_TUPLE(CRYPTO_RSA_SIGNATURE_VERIFICATION_ALG_FAILURE),
	ENUM_TUPLE(CRYPTO_RSA_SIGNATURE_VERIFICATION_CMP_FAILURE),
	ENUM_TUPLE(FW_PKG_VERIFIER_CERT_MAGIC_NUM_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_CERT_VERSION_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_CERT_ENCRYPTION_MODE_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_CERT_ENC_ALGO_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_CERT_PACKAGE_TYPE_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_CERT_TAG_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_PAYLOAD_CHUNK_MAGIC_NUM_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_PAYLOAD_CHUNK_VERSION_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_IMG_HDR_MAGIC_NUM_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_IMG_HDR_VERSION_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_IMG_HDR_CERT_SIZE_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_IMG_HDR_IMG_NUM_INVALID),
	ENUM_TUPLE(FW_PKG_IV_TYPE_INVALID),
	ENUM_TUPLE(FW_PKG_HDR_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_PAYLOAD_CHUNK_LENGTH_INVALID),
	ENUM_TUPLE(FW_PKG_VERIFIER_HEADER_USE_ENC_L2_INVALID),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_MW),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_VERSION),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_SIZE),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_CONTEXT),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_CUST_ID),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_PROD_ID),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_HASH_ID),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_SEC_VERSION),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_ARB_VERSION),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_CA_INVALID_SIGNATURE),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_STATUS_NULL_POINTER),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_STATUS_INVALID_LCS),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_STATUS_SOC_ID_NULL),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_STATUS_RANDOM_NULL),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_STATUS_CA_NOT_VERIFIED),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_STATUS_NO_CA_CERT_PRESENT),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_STATUS_CA_PARTLY_VERIFIED),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_STATUS_CA_VERIFIED),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_SERVICE_INVALID_CA_ID),
	ENUM_TUPLE(CRYPTO_DEBUG_CERT_ERROR_SERVICE_INVALID_VERSION),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_ENTRY_KEY),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_MAGIC),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_VERSION),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_SIZE),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_KEY_ID),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_PROV_KEY),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_CUST_ID),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_PROD_ID),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_SEC_VERSION_ICV),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_SEC_VERSION_OEM),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_ARB_VERSION_ICV),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_ARB_VERSION_OEM),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_SEC_BOOT_FLAG),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_PRGM_CIPHER_FLAG),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_SEC_DEBUG_FLAG),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_SD_LOCK_FLAG),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_WORK_MODEL),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_CONTEXT),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_LCS),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_TAG),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_INVALID_NUMBER_OF_ENTRIES),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_LCS_NOT_TEST),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_LCS_NOT_OEM),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_NO_CUST_OR_PROD_ID),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_HBK0_ALREADY_SET),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_HBK1_ALREADY_SET),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_KCEICV_ALREADY_SET),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_KPICV_ALREADY_SET),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_KCE_ALREADY_SET),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_1EN_CA_ALREADY_SET),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_2EN_CA_ALREADY_SET),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_TEST_2_OEM_ILLEGAL),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_TEST_2_USER_ILLEGAL),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_TEST_2_RMA_ILLEGAL),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_OEM_2_USER_ILLEGAL),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PROV_HSUPCA_ALREADY_SET),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_HBK),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_KCE),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_KP),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_1E_CA),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_2E_CA),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_CUST_ID),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_PROD_ID),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_SEC_VER),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_ARB_VER),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_CONTEXT),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_LCS),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_SB_OEM),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_CIPHER_OEM),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_SEC_DEBUG),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_DEBUG_LOCK),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_WORK_MODEL),
	ENUM_TUPLE(CRYPTO_CONFIG_CERT_ERROR_PARSING_DOUBLE_HSUPCA),
	ENUM_TUPLE_END /* End of list marker. */
};

/*! Command header structure typedef. */
typedef struct {
	union {
		struct {
			/*! Command code. */
			uint8_t cmd;
			/*! Sub-command code. */
			uint8_t sub_cmd;
			/*! Response code. */
			uint16_t resp;
		};
		uint32_t all;
	};
} cmd_hdr_t;

#define MAKE_CMD_HDR(c, sc, r)                           \
	(cmd_hdr_t)                                      \
	{                                                \
		.cmd = (c), .sub_cmd = (sc), .resp = (r) \
	}

/*! Response header structure typedef. */
typedef struct {
	/*! Command header. */
	cmd_hdr_t cmd_hdr;
	/*! Error code. */
	uint32_t err_code;
} resp_t;

#define MAKE_RSP_HDR(ch, ec)                      \
	(resp_t)                                  \
	{                                         \
		.cmd_hdr = (ch), .err_code = (ec) \
	}

#define CMD_MODE_READY_RSP_HDR                            \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_NONE, SUB_CMD_NONE, \
				  RESP_CMD_MODE_READY),   \
		     SB_OK)

#define CMD_MODE_READY_EFLASH_STR_ERR_RSP_HDR             \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_NONE, SUB_CMD_NONE, \
				  RESP_CMD_MODE_READY),   \
		     EFLASH_STR_ERROR)

#define CMD_GET_CHIP_VERSION_RSP_HDR                                  \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_GET_CHIP_VERSION, SUB_CMD_NONE, \
				  RESP_GET_CHIP_VERSION_SUCCESS),     \
		     SB_OK)

#define CMD_GET_SOC_INFO_RSP_HDR                                  \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_GET_SOC_INFO, SUB_CMD_NONE, \
				  RESP_GET_SOC_INFO_SUCCESS),     \
		     SB_OK)

#define CMD_GENERATE_MASTER_SECRET_AND_UUID_RSP_HDR                         \
	MAKE_RSP_HDR(                                                       \
		MAKE_CMD_HDR(CMD_GENERATE_MASTER_SECRET_AND_UUID,           \
			     SUB_CMD_NONE,                                  \
			     RESP_GENERATE_MASTER_SECRET_AND_UUID_SUCCESS), \
		SB_OK)

#define CMD_LOAD_ASSET_PKG_RSP_HDR                                  \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_LOAD_ASSET_PKG, SUB_CMD_NONE, \
				  RESP_LOAD_ASSET_PKG_SUCCESS),     \
		     SB_OK)

#define CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_RSP_HDR                             \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_LOAD_FW_PKG,                             \
				  SUB_CMD_LOAD_FW_PKG_PAYLOAD_CHUNK, RESP_OK), \
		     SB_OK)

#define CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_COMPLETE_RSP_HDR                  \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_LOAD_FW_PKG,                           \
				  SUB_CMD_LOAD_FW_PKG_PAYLOAD_CHUNK,         \
				  RESP_LOAD_FW_PKG_VERIFIED_IMGS_COMPLETED), \
		     SB_OK)

#define CMD_LOAD_SECURE_DEBUG_PKG_RSP_HDR                                  \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_LOAD_SECURE_DEBUG_PKG, SUB_CMD_NONE, \
				  RESP_LOAD_SEC_DEBUG_PKG_SUCCESS),        \
		     SB_OK)

#define CMD_ERASE_SECURE_DEBUG_PKG_RSP_HDR                                  \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_ERASE_SECURE_DEBUG_PKG, SUB_CMD_NONE, \
				  RESP_ERASE_SEC_DEBUG_PKG_SUCCESS),        \
		     SB_OK)

#define CMD_LOAD_SRAM_RSP_HDR                                                \
	MAKE_RSP_HDR(MAKE_CMD_HDR(CMD_LOAD_SRAM, SUB_CMD_LOAD_SRAM_IMG_DATA, \
				  RESP_OK),                                  \
		     SB_OK)

#define COMPARE_RSP(act_rsp, exp_rsp) memcmp(act_rsp, exp_rsp, sizeof(resp_t))

typedef struct {
	enum_tuple_t cmd;
	enum_tuple_t sub_cmd;
	enum_tuple_t resp_code;
	enum_tuple_t error_code;
} response_enum_tuple_t;

static void log_error_response(const char *func, resp_t *expected,
			       resp_t *received);
static int gen_secrets(struct qmrom_handle *handle);
static int load_asset_pkg(struct qmrom_handle *handle,
			  const struct firmware *asset_pkg);
static int load_fw_pkg(struct qmrom_handle *handle,
		       const struct firmware *fw_pkg);
static int load_secure_debug_pkg(struct qmrom_handle *handle,
				 const struct firmware *dbg_pkg);
static int erase_secure_debug_pkg(struct qmrom_handle *handle);
static int run_test_mode(struct qmrom_handle *handle);
static int load_sram_fw(struct qmrom_handle *handle,
			const struct firmware *sram_fw);

int qm358xx_rom_probe_device(struct qmrom_handle *handle)
{
	int rc;

	if (handle->spi_speed == 0)
		qmrom_spi_set_freq(DEFAULT_SPI_CLOCKRATE);
	else
		qmrom_spi_set_freq(handle->spi_speed);

	/* On QPF51xx, initial message can also indicate eFlash storage error */
	if ((COMPARE_RSP(&handle->sstc->payload[0], &CMD_MODE_READY_RSP_HDR) !=
	     0) &&
	    (COMPARE_RSP(&handle->sstc->payload[0],
			 &CMD_MODE_READY_EFLASH_STR_ERR_RSP_HDR) != 0)) {
		log_error_response(__func__, &CMD_MODE_READY_RSP_HDR,
				   (resp_t *)&handle->sstc->payload[0]);
		return SPI_PROTO_WRONG_RESP;
	}

	LOG_DBG("%s: sending CMD_GET_CHIP_VERSION command\n", __func__);
	rc = qmrom_write_cmd32(
		handle,
		MAKE_CMD_HDR(CMD_GET_CHIP_VERSION, SUB_CMD_NONE, RESP_NONE).all);
	qmrom_poll_cmd_resp(handle);
	if (COMPARE_RSP(&handle->sstc->payload[0],
			&CMD_GET_CHIP_VERSION_RSP_HDR) != 0) {
		log_error_response(__func__, &CMD_GET_CHIP_VERSION_RSP_HDR,
				   (resp_t *)&handle->sstc->payload[0]);
		return SPI_PROTO_WRONG_RESP;
	}

	handle->chip_rev =
		le16toh(SSTC2UINT16(handle,
				    CHIP_VERSION_CHIP_REV_PAYLOAD_OFFSET)) >>
		8;
	handle->device_version = le16toh(
		SSTC2UINT16(handle, CHIP_VERSION_DEV_REV_PAYLOAD_OFFSET));
	switch (handle->device_version) {
	case DEVICE_VER_QM358XX:
		handle->dev_gen = DEVICE_GEN_QM358XX;
		break;
	case DEVICE_VER_QPF51XX:
		handle->dev_gen = DEVICE_GEN_QPF51XX;
		break;
	default:
		LOG_ERR("%s: wrong device version %#x\n", __func__,
			handle->device_version);
		handle->dev_gen = DEVICE_GEN_UNKNOWN;
		return -1;
	}

	rc = qmrom_wait_ready(handle);
	if (rc) {
		LOG_ERR("%s: hmm something went wrong!!!\n", __func__);
		return rc;
	}

	rc = qmrom_write_cmd32(
		handle,
		MAKE_CMD_HDR(CMD_GET_SOC_INFO, SUB_CMD_NONE, RESP_NONE).all);
	qmrom_poll_cmd_resp(handle);
	if (COMPARE_RSP(&handle->sstc->payload[0], &CMD_GET_SOC_INFO_RSP_HDR) !=
	    0) {
		log_error_response(__func__, &CMD_GET_SOC_INFO_RSP_HDR,
				   (resp_t *)&handle->sstc->payload[0]);
		return SPI_PROTO_WRONG_RESP;
	}

	/* skip the resp header bytes */
	memcpy(&handle->qm358xx_soc_info,
	       &handle->sstc->payload[sizeof(resp_t)],
	       min(sizeof(handle->qm358xx_soc_info),
		   handle->sstc->len - sizeof(resp_t)));

	/* Set rom ops */
	handle->rom_ops.gen_secrets = gen_secrets;
	handle->rom_ops.load_asset_pkg = load_asset_pkg;
	handle->rom_ops.load_fw_pkg = load_fw_pkg;
	handle->rom_ops.load_secure_dbg_pkg = load_secure_debug_pkg;
	handle->rom_ops.erase_secure_dbg_pkg = erase_secure_debug_pkg;
	handle->rom_ops.load_sram_fw = load_sram_fw;
	handle->rom_ops.run_test_mode = run_test_mode;

	return 0;
}

#ifdef CONFIG_FLASHING_STATS
static uint64_t total_time_ns;
static uint32_t total_bytes, total_chunks;
static uint32_t max_write_time_ns, min_write_time_ns = ~0U;

static void update_write_stats(qmrom_time start_time, uint32_t chunk_size)
{
	uint64_t elapsed_time_ns =
		qmrom_time_to_ns(qmrom_time_sub(qmrom_time_get(), start_time));

	total_time_ns += elapsed_time_ns;
	total_bytes += CHUNK_SIZE;
	total_chunks++;

	if (elapsed_time_ns > max_write_time_ns)
		max_write_time_ns = elapsed_time_ns;
	if (elapsed_time_ns < min_write_time_ns)
		min_write_time_ns = elapsed_time_ns;
}

static void dump_stats(void)
{
	LOG_WARN("Flashing time stats: %u bytes over %" PRIu64
		 " us (max chunk size %u, "
		 "%u chunks, write timings: mean %" PRIu64
		 " us, min %u us, max %u us)\n",
		 total_bytes, qmrom_time_div(total_time_ns, 1000), CHUNK_SIZE,
		 total_chunks,
		 qmrom_time_div(total_time_ns, total_chunks * 1000),
		 min_write_time_ns / 1000, max_write_time_ns / 1000);

	/* Reset stats */
	total_time_ns = 0;
	total_bytes = 0;
	total_chunks = 0;
	max_write_time_ns = 0;
	min_write_time_ns = ~0U;
}
#endif

static int gen_secrets(struct qmrom_handle *handle)
{
	int rc;

	LOG_DBG("%s: starting...\n", __func__);

	rc = qmrom_wait_ready(handle);
	if (rc)
		return rc;

	LOG_DBG("%s: sending CMD_GENERATE_MASTER_SECRET_AND_UUID command\n",
		__func__);
	rc = qmrom_write_cmd32(handle,
			       MAKE_CMD_HDR(CMD_GENERATE_MASTER_SECRET_AND_UUID,
					    SUB_CMD_NONE, RESP_NONE)
				       .all);
	qmrom_poll_cmd_resp(handle);
	if (COMPARE_RSP(&handle->sstc->payload[0],
			&CMD_GENERATE_MASTER_SECRET_AND_UUID_RSP_HDR) != 0) {
		log_error_response(__func__,
				   &CMD_GENERATE_MASTER_SECRET_AND_UUID_RSP_HDR,
				   (resp_t *)&handle->sstc->payload[0]);
		return SPI_PROTO_WRONG_RESP;
	}

	return 0;
}

bool verify_fw_pkg_img_chunk(const char *data)
{
	fw_pkg_payload_chunk_hdr_t *hdr = (fw_pkg_payload_chunk_hdr_t *)data;
	if ((hdr->magic != CRYPTO_FIRMWARE_CHUNK_MAGIC_VALUE) ||
	    (hdr->version != CRYPTO_FIRMWARE_CHUNK_VERSION) ||
	    (hdr->length > CHUNK_PAYLOAD_MAX_SIZE)) {
		return false;
	}
	LOG_DBG("%s, image chunk: hdr->magic: %4s hdr->version: %#x hdr->length: %#x\n",
		__func__, (char *)&hdr->magic, hdr->version, hdr->length);

	return true;
}

static int load_fw_pkg(struct qmrom_handle *handle,
		       const struct firmware *fw_pkg)
{
	int rc, init_tx = 0;
	size_t sent = 0;
	const char *bin_data = (const char *)fw_pkg->data;
	char *img_chunk = NULL;
	bool bin_data_pre_chunked = false;
#ifdef CONFIG_FLASHING_STATS
	qmrom_time start_time;
#endif
	LOG_DBG("%s: starting...\n", __func__);

	if (((uint32_t) * (uint32_t *)bin_data !=
	     CRYPTO_FIRMWARE_PACK_MAGIC_VALUE) ||
	    (fw_pkg->size <
	     (CRYPTO_FIRMWARE_PACK_HEADER_SIZE +
	      CRYPTO_FIRMWARE_IMAGE_CERT_SIZE + CRYPTO_IMAGES_CERT_PKG_SIZE +
	      CRYPTO_FIRMWARE_CHUNK_MIN_SIZE))) {
		LOG_ERR("%s: Invalid firmware package.\n", __func__);
		rc = -EINVAL;
		goto exit;
	}

	rc = qmrom_wait_ready(handle);
	if (rc)
		goto exit;

	LOG_DBG("%s: sending CMD_LOAD_FW_PKG:HEADER command\n", __func__);
	rc = qmrom_write_size_cmd32(handle,
				    MAKE_CMD_HDR(CMD_LOAD_FW_PKG,
						 SUB_CMD_LOAD_FW_PKG_HDR,
						 RESP_NONE)
					    .all,
				    CRYPTO_FIRMWARE_PACK_HEADER_SIZE, bin_data);
	qmrom_poll_cmd_resp(handle);
	if (COMPARE_RSP(&handle->sstc->payload[0],
			&CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_RSP_HDR) != 0) {
		log_error_response(__func__,
				   &CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_RSP_HDR,
				   (resp_t *)&handle->sstc->payload[0]);
		rc = SPI_PROTO_WRONG_RESP;
		goto exit;
	}

	sent += CRYPTO_FIRMWARE_PACK_HEADER_SIZE;
	bin_data += CRYPTO_FIRMWARE_PACK_HEADER_SIZE;

	qmrom_alloc(img_chunk, CHUNK_SIZE);
	if (!img_chunk) {
		LOG_ERR("Image chunk buffer allocation failure\n");
		rc = -1;
		goto exit;
	}
	((fw_pkg_payload_chunk_hdr_t *)img_chunk)->magic =
		CRYPTO_FIRMWARE_CHUNK_MAGIC_VALUE;
	((fw_pkg_payload_chunk_hdr_t *)img_chunk)->version =
		CRYPTO_FIRMWARE_CHUNK_VERSION;

	while (sent < fw_pkg->size) {
		uint32_t tx_bytes = 0;
		const char *payload = NULL;
		if (verify_fw_pkg_img_chunk(bin_data)) {
			bin_data_pre_chunked = true;
			tx_bytes =
				((fw_pkg_payload_chunk_hdr_t *)bin_data)->length;
			if (tx_bytes > CHUNK_SIZE) {
				LOG_ERR("Invalid payload chunk size\n");
				rc = -1;
				goto exit;
			}
			payload = bin_data;
		} else {
			if (bin_data_pre_chunked) {
				LOG_ERR("Invalid pre-chunked package\n");
				rc = -1;
				goto exit;
			}
			tx_bytes = fw_pkg->size - sent;
			if (tx_bytes > CHUNK_PAYLOAD_MAX_SIZE)
				tx_bytes = CHUNK_PAYLOAD_MAX_SIZE;
			((fw_pkg_payload_chunk_hdr_t *)img_chunk)->length =
				tx_bytes;
			memcpy(&img_chunk[CRYPTO_FIRMWARE_CHUNK_HDR_SIZE],
			       bin_data, tx_bytes);
			payload = img_chunk;
		}

		LOG_DBG("%s: sending CMD_LOAD_FW_PKG:PAYLOAD_CHUNK command with %" PRIu32
			" bytes\n",
			__func__, tx_bytes);
#ifdef CONFIG_FLASHING_STATS
		start_time = qmrom_time_get();
#endif
		rc = qmrom_write_size_cmd32(
			handle,
			MAKE_CMD_HDR(CMD_LOAD_FW_PKG,
				     SUB_CMD_LOAD_FW_PKG_PAYLOAD_CHUNK,
				     RESP_NONE)
				.all,
			CRYPTO_FIRMWARE_CHUNK_HDR_SIZE + tx_bytes, payload);
		if (rc)
			goto exit;
		sent += tx_bytes;
		bin_data += tx_bytes;
		if (bin_data_pre_chunked) {
			sent += CRYPTO_FIRMWARE_CHUNK_HDR_SIZE;
			bin_data += CRYPTO_FIRMWARE_CHUNK_HDR_SIZE;
		}
		if (!init_tx) {
			init_tx = 1;
			continue;
		}
		qmrom_poll_cmd_resp(handle);
#ifdef CONFIG_FLASHING_STATS
		update_write_stats(start_time, tx_bytes);
#endif
		if (COMPARE_RSP(&handle->sstc->payload[0],
				&CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_RSP_HDR) ==
		    0) {
			continue;
		} else if (COMPARE_RSP(
				   &handle->sstc->payload[0],
				   &CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_COMPLETE_RSP_HDR) ==
			   0) {
			LOG_INFO("%s: flashing done, quitting now\n", __func__);
			rc = 0;
			goto exit;
		} else {
			log_error_response(
				__func__,
				(sent < fw_pkg->size) ?
					&CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_RSP_HDR :
					&CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_COMPLETE_RSP_HDR,
				(resp_t *)&handle->sstc->payload[0]);
			rc = SPI_PROTO_WRONG_RESP;
			goto exit;
		}
	}
	qmrom_poll_cmd_resp(handle);
	if (COMPARE_RSP(&handle->sstc->payload[0],
			&CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_COMPLETE_RSP_HDR) !=
	    0) {
		log_error_response(
			__func__,
			&CMD_LOAD_FW_PKG_LOAD_PAYLOAD_CHUNK_COMPLETE_RSP_HDR,
			(resp_t *)&handle->sstc->payload[0]);
		rc = SPI_PROTO_WRONG_RESP;
	}
exit:
#ifdef CONFIG_FLASHING_STATS
	dump_stats();
#endif
	if (img_chunk)
		qmrom_free(img_chunk);

	return rc;
}

static int load_asset_pkg(struct qmrom_handle *handle,
			  const struct firmware *asset_pkg)
{
	int rc;

	LOG_DBG("%s: starting...\n", __func__);
	rc = qmrom_wait_ready(handle);
	if (rc)
		return rc;

	LOG_DBG("%s: sending CMD_LOAD_ASSET_PKG command\n", __func__);
	rc = qmrom_write_size_cmd32(
		handle,
		MAKE_CMD_HDR(CMD_LOAD_ASSET_PKG, SUB_CMD_NONE, RESP_NONE).all,
		asset_pkg->size, (const char *)asset_pkg->data);
	qmrom_poll_cmd_resp(handle);
	if (COMPARE_RSP(&handle->sstc->payload[0],
			&CMD_LOAD_ASSET_PKG_RSP_HDR) != 0) {
		log_error_response(__func__, &CMD_LOAD_ASSET_PKG_RSP_HDR,
				   (resp_t *)&handle->sstc->payload[0]);
		return SPI_PROTO_WRONG_RESP;
	}

	return 0;
}

static int load_secure_debug_pkg(struct qmrom_handle *handle,
				 const struct firmware *dbg_pkg)
{
	int rc;

	LOG_DBG("%s: starting...\n", __func__);
	rc = qmrom_wait_ready(handle);
	if (rc)
		return rc;

	LOG_DBG("%s: sending CMD_LOAD_SECURE_DEBUG_PKG command\n", __func__);
	rc = qmrom_write_size_cmd32(handle,
				    MAKE_CMD_HDR(CMD_LOAD_SECURE_DEBUG_PKG,
						 SUB_CMD_NONE, RESP_NONE)
					    .all,
				    dbg_pkg->size, (const char *)dbg_pkg->data);
	qmrom_poll_cmd_resp(handle);
	if (COMPARE_RSP(&handle->sstc->payload[0],
			&CMD_LOAD_SECURE_DEBUG_PKG_RSP_HDR) != 0) {
		log_error_response(__func__, &CMD_LOAD_SECURE_DEBUG_PKG_RSP_HDR,
				   (resp_t *)&handle->sstc->payload[0]);
		return SPI_PROTO_WRONG_RESP;
	}

	return 0;
}

static int erase_secure_debug_pkg(struct qmrom_handle *handle)
{
	int rc;

	LOG_DBG("%s: starting...\n", __func__);

	rc = qmrom_wait_ready(handle);
	if (rc)
		return rc;

	LOG_DBG("%s: sending CMD_ERASE_SECURE_DEBUG_PKG command\n", __func__);
	rc = qmrom_write_cmd32(handle, MAKE_CMD_HDR(CMD_ERASE_SECURE_DEBUG_PKG,
						    SUB_CMD_NONE, RESP_NONE)
					       .all);
	qmrom_poll_cmd_resp(handle);
	if (COMPARE_RSP(&handle->sstc->payload[0],
			&CMD_ERASE_SECURE_DEBUG_PKG_RSP_HDR) != 0) {
		log_error_response(__func__,
				   &CMD_ERASE_SECURE_DEBUG_PKG_RSP_HDR,
				   (resp_t *)&handle->sstc->payload[0]);
		return SPI_PROTO_WRONG_RESP;
	}

	return 0;
}

static int run_test_mode(struct qmrom_handle *handle)
{
	int rc;

	LOG_DBG("%s: starting...\n", __func__);

	if ((handle->qm358xx_soc_info.lcs_state != LCS_TEST) &&
	    (handle->qm358xx_soc_info.lcs_state != LCS_RMA)) {
		LOG_ERR("%s: Test mode only available in TEST and RMA LCS.\n",
			__func__);
		return -1;
	}

	rc = qmrom_wait_ready(handle);
	if (rc)
		return rc;

	LOG_DBG("%s: sending CMD_RUN_TEST_MODE command\n", __func__);
	rc = qmrom_write_cmd32(
		handle,
		MAKE_CMD_HDR(CMD_RUN_TEST_MODE, SUB_CMD_NONE, RESP_NONE).all);

	return 0;
}

static int load_sram_fw(struct qmrom_handle *handle,
			const struct firmware *sram_fw)
{
	int rc;
	size_t sent = 0;
	const char *bin_data = (const char *)sram_fw->data;
#ifdef CONFIG_FLASHING_STATS
	qmrom_time start_time;
#endif
	LOG_DBG("%s: starting...\n", __func__);
	rc = qmrom_wait_ready(handle);
	if (rc)
		return rc;

	LOG_DBG("%s: sending CMD_LOAD_SRAM:FILE_SIZE command\n", __func__);
	rc = qmrom_write_size_cmd32(
		handle,
		MAKE_CMD_HDR(CMD_LOAD_SRAM, SUB_CMD_LOAD_SRAM_FILE_SIZE,
			     RESP_NONE)
			.all,
		sizeof(uint32_t), (const char *)&sram_fw->size);
	qmrom_poll_cmd_resp(handle);
	if (COMPARE_RSP(&handle->sstc->payload[0], &CMD_LOAD_SRAM_RSP_HDR) !=
	    0) {
		log_error_response(__func__, &CMD_LOAD_SRAM_RSP_HDR,
				   (resp_t *)&handle->sstc->payload[0]);
		return SPI_PROTO_WRONG_RESP;
	}

	while (sent < sram_fw->size) {
		uint32_t tx_bytes = sram_fw->size - sent;
		if (tx_bytes > CHUNK_SIZE)
			tx_bytes = CHUNK_SIZE;

		LOG_DBG("%s: sending CMD_LOAD_SRAM:IMG_DATA command with %" PRIu32
			" bytes\n",
			__func__, tx_bytes);
#ifdef CONFIG_FLASHING_STATS
		start_time = qmrom_time_get();
#endif
		rc = qmrom_write_size_cmd32(
			handle,
			MAKE_CMD_HDR(CMD_LOAD_SRAM, SUB_CMD_LOAD_SRAM_IMG_DATA,
				     RESP_NONE)
				.all,
			tx_bytes, bin_data);
		if (rc)
			return rc;
		sent += tx_bytes;
		bin_data += tx_bytes;
		if (sent == sram_fw->size) {
			LOG_INFO("%s: flashing done, quitting now\n", __func__);
			break;
		}
		qmrom_poll_cmd_resp(handle);
#ifdef CONFIG_FLASHING_STATS
		update_write_stats(start_time, tx_bytes);
#endif
		if (COMPARE_RSP(&handle->sstc->payload[0],
				&CMD_LOAD_SRAM_RSP_HDR) != 0) {
			log_error_response(__func__, &CMD_LOAD_SRAM_RSP_HDR,
					   (resp_t *)&handle->sstc->payload[0]);
			return SPI_PROTO_WRONG_RESP;
		}
	}
#ifdef CONFIG_FLASHING_STATS
	dump_stats();
#endif

	return 0;
}

static void get_enum_tuple(const enum_tuple_t *tuples, uint32_t value,
			   enum_tuple_t *out)
{
	size_t i;

	out->value = value;
	out->name = "UNKNOWN";
	for (i = 0; tuples[i].name != NULL; i++) {
		if (out->value == tuples[i].value) {
			out->name = tuples[i].name;
			break;
		}
	}
}

static void log_error_response(const char *func, resp_t *expected,
			       resp_t *received)
{
#define RSP_HDR_EXP(x)                                                        \
	(x).cmd.name, (x).cmd.value, (x).sub_cmd.name, (x).sub_cmd.value,     \
		(x).resp_code.name, (x).resp_code.value, (x).error_code.name, \
		(x).error_code.value

	response_enum_tuple_t exp, rec;

	get_enum_tuple(cmd_enum_tuples, expected->cmd_hdr.cmd, &exp.cmd);
	get_enum_tuple(expected->cmd_hdr.cmd == CMD_LOAD_SRAM ?
			       sub_cmd_load_sram_enum_tuples :
			       sub_cmd_load_fw_pkg_enum_tuples,
		       expected->cmd_hdr.sub_cmd, &exp.sub_cmd);
	get_enum_tuple(resp_code_enum_tuples, expected->cmd_hdr.resp,
		       &exp.resp_code);
	get_enum_tuple(error_code_enum_tuples, expected->err_code,
		       &exp.error_code);

	get_enum_tuple(cmd_enum_tuples, received->cmd_hdr.cmd, &rec.cmd);
	get_enum_tuple(received->cmd_hdr.cmd == CMD_LOAD_SRAM ?
			       sub_cmd_load_sram_enum_tuples :
			       sub_cmd_load_fw_pkg_enum_tuples,
		       received->cmd_hdr.sub_cmd, &rec.sub_cmd);
	get_enum_tuple(resp_code_enum_tuples, received->cmd_hdr.resp,
		       &rec.resp_code);
	get_enum_tuple(error_code_enum_tuples, received->err_code,
		       &rec.error_code);

	LOG_ERR("%s: Expected: %s(%#x), %s(%#x), %s(%#x), %s(%#x)"
		" Received: %s(%#x), %s(%#x), %s(%#x), %s(%#x)\n",
		func, RSP_HDR_EXP(exp), RSP_HDR_EXP(rec));
}

int qm358xx_rom_gen_secrets(struct qmrom_handle *handle)
{
	if (!handle->rom_ops.gen_secrets) {
		LOG_ERR("%s: generate secrets not supported on this device\n",
			__func__);
		return -EINVAL;
	}
	return handle->rom_ops.gen_secrets(handle);
}

int qm358xx_rom_load_asset_pkg(struct qmrom_handle *handle,
			       struct firmware *asset_pkg)
{
	if (!handle->rom_ops.load_asset_pkg) {
		LOG_ERR("%s: loading asset packages not supported on this device\n",
			__func__);
		return -EINVAL;
	}
	return handle->rom_ops.load_asset_pkg(handle, asset_pkg);
}

int qm358xx_rom_load_fw_pkg(struct qmrom_handle *handle,
			    const struct firmware *fw_pkg)
{
	if (!handle->rom_ops.load_fw_pkg) {
		LOG_ERR("%s: loading firmware packages not supported on this device\n",
			__func__);
		return -EINVAL;
	}
	return handle->rom_ops.load_fw_pkg(handle, fw_pkg);
}

int qm358xx_rom_load_secure_dbg_pkg(struct qmrom_handle *handle,
				    const struct firmware *dbg_pkg)
{
	if (!handle->rom_ops.load_secure_dbg_pkg) {
		LOG_ERR("%s: loading secure debug packages not supported on this device\n",
			__func__);
		return -EINVAL;
	}
	return handle->rom_ops.load_secure_dbg_pkg(handle, dbg_pkg);
}

int qm358xx_rom_erase_secure_dbg_pkg(struct qmrom_handle *handle)
{
	if (!handle->rom_ops.erase_secure_dbg_pkg) {
		LOG_ERR("%s: erasing secure debug packages not supported on this device\n",
			__func__);
		return -EINVAL;
	}
	return handle->rom_ops.erase_secure_dbg_pkg(handle);
}

int qm358xx_rom_run_test_mode(struct qmrom_handle *handle)
{
	if (!handle->rom_ops.run_test_mode) {
		LOG_ERR("%s: test mode not supported on this device\n",
			__func__);
		return -EINVAL;
	}
	return handle->rom_ops.run_test_mode(handle);
}

int qm358xx_rom_load_sram_fw(struct qmrom_handle *handle,
			     struct firmware *sram_fw)
{
	if (!handle->rom_ops.load_sram_fw) {
		LOG_ERR("%s: loading SRAM firmware not supported on this device\n",
			__func__);
		return -EINVAL;
	}
	return handle->rom_ops.load_sram_fw(handle, sram_fw);
}
