ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1/include \

# KBUILD_EXTRA_SYMBOLS += $(CURDIR)/../../kernel/msm-$(MODULE_KERNEL_VERSION)/Module.symvers
# KBUILD_EXTRA_SYMBOLS += $(CURDIR)/../../kernel_platform/msm-kernel/Module.symvers

obj-m += mmi_lpm_dbg.o
