ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel_platform/common
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/moto_binder


obj-m += moto_binder.o

moto_binder-y := moto_binder_status.o moto_binder_sysfs.o moto_binder_main.o

