# add -Wall to try to catch everything we can.
ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/sensors \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/chipone_tddi_mmi_v2_u \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.12/drivers/gpu/drm/mediatek/mediatek_v2 \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.12/drivers/gpu/drm \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.12/include

ifneq ($(filter icnl9922c,$(CONFIG_INPUT_CHIPONE_IC_NAME)),)
	EXTRA_CFLAGS += -DCONFIG_CTS_IC_NAME_ICNL9922C
endif

ifneq ($(filter icnl9922,$(CONFIG_INPUT_CHIPONE_IC_NAME)),)
	EXTRA_CFLAGS += -DCONFIG_CTS_IC_NAME_ICNL9922
endif

ifneq ($(filter icnl9951,$(CONFIG_INPUT_CHIPONE_IC_NAME)),)
	EXTRA_CFLAGS += -DCONFIG_CTS_IC_NAME_ICNL9951
endif

ifneq ($(filter m y,$(CONFIG_CHIPONE_ESD)),)
EXTRA_CFLAGS += -DCONFIG_CHIPONE_ESD_EN
endif

ifneq ($(filter m y,$(CONFIG_CHIPONE_MTK_CHECK_PANEL)),)
	EXTRA_CFLAGS += -DCTS_MTK_CHECK_PANEL
endif

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_MTK_GET_PANEL)),)
	EXTRA_CFLAGS += -DCTS_MTK_GET_PANEL
endif

ifneq ($(filter m y, $(CONFIG_MTK_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_MTK_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y, $(CONFIG_CHIPONE_CHECK_DEVICE_BOOTMODE)),)
	EXTRA_CFLAGS += -DCTS_CHECK_DEVICE_BOOTMODE
endif

ifneq ($(filter m y,$(CONFIG_CTS_INPUT_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DCHIPONE_SENSOR_EN
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

ifneq ($(filter m y,$(CONFIG_CTS_NOTIFY_TOUCH_STATE)),)
	EXTRA_CFLAGS += -DCHIPONE_SET_TOUCH_STATE
endif

ifneq ($(filter m y,$(CONFIG_INPUT_CHIPONE_EARJACK)),)
EXTRA_CFLAGS += -DCONFIG_CHIPONE_EARJACK_EN
endif

ifneq ($(filter m y,$(CONFIG_TARGET_BUILD_FACTORY)),)
	EXTRA_CFLAGS += -DTARGET_BUILD_FACTORY
endif

ifneq ($(filter m y, $(CONFIG_STOWED_MODE_EN)),)
	EXTRA_CFLAGS += -DCTS_STOWED_MODE_EN
endif

ifneq ($(filter m y,$(CONFIG_CTS_LAST_TIME)),)
    EXTRA_CFLAGS += -DCONFIG_CTS_LAST_TIME
endif

ifneq ($(filter m y, $(CONFIG_CHIPONE_LOG_CAPTURE)),)
        EXTRA_CFLAGS += -DCONFIG_CTS_LOG_CAPTURE
endif

ifneq ($(filter m y, $(CONFIG_CHIPONE_FORCE_UP_ENABLE)),)
	EXTRA_CFLAGS += -DCONFIG_CTS_FORCE_UP_ENABLE
endif

obj-m := chipone_tddi_mmi_v2_u.o

chipone_tddi_mmi_v2_u-objs := cts_driver.o
chipone_tddi_mmi_v2_u-objs += cts_core.o
chipone_tddi_mmi_v2_u-objs += cts_sfctrlv2.o
chipone_tddi_mmi_v2_u-objs += cts_spi_flash.o
chipone_tddi_mmi_v2_u-objs += cts_firmware.o
chipone_tddi_mmi_v2_u-objs += cts_test.o
chipone_tddi_mmi_v2_u-objs += cts_charger_detect.o
chipone_tddi_mmi_v2_u-objs += cts_earjack_detect.o
chipone_tddi_mmi_v2_u-objs += cts_tcs.o
chipone_tddi_mmi_v2_u-objs += cts_platform.o
chipone_tddi_mmi_v2_u-objs += cts_tool.o
chipone_tddi_mmi_v2_u-objs += cts_sysfs.o
chipone_tddi_mmi_v2_u-objs += cts_strerror.o
chipone_tddi_mmi_v2_u-objs += cts_oem.o

