# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/power/mmi_decrete_charger_cp_qc3p \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/supply

obj-m += mmi_decrete_charger_cp_qc3p.o
mmi_decrete_charger_cp_qc3p-objs += mmi_charger_class.o
mmi_decrete_charger_cp_qc3p-objs += mmi_charger_core.o
mmi_decrete_charger_cp_qc3p-objs += mmi_pump_charger.o
mmi_decrete_charger_cp_qc3p-objs += mmi_charger_pump_policy.o
mmi_decrete_charger_cp_qc3p-objs += mtk_pmic_charger.o
mmi_decrete_charger_cp_qc3p-objs += pps.o

#KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../bq2597x_mmi_discrete/$(GKI_OBJ_MODULE_DIR)/Module.symvers
#$(warning CURDIR:$(CURDIR) KBUILD_EXTMOD:$(KBUILD_EXTMOD) GKI_OBJ_MODULE_DIR:$(GKI_OBJ_MODULE_DIR))
#KBUILD_EXTRA_SYMBOLS += $(KBUILD_EXTMOD)/../../bq2597x_mmi_discrete.ko_intermediates/LINKED/Module.symvers
