DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

ifeq ($(AW9610_MTK_CHARGER),true)
    KERNEL_CFLAGS  += CONFIG_AW9610_MTK_CHARGER=y
endif

ifeq ($(AW9610_MTK_KERNEL419_CHARGER_TYPE), true)
    KERNEL_CFLAGS  += CONFIG_AW9610_MTK_KERNEL419_CHARGER_TYPE=y
endif

ifeq ($(AW9610_MTK_KERNEL5XX_CHARGER_TYPE),true)
    KERNEL_CFLAGS  += CONFIG_AW9610_MTK_KERNEL5XX_CHARGER_TYPE=y
endif

include $(CLEAR_VARS)
LOCAL_MODULE := aw9610x.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
LOCAL_ADDITIONAL_DEPENDENCIES := $(KERNEL_MODULES_OUT)/sensors_class.ko
LOCAL_REQUIRED_MODULES := sensors_class.ko
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
include $(DLKM_DIR)/AndroidKernelModule.mk

