# add -Wall to try to catch everything we can.
#MTK have kernel-4.14 and kernel-4.19 in the same dir,so we can't use below method
#KERNEL_DIR_PATH = $(shell find $(TOP)/kernel* -type d -name  "kernel-*" | head -1)
KERNEL_VERSION_NAME = $(shell basename $(KERNEL_DIR_PATH))
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += -I$(TOP)/$(KERNEL_VERSION_NAME)/drivers/base

ifneq ($(filter m y,$(CONFIG_AW9610_MTK_CHARGER)),)
	EXTRA_CFLAGS += -DCONFIG_AW9610_MTK_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_AW9610_MTK_KERNEL419_CHARGER_TYPE)),)
	EXTRA_CFLAGS += -DCONFIG_AW9610_MTK_KERNEL419_CHARGER_TYPE
endif

ifneq ($(filter m y,$(CONFIG_AW9610_MTK_KERNEL5XX_CHARGER_TYPE)),)
	EXTRA_CFLAGS += -DCONFIG_AW9610_MTK_KERNEL5XX_CHARGER_TYPE
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers

obj-m := aw9610x.o
aw9610x-objs += aw9610x_sar.o
aw9610x-objs += aw_bin_parse.o


