# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/pt




obj-m += pt.o
pt-y := pt_core.o pt_mt_common.o
#pt-objs += pt_mta.o
pt-y += pt_mtb.o
pt-y += pt_btn.o
pt-y += pt_proximity.o
pt-y += pt_devtree.o pt_platform.o
pt-y += pt_i2c.o
#pt-objs += pt_spi.o
obj-m += cypsoc_picoleaf.o

ifneq ($(filter m y, $(NDT_DATA_FOR_TOUCH)),)
	EXTRA_CFLAGS += -DNDT_DATA_EN
endif


