# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += -I$(srctree)

# vendor hook for mm
obj-m += moto_metrics.o
moto_metrics-y += init_metrics.o perf_metrics.o thermal_metrics.o


