# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

GITVERSION := unknown

# Add defines in subdir-ccflags
subdir-ccflags-y := -I$(src) -I$(src)/include \
 -I$(srctree)/$(src) -I$(srctree)/$(src)/include -Werror -Wall
subdir-ccflags-y += -DGITVERSION="\"$(GITVERSION)\""
# Used in drivers/net/ieee802154/qm & net/mcps802154
subdir-ccflags-$(CONFIG_MCPS802154_TESTMODE) += -DCONFIG_MCPS802154_TESTMODE

# Ensure include for exported API is visible for all modules
# accross the new build tree.
subdir-ccflags-y += -I$(src)/drivers/base/qm \
 -I$(srctree)/$(src)/drivers/base/qm

# I want debug info in our modules to be able to analyse dumpstack().
# Only if not already enabled by CONFIG_DEBUG_INFO.
ifneq ($(CONFIG_DEBUG_INFO),y)
subdir-ccflags-y += -g
endif

ifneq ($(filter m y,$(CONFIG_SYSFS_IMPORT_REMOVE_SELF)),)
        EXTRA_CFLAGS += -DCONFIG_SYSFS_IMPORT_REMOVE_SELF
endif

obj-$(CONFIG_QM35_IEEE_NL) += drivers/net/ieee802154/qm/ net/mcps802154/

# QM35 core apis module
qm35_apis-y := \
		drivers/base/qm/qm35_bypass.o \
		drivers/base/qm/qm35_core.o \
		drivers/base/qm/qm35_ids.o \
		drivers/base/qm/qm35_notifier.o \
		drivers/base/qm/qm35_transport.o \
		drivers/base/qm/qm35_trc.o

obj-m += qm35_apis.o

# QM35 UCI char device
qm35_uci_dev-y :=\
		drivers/base/qm/qm35_uci_dev_main.o \
		drivers/base/qm/qm35_uci_dev_trc.o

obj-m += qm35_uci_dev.o

# QM35 Log module
qm35_logs-y := \
		drivers/base/qm/qm35_logs.o
obj-m += qm35_logs.o

# QM35 coredump extractor
qm35_coredump-y := \
		drivers/base/qm/qm35_coredump.o
obj-m += qm35_coredump.o

# Allow include external library files.
subdir-ccflags-y += -I$(src)/drivers/spi/qm/libqmrom/include -I$(src)/drivers/spi/qm/libfwupdater/include\
 -I$(srctree)/$(src)/drivers/spi/qm/libqmrom/include -I$(srctree)/$(src)/drivers/spi/qm/libfwupdater/include
subdir-ccflags-y += -DCONFIG_QM35_FLASHING

# QM35 transport modules
# Build qm35_spi.ko only if SPI supported on target kernel.
qm35_spi-y := \
		drivers/spi/qm/libfwupdater/src/fwupdater.o \
		drivers/spi/qm/libqmrom/src/qm357xx_rom_b0.o \
		drivers/spi/qm/libqmrom/src/qm357xx_rom_c0.o \
		drivers/spi/qm/libqmrom/src/qm357xx_rom_common.o \
		drivers/spi/qm/libqmrom/src/qm358xx_rom.o \
		drivers/spi/qm/libqmrom/src/qmrom_common.o \
		drivers/spi/qm/libqmrom/src/qmrom_log.o \
		drivers/spi/qm/qm35_hsspi.o \
		drivers/spi/qm/qm35_spi_fw.o \
		drivers/spi/qm/qm35_spi_main.o \
		drivers/spi/qm/qm35_spi_pm.o \
		drivers/spi/qm/qm35_spi_setup.o \
		drivers/spi/qm/qm35_spi_thread.o \
		drivers/spi/qm/qm35_spi_transport.o \
		drivers/spi/qm/qm35_spi_trc.o \
		drivers/spi/qm/qm35_uci_probe.o \
		drivers/spi/qm/qmrom_wrapper.o

# Uncomment to change default debug_flags to 18 (AUTO_TRACE|NO_RESET_ON_SUSPEND)
#CFLAGS_qm35_spi_main.o := -DDEFAULT_DEBUG_FLAGS=18
# Uncomment to change default auto suspend delay value to 250 MS
CFLAGS_drivers/spi/qm/qm35_spi_pm.o := -DAUTOSUSPEND_DELAY_MS=0


CFLAGS_drivers/spi/qm/libqmrom/src/qm357xx_rom_c0.o := -DCONFIG_FLASHING_STATS
CFLAGS_drivers/spi/qm/libqmrom/src/qm358xx_rom.o := -DCONFIG_FLASHING_STATS
CFLAGS_drivers/spi/qm/libfwupdater/src/fwupdater.o := -DCONFIG_FLASHING_STATS
obj-m += qm35_spi.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../mmi_info/Module.symvers
