EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_CHIPONE_GPIO_CTRL_VDD)),)
	EXTRA_CFLAGS += -DCONFIG_CHIPONE_GPIO_CTRL_VDD
endif

ifneq ($(filter m y,$(CONFIG_CHIPONE_PMIC_CTRL_VDD)),)
        EXTRA_CFLAGS += -DCONFIG_CHIPONE_PMIC_CTRL_VDD
endif

ifneq ($(filter m y,$(CONFIG_CHIPONE_MTK_KERNEL5XX_WAKE_TYPE)),)
	EXTRA_CFLAGS += -DCONFIG_CHIPONE_MTK_KERNEL5XX_WAKE_TYPE
endif

fpsensor_mtk_spi-y += fpsensor_spi_tee.o

obj-m += fpsensor_mtk_spi.o
