load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

define_mgk_ko(
    name = "moto_mmtrack",
    srcs = glob([
        "*.c",
        "*.h",
        "Kbuild",
        "Makefile",
    ]) + [
        "//motorola/kernel/modules/drivers/moto_sched:sched_headers",
    ],
    deps = [
        "//motorola/kernel/modules/drivers/moto_swap5:moto_swap5",
    ],

    outs = ["moto_mmtrack.ko"],
)
