# add -Wall to try to catch everything we can.
ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

ifeq ($(DEVICE_MODULES_PATH),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
EXTRA_CFLAGS += \
		-I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/

EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_touch_v3_u_mmi \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_touch_v3_u_mmi/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_touch_v3_u_mmi/focaltech_test

obj-m := focaltech_touch_v3_u_mmi.o
focaltech_touch_v3_u_mmi-objs += focaltech_core.o
focaltech_touch_v3_u_mmi-objs += focaltech_ex_fun.o
focaltech_touch_v3_u_mmi-objs += focaltech_ex_mode.o
focaltech_touch_v3_u_mmi-objs += focaltech_gesture.o
focaltech_touch_v3_u_mmi-objs += focaltech_esdcheck.o
focaltech_touch_v3_u_mmi-objs += focaltech_point_report_check.o
focaltech_touch_v3_u_mmi-objs += focaltech_flash.o
focaltech_touch_v3_u_mmi-objs += focaltech_spi.o
focaltech_touch_v3_u_mmi-objs += focaltech_test/focaltech_test.o
focaltech_touch_v3_u_mmi-objs += focaltech_test/focaltech_test_ini.o
focaltech_touch_v3_u_mmi-objs += focaltech_ts_config.o
focaltech_touch_v3_u_mmi-objs += focaltech_debug.o

ifneq ($(filter ft3681,$(CONFIG_FOCALTECH_TOUCH_IC_NAME)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_IC_FT3681
	focaltech_touch_v3_u_mmi-objs += focaltech_flash/focaltech_upgrade_ft3681.o
	focaltech_touch_v3_u_mmi-objs += focaltech_test/supported_ic/focaltech_test_ft3681.o
endif

ifneq ($(filter ft3683g,$(CONFIG_FOCALTECH_TOUCH_IC_NAME)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_IC_FT3683G
	EXTRA_CFLAGS += -DCONFIG_FTS_NOISE_TEST_P2P
	focaltech_touch_v3_u_mmi-objs += focaltech_flash/focaltech_upgrade_ft3683g.o
	focaltech_touch_v3_u_mmi-objs += focaltech_test/supported_ic/focaltech_test_ft3683g.o
endif

ifneq ($(filter m y,$(CONFIG_FTS_INPUT_PROTOCOL_V0)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_INPUT_PROTOCOL_V0
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
       EXTRA_CFLAGS += -DCONFIG_INPUT_TOUCHSCREEN_MMI
       focaltech_touch_v3_u_mmi-objs += focaltech_ts_mmi.o
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_V3_MMI_ENABLE_DOUBLE_TAP)),)
	EXTRA_CFLAGS += -DFOCALTECH_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_V3_MMI_ENABLE_PALM)),)
	EXTRA_CFLAGS += -DFOCALTECH_PALM_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_V3_MMI_PEN_NOTIFIER)),)
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../misc/pen/Module.symvers
	EXTRA_CFLAGS += -DFOCALTECH_PEN_NOTIFIER
endif

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y, $(CONFIG_MTK_PANEL_NOTIFICATIONS)),)
        EXTRA_CFLAGS += -DCONFIG_MTK_PANEL_NOTIFICATIONS
        EXTRA_CFLAGS += -DCFG_MTK_PANEL_NOTIFIER
endif

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif

ifneq ($(filter m y, $(CONFIG_FTS_NOISE_TEST_P2P)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_NOISE_TEST_P2P
endif

ifneq ($(filter m y, $(CONFIG_FTS_COMPATIBLE_WITH_GKI)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_COMPATIBLE_WITH_GKI
endif

ifneq ($(filter m y, $(CONFIG_FTS_DOUBLE_TAP_CONTROL)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_DOUBLE_TAP_CONTROL
endif

ifneq ($(CONFIG_SUPPORT_FTS_HIRES_X),)
	EXTRA_CFLAGS += -DCONFIG_FTS_HIRES_EN
	EXTRA_CFLAGS += -DCONFIG_FTS_HIRES_X=$(CONFIG_SUPPORT_FTS_HIRES_X)
endif

ifneq ($(filter m y, $(CONFIG_FTS_SUPPORT_HIGH_RESOLUTION)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_SUPPORT_HIGH_RESOLUTION
endif

ifneq ($(filter m y, $(CONFIG_FTS_VDD_GPIO_CONTROL)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_VDD_GPIO_CONTROL
endif

ifneq ($(filter m y,$(CONFIG_FTS_LAST_TIME)),)
    EXTRA_CFLAGS += -DCONFIG_FTS_LAST_TIME
endif

ifneq ($(filter m y,$(CONFIG_FTS_INPUT_ID)),)
    EXTRA_CFLAGS += -DCONFIG_FTS_INPUT_ID
endif

ifneq ($(filter m y,$(CONFIG_ENABLE_FTS_PALM_CANCEL)),)
    EXTRA_CFLAGS += -DCONFIG_ENABLE_FTS_PALM_CANCEL
endif

ifneq ($(filter m y,$(CONFIG_FTS_GAME_MODE_EN)),)
    EXTRA_CFLAGS += -DCONFIG_FTS_GAME_MODE_EN
endif

ifneq ($(filter m y,$(CONFIG_FOCALTECH_REPORT_PRESSURE_DISABLE)),)
    EXTRA_CFLAGS += -DCONFIG_FOCALTECH_REPORT_PRESSURE_DISABLE
endif

ifneq ($(filter m y,$(CONFIG_ENABLE_FTS_PALM_CANCEL_BY_ID)),)
    EXTRA_CFLAGS += -DCONFIG_ENABLE_FTS_PALM_CANCEL_BY_ID
endif

ifneq ($(filter m y,$(CONFIG_TOUCH_HARDWARE_STATUS)),)
    EXTRA_CFLAGS += -DCONFIG_FTS_HARDWARE_STATUS
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

ifneq ($(findstring _factory,$(TARGET_PRODUCT)),)
USE_TARGET_PRODUCT := $(strip $(subst _factory,, $(TARGET_PRODUCT)))
else
USE_TARGET_PRODUCT := $(TARGET_PRODUCT)
endif

ifeq ($(TARGET_PRODUCT),)
USE_TARGET_PRODUCT := $(CONFIG_MTK_PROJECT_NAME)
$(warning "USE_TARGET_PRODUCT = $(USE_TARGET_PRODUCT)")
endif

ifneq ($(filter bangkk%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_BANGKK
else ifneq ($(filter avatrn%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_AVATRN
else ifneq ($(filter scout%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_SCOUT
else ifneq ($(filter cybert%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_CYBERT
else ifneq ($(filter fuji%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_FUJI
else ifneq ($(filter naples%, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_NAPLES
endif

$(warning "focalteh EXTRA_CFLAGS = $(EXTRA_CFLAGS)")

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_u_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
