load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

define_mgk_ko(
    name = "ilitek_tddi_v3",
    srcs = glob([
        "*.c",
        "*.h",
        "firmware/*",
        "Kbuild",
        "Makefile",
    ]) + [
        "//motorola/kernel/modules:public_headers",
    ],
    deps = [
        "//motorola/kernel/modules/drivers/sensors:sensors_class",
    ],
    outs = ["ilitek_tddi_v3.ko"],
)
